Repository gazebosim/gz-sim, pull requests merged in 2020-05, with the labels that each got.

#129 [ign-gazebo3] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 🏰 citadel

#128 [ign-gazebo2] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 📜 blueprint

#127 Port support for computing model bounding box in physics system
  Changelog.md
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/components/AxisAlignedBox.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  test/integration/physics_system.cc
Labels: 🏰 citadel

#120 Fix for issue 55
  Changelog.md
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/physics/Physics.cc
  test/integration/battery_plugin.cc
  test/integration/breadcrumbs.cc
Labels: physics, 📜 blueprint

#135 Prepare for 2.17.0
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#130 [master] Workflow updates
  .github/ci-bionic/dependencies.yaml
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 🔮 dome

#107 Add shapes plugin
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/shapes/CMakeLists.txt
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/shapes/Shapes.hh
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/box.png
  src/gui/plugins/shapes/cylinder.png
  src/gui/plugins/shapes/sphere.png
  src/rendering/SceneManager.cc
Labels: 📜 blueprint

#142 Multiple resource paths separated by colon
  src/cmd/cmdgazebo.rb.in
  src/ign_TEST.cc
Labels: bug, 🏰 citadel

#143 3.1.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#132 DetachableJoint system: Add option to suppress warning about missing child model
  Changelog.md
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
Labels: 📜 blueprint

#146 Support multi entity spawn
  CMakeLists.txt
  Changelog.md
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
Labels: 📜 blueprint

#148 Bump ign-msgs version to 4.9
  CMakeLists.txt
Labels: 📜 blueprint

#145 Fix ign-gui version 😅
  CMakeLists.txt
Labels: 🏰 citadel

#149 2 to 3 may2020
  CMakeLists.txt
  Changelog.md
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/shapes/CMakeLists.txt
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/shapes/Shapes.hh
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/box.png
  src/gui/plugins/shapes/cylinder.png
  src/gui/plugins/shapes/sphere.png
  src/rendering/SceneManager.cc
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
Labels: 🏰 citadel

#152 Fixed docblock showGrid
  include/ignition/gazebo/rendering/RenderUtil.hh
Labels: documentation, 🔮 dome

#151 3 ➡️ 4 logging
  src/ServerPrivate.cc
  src/ign.cc
  src/systems/log/LogRecord.cc
  test/integration/log_system.cc
Labels: 🔮 dome

#140 Support TPE (more optional physics features)
  src/systems/physics/Physics.cc
Labels: enhancement, physics, 🏰 citadel

#125 Add PerformerDetector, a system for detecting when performers enter a specified region
  Changelog.md
  examples/worlds/performer_detector.sdf
  src/LevelManager.cc
  src/systems/CMakeLists.txt
  src/systems/performer_detector/CMakeLists.txt
  src/systems/performer_detector/PerformerDetector.cc
  src/systems/performer_detector/PerformerDetector.hh
  test/integration/CMakeLists.txt
  test/integration/performer_detector.cc
  test/worlds/performer_detector.sdf
Labels: 📜 blueprint

#139 Add TriggeredPublisher system
  Changelog.md
  examples/worlds/triggered_publisher.sdf
  src/systems/CMakeLists.txt
  src/systems/triggered_publisher/CMakeLists.txt
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/triggered_publisher/TriggeredPublisher.hh
  test/integration/CMakeLists.txt
  test/integration/triggered_publisher.cc
  test/worlds/triggered_publisher.sdf
  tutorials.md.in
  tutorials/triggered_publisher.md
Labels: 📜 blueprint
