Repository gazebosim/gz-sim, pull requests merged in 2020-07, with the labels that each got.

#216 Joint position controller system
  examples/worlds/joint_position_controller.sdf
  src/systems/CMakeLists.txt
  src/systems/joint_position_controller/CMakeLists.txt
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_position_controller/JointPositionController.hh
  test/integration/CMakeLists.txt
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller.sdf
Labels: 📜 blueprint

#169 [Citadel] [TPE] Add velocity cmd
  examples/worlds/velocity_control.sdf
  include/ignition/gazebo/components/AngularVelocityCmd.hh
  include/ignition/gazebo/components/LinearVelocityCmd.hh
  src/systems/CMakeLists.txt
  src/systems/physics/Physics.cc
  src/systems/velocity_control/CMakeLists.txt
  src/systems/velocity_control/VelocityControl.cc
  src/systems/velocity_control/VelocityControl.hh
  test/integration/CMakeLists.txt
  test/integration/velocity_control_system.cc
  test/worlds/velocity_control.sdf
Labels: enhancement, physics, 🏰 citadel

#233 Joint velocity controller using force
  examples/worlds/joint_controller.sdf
  src/systems/joint_controller/JointController.cc
  src/systems/joint_controller/JointController.hh
  test/integration/joint_controller_system.cc
  test/worlds/joint_controller.sdf
Labels: 📜 blueprint

#230 Battery updates - part3
  Changelog.md
  examples/worlds/linear_battery_demo.sdf
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  tutorials/battery.md
Labels: 📜 blueprint

#236 Added additional pose offset for the performer detector
  Changelog.md
  src/systems/performer_detector/PerformerDetector.cc
  src/systems/performer_detector/PerformerDetector.hh
Labels: 📜 blueprint

#251 Preparing for 2.21.0 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#249 Enable alpha based transparency on PBR materials by default
  src/rendering/SceneManager.cc
Labels: 🔮 dome

#244 Names with spaces: add string serializer
  Changelog.md
  examples/worlds/fuel.sdf
  include/ignition/gazebo/components/Actor.hh
  include/ignition/gazebo/components/ChildLinkName.hh
  include/ignition/gazebo/components/LevelEntityNames.hh
  include/ignition/gazebo/components/Name.hh
  include/ignition/gazebo/components/ParentLinkName.hh
  include/ignition/gazebo/components/PerformerAffinity.hh
  include/ignition/gazebo/components/PhysicsEnginePlugin.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/components/SourceFilePath.hh
  test/integration/components.cc
Labels: 🔮 dome

#259 Prepare for 2.22.0 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#255 Backport support for <uri>s from Fuel
  .github/ci-bionic/after_make.sh
  examples/worlds/fuel.sdf
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/gui/GuiRunner.cc
Labels: 📜 blueprint

#253 Some UI tweaks to Resource Spawner
  src/gui/plugins/resource_spawner/NoThumbnail.png
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/plugins/resource_spawner/copy_object.png
  src/gui/plugins/resource_spawner/folder_closed.png
  src/gui/plugins/resource_spawner/folder_open.png
Labels: GUI, 📜 blueprint

#264 2.23.0 release prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint
