Repository gazebosim/gz-sim, pull requests merged in 2020-10, with the labels that each got.

#359 Add search and sort for resource spawner
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/plugins/resource_spawner/Search.svg
Labels: GUI, enhancement, 🏰 citadel

#394 Add nullchecks for scene
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/sensors/Sensors.cc
Labels: 🏰 citadel

#336 add 10k actors and generalize actors pose in erb
  examples/worlds/3k_shapes.sdf
  examples/worlds/actors_population.sdf
  examples/worlds/actors_population.sdf.erb
Labels: 🏰 citadel

#388 docker: update Dockerfiles to use focal images
  docker/Dockerfile.base
  docker/Dockerfile.ignition
  docker/README.md
  docker/run.bash
Labels: 🔮 dome

#395 Fix source build instructions for ign-gazebo3
  README.md
Labels: 🏰 citadel

#362 2 ➡️ 3
  CMakeLists.txt
  Changelog.md
  examples/worlds/diff_drive_skid.sdf
  examples/worlds/trisphere_cycle_wheel_slip.sdf
  include/ignition/gazebo/components/LogPlaybackStatistics.hh
  include/ignition/gazebo/components/SlipComplianceCmd.hh
  src/Conversions.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/playback_gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/playback_scrubber/CMakeLists.txt
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.hh
  src/gui/plugins/playback_scrubber/PlaybackScrubber.qml
  src/gui/plugins/playback_scrubber/PlaybackScrubber.qrc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/systems/CMakeLists.txt
  src/systems/log/LogPlayback.cc
  src/systems/log/LogRecord.cc
  src/systems/physics/Physics.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/wheel_slip/CMakeLists.txt
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wheel_slip/WheelSlip.hh
  test/integration/CMakeLists.txt
  test/integration/log_system.cc
  test/integration/wheel_slip.cc
  test/worlds/diff_drive_skid.sdf
  test/worlds/tire_drum.sdf
  test/worlds/triball_drift.sdf
  test/worlds/trisphere_cycle_wheel_slip.sdf
  tutorials/gui_config.md
Labels: 🏰 citadel

#375 Add more link APIs, with tutorial
  include/ignition/gazebo/Link.hh
  include/ignition/gazebo/Model.hh
  src/Link.cc
  src/Model.cc
  test/integration/link.cc
  test/integration/model.cc
  tutorials/migration_link_api.md
  tutorials/migration_model_api.md
Labels: migration, 🏰 citadel

#403 Fix source build instructions for ign-gazebo2
  README.md
Labels: 📜 blueprint

#404 Updated source build instructions for ign-gazebo4
  README.md
Labels: 🏢 edifice, 🔮 dome

#258 Support nested model
  CMakeLists.txt
  examples/worlds/nested_model.sdf
  include/ignition/gazebo/SdfEntityCreator.hh
  include/ignition/gazebo/Util.hh
  src/SdfEntityCreator.cc
  src/SdfGenerator.cc
  src/Util.cc
  src/Util_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Pose3d.qml
  src/systems/physics/Physics.cc
  test/integration/log_system.cc
  test/integration/physics_system.cc
  test/integration/pose_publisher_system.cc
  test/integration/save_world.cc
  test/worlds/log_record_dbl_pendulum.sdf
  test/worlds/nested_model.sdf
Labels: enhancement, 🏰 citadel

#406 Add screenshots to GUI config tutorial
  CMakeLists.txt
  tutorials/files/gui_config/cmd_line.png
  tutorials/files/gui_config/dark_gui.png
  tutorials/files/gui_config/default_gui.png
  tutorials/files/gui_config/fuel_preview.png
  tutorials/files/gui_config/fuel_preview_no_gui.png
  tutorials/files/gui_config/save_config.gif
  tutorials/gui_config.md
Labels: documentation, 🏰 citadel

#378 More world APIs, helper function ComponentData
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/World.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/CMakeLists.txt
  src/EntityComponentManager_TEST.cc
  src/Link.cc
  src/World.cc
  src/World_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/world.cc
  tutorials.md.in
  tutorials/migration_world_api.md
Labels: migration, 🏰 citadel

#411 Improve fork experience
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#413 Suggestions to #412: set grid material
  src/gui/plugins/grid_config/GridConfig.cc
Labels: bug, 🏰 citadel

#412 Fix a crash in the grid_config plugin
  src/gui/plugins/grid_config/GridConfig.cc
Labels: 🏰 citadel

#424 [Citadel] Document deprecation of playback <path> SDF param
  Migration.md
  examples/worlds/log_playback.sdf
  tutorials/log.md
Labels: 🏰 citadel

#425 [Blueprint] Document deprecation of playback <path> SDF param
  Migration.md
  examples/worlds/log_playback.sdf
  tutorials/log.md
Labels: 📜 blueprint

#402 Enable mouse highlighting for resource spawner
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
Labels: 🏰 citadel

#373 Add support for custom render engines
  CMakeLists.txt
  include/ignition/gazebo/Util.hh
  src/cmd/cmdgazebo.rb.in
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/sensors/Sensors.cc
Labels: 🏰 citadel

#426 View angle icons higher contrast
  src/gui/plugins/view_angle/view_angle_back.png
  src/gui/plugins/view_angle/view_angle_bottom.png
  src/gui/plugins/view_angle/view_angle_front.png
  src/gui/plugins/view_angle/view_angle_home.png
  src/gui/plugins/view_angle/view_angle_left.png
  src/gui/plugins/view_angle/view_angle_right.png
  src/gui/plugins/view_angle/view_angle_top.png
Labels: GUI, enhancement
