Repository gazebosim/gz-sim, pull requests merged in 2020-11, with the labels that each got.

#416 Component Vector -> Map ECM Optimization
  src/EntityComponentManager.cc
Labels: enhancement, 🏰 citadel

#433 Added tests for the AnimationTime component
  include/ignition/gazebo/components/Actor.hh
  test/integration/components.cc
Labels: 🔮 dome

#439 2 ➡️ 3
  README.md
Labels: 🏰 citadel

#430 Bump in edifice: ign-rendering5
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  docker/Dockerfile.nightly
  tutorials/migrating_ardupilot_plugin.md
Labels: 🏢 edifice

#440 ⬆️ 3.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#450 Fix pose msg conversion when msg is missing orientation
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: 🏰 citadel

#443 Resolve updated codecheck issues
  src/LevelManager.cc
  src/SdfGenerator.cc
  src/SimulationRunner.cc
  src/gui/PathManager.cc
  src/gui/PathManager.hh
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/ign.cc
  src/network/NetworkManagerPrimary.cc
  src/network/PeerTracker.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/contact/Contact.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/imu/Imu.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/log/LogPlayback.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/multicopter_control/Common.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/physics/Physics.cc
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wind_effects/WindEffects.cc
Labels: 📜 blueprint

#455 Use new backpack version in tests
  src/SdfGenerator.cc
  src/SdfGenerator_TEST.cc
  test/worlds/save_world.sdf
Labels: tests, 📜 blueprint

#454 Fix segfault in the Breadcrumb system when associated model is unloaded
  src/systems/breadcrumbs/Breadcrumbs.cc
  test/integration/breadcrumbs.cc
  test/worlds/breadcrumbs_levels.sdf
Labels: bug, 📜 blueprint

#457 2 ➡️ 3
  src/LevelManager.cc
  src/SdfGenerator.cc
  src/SdfGenerator_TEST.cc
  src/SimulationRunner.cc
  src/gui/PathManager.cc
  src/gui/PathManager.hh
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/ign.cc
  src/network/NetworkManagerPrimary.cc
  src/network/PeerTracker.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/contact/Contact.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/imu/Imu.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/log/LogPlayback.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/multicopter_control/Common.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/breadcrumbs.cc
  test/worlds/breadcrumbs_levels.sdf
  test/worlds/save_world.sdf
Labels: 🏰 citadel

#442 Added user commands to example thermal camera world
  examples/worlds/thermal_camera.sdf
Labels: 🏰 citadel

#436 Helper function to set component data
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/EntityComponentManager_TEST.cc
Labels: migration, 🏰 citadel

#432 Remove unneeded if statement
  src/EntityComponentManager.cc
Labels: 🏰 citadel

#462 Make the tunnels example world more interesting
  examples/worlds/tunnel.sdf
Labels: 🔮 dome

#463 Fixes flaky RecordAndPlayback test in INTEGRATION_log_system
  test/integration/log_system.cc
Labels: tests, 🏰 citadel

#452 👩‍🌾 Make PeerTracker test more robust
  src/network/PeerTracker_TEST.cc
  test/integration/physics_system.cc
Labels: tests, 🏰 citadel
