Repository gazebosim/gz-sim, pull requests merged in 2020-09, with the labels that each got.

#320 Adjust grid config starting size
  src/gui/plugins/grid_config/GridConfig.qml
Labels: 🏰 citadel

#318 Prepare for ign-gazebo 3.3.0 release
  CMakeLists.txt
  Changelog.md
  test/integration/breadcrumbs.cc
Labels: 🏰 citadel

#288 Add error handling for JointAxis::SetXyz and remove use of use_parent_model_frame
  .github/workflows/ci-bionic.yml
  src/Conversions.cc
  src/Conversions_TEST.cc
  test/integration/components.cc
Labels: 🔮 dome

#334 2.24.0 release prep
  CMakeLists.txt
  Changelog.md
  test/integration/breadcrumbs.cc
Labels: 📜 blueprint

#333 Include src/systems when generating documentation
  CMakeLists.txt
Labels: 📜 blueprint

#297 Allow executing a blocking single Server run in both paused and unpaused states
  include/ignition/gazebo/Server.hh
  src/Server.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
Labels: 🏰 citadel

#335 Fix Log system tests to work with plugin names without ".so"
  src/Server.cc
  src/ServerPrivate.cc
Labels: 🏰 citadel

#315 Add support for specifying topics to record
  CMakeLists.txt
  include/ignition/gazebo/ServerConfig.hh
  src/ServerConfig.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/ign.cc
  src/ign.hh
  src/systems/log/LogRecord.cc
  test/integration/log_system.cc
Labels: 📜 blueprint

#314 Fixed some test - sdf::JointAxis is normalized and some other timers.
  src/EntityComponentManager.cc
  test/integration/diff_drive_system.cc
  test/integration/sensors_system.cc
Labels: enhancement, tests, 🔮 dome

#342 Resource spawner: accept relative paths
  include/ignition/gazebo/gui/GuiEvents.hh
  src/SimulationRunner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: 🏰 citadel

#346 Support spawning during log playback
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/Server.cc
  src/systems/log/LogPlayback.cc
Labels: 📜 blueprint

#348 EntityComponentManager::EachRemoved documentation fix
  include/ignition/gazebo/EntityComponentManager.hh
Labels: 🏰 citadel

#339 Make sure OpenGL core profile context is used by GzScene3D
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 📜 blueprint

#316 Add camera video recorder system
  examples/worlds/camera_video_record_dbl_pendulum.sdf
  include/ignition/gazebo/rendering/Events.hh
  src/systems/CMakeLists.txt
  src/systems/camera_video_recorder/CMakeLists.txt
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/sensors/Sensors.cc
  test/integration/CMakeLists.txt
  test/integration/camera_video_record_system.cc
  test/worlds/camera_video_record.sdf
Labels: 🏰 citadel

#338 2 ➡️ 3
  CMakeLists.txt
  Changelog.md
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/ServerConfig.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/Server.cc
  src/ServerConfig.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/plugins/scene3d/Scene3D.cc
  src/ign.cc
  src/ign.hh
  src/ign_TEST.cc
  src/systems/log/LogPlayback.cc
  src/systems/log/LogRecord.cc
  test/integration/breadcrumbs.cc
  test/integration/log_system.cc
  test/integration/save_world.cc
  test/performance/each.cc
Labels: 🏰 citadel

#328 Support relative paths for PBR materials
  src/Conversions.cc
Labels: 📜 blueprint

#303 Add file extension automatically for record plugin
  src/gui/plugins/video_recorder/VideoRecorder.cc
Labels: 📜 blueprint

#134 Wheel slip system
  examples/worlds/trisphere_cycle_wheel_slip.sdf
  include/ignition/gazebo/components/SlipComplianceCmd.hh
  src/systems/CMakeLists.txt
  src/systems/physics/Physics.cc
  src/systems/wheel_slip/CMakeLists.txt
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wheel_slip/WheelSlip.hh
  test/integration/CMakeLists.txt
  test/integration/wheel_slip.cc
  test/worlds/tire_drum.sdf
  test/worlds/triball_drift.sdf
  test/worlds/trisphere_cycle_wheel_slip.sdf
Labels: enhancement, needs upstream release, 📜 blueprint

#355 Suggestions to scrubber UI (#299)
  src/gui/Gui.cc
  src/gui/playback_gui.config
  src/gui/plugins/playback_scrubber/PlaybackScrubber.qml
  tutorials/gui_config.md
Labels: GUI, 📜 blueprint

#349 Add more model APIs
  include/ignition/gazebo/Model.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/components/AngularVelocityCmd.hh
  include/ignition/gazebo/components/LinearVelocityCmd.hh
  src/Model.cc
  src/Util.cc
  src/Util_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/String.qml
  src/systems/physics/Physics.cc
  test/integration/model.cc
  tutorials.md.in
  tutorials/migration_model_api.md
Labels: migration, 🏰 citadel

#357 Fix diff_drive_skid test
  CMakeLists.txt
  examples/worlds/diff_drive_skid.sdf
  test/worlds/diff_drive_skid.sdf
Labels: physics

#351 Enhancing log playback performance
  src/systems/log/LogPlayback.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
Labels: 📜 blueprint

#358 2.25.0
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#299 Playback Scrubber
  include/ignition/gazebo/components/LogPlaybackStatistics.hh
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/playback_gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/playback_scrubber/CMakeLists.txt
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.hh
  src/gui/plugins/playback_scrubber/PlaybackScrubber.qml
  src/gui/plugins/playback_scrubber/PlaybackScrubber.qrc
  src/systems/log/LogPlayback.cc
  src/systems/log/LogRecord.cc
  test/integration/log_system.cc
  tutorials/gui_config.md
Labels: 📜 blueprint

#331 Add Render Engine Cmd Line
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/components/RenderEngineGuiPlugin.hh
  include/ignition/gazebo/components/RenderEngineServerPlugin.hh
  src/LevelManager.cc
  src/ServerConfig.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/plugins/scene3d/Scene3D.cc
  src/ign.cc
  src/ign.hh
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
Labels: 🏰 citadel

#352 Add support for moving the GUI camera to a pose
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: enhancement, rendering, 🏰 citadel

#363 Fix Qt5 warnings for using anchors
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Vector3d.qml
Labels: beta, bug, 🔮 dome

#270 Plotting Components Plugin
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Vector3d.qml
  src/gui/plugins/component_inspector/plottable_icon.svg
  src/gui/plugins/plotting/CMakeLists.txt
  src/gui/plugins/plotting/Plotting.cc
  src/gui/plugins/plotting/Plotting.hh
  src/gui/plugins/plotting/Plotting.qml
  src/gui/plugins/plotting/Plotting.qrc
Labels: GUI, beta, enhancement, 🔮 dome

#301 Visualize Lidar Plugin for ign-gazebo
  examples/worlds/visualize_lidar.sdf
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/visualize_lidar/CMakeLists.txt
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.hh
  src/gui/plugins/visualize_lidar/VisualizeLidar.qml
  src/gui/plugins/visualize_lidar/VisualizeLidar.qrc
Labels: beta, enhancement, 🔮 dome

#365 Fix gui sendEvent memory leaks
  src/Conversions.cc
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
Labels: 🏰 citadel

#372 Decrease time step for quadcopter world
  examples/worlds/quadcopter.sdf
Labels: 🏰 citadel

#380 Add tutorial tweaks
  README.md
  tutorials/battery.md
  tutorials/detachable_joints.md
  tutorials/distributed_simulation.md
  tutorials/erb_template.md
  tutorials/levels.md
  tutorials/log.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/migration_plugins.md
  tutorials/point_cloud_to_mesh.md
  tutorials/resources.md
  tutorials/terminology.md
  tutorials/triggered_publisher.md
Labels: documentation, 🔮 dome

#383 Update dimensions of the grid config
  src/gui/plugins/grid_config/GridConfig.qml
Labels: 🏰 citadel

#384 Remove sidebar and put world control in bottom left
  examples/worlds/joint_controller.sdf
  examples/worlds/joint_position_controller.sdf
Labels: 🏰 citadel

#381 Fix top-left toolbar layout so magnet shows
  src/gui/gui.config
Labels: GUI, bug, 🏰 citadel

#377 Add instructions to bitmask world
  examples/worlds/shapes_bitmask.sdf
Labels: 🏰 citadel

#386 Update log tutorials
  examples/worlds/log_playback.sdf
  examples/worlds/log_record_dbl_pendulum.sdf
  examples/worlds/log_record_keyboard.sdf
  examples/worlds/log_record_resources.sdf
  examples/worlds/log_record_shapes.sdf
Labels: 🔮 dome

#387 Update window placement for sensors demo
  examples/worlds/sensors_demo.sdf
Labels: 🔮 dome

#374 Fix adding performers to entity tree
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/entity_tree/EntityTree.hh
Labels: GUI, bug, 🏰 citadel

#390 Clarified performer example in Levels tutorial
  tutorials/levels.md
Labels: 🔮 dome

#391 Fix error message on Visualize Lidar plugin
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: 🔮 dome
