Repository gazebosim/gz-sim, pull requests merged in 2020-08, with the labels that each got.

#172 Resource env var, with transport interface
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  src/SdfGenerator_TEST.cc
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/Util.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/Gui_TEST.cc
  src/gui/PathManager.cc
  src/gui/PathManager.hh
  src/main.cc
  src/systems/physics/Physics.cc
  test/worlds/models/scheme_resource_uri/meshes/box.dae
  test/worlds/models/scheme_resource_uri/model.config
  test/worlds/models/scheme_resource_uri/model.sdf
  test/worlds/resource_paths.sdf
  tutorials/resources.md
Labels: 📜 blueprint

#262 Dome version update
  .github/ci-bionic/dependencies.yaml
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  CMakeLists.txt
  README.md
  bitbucket-pipelines.yml
  docker/Dockerfile.nightly
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🔮 dome

#271 Save http URIs (fix tests)
  src/SdfGenerator.cc
  src/SdfGenerator_TEST.cc
Labels: tests, 📜 blueprint

#173 Insert Local Models
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/resource_spawner/CMakeLists.txt
  src/gui/plugins/resource_spawner/NoThumbnail.png
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/plugins/resource_spawner/folder_closed.png
  src/gui/plugins/resource_spawner/folder_open.png
Labels: close the gap, 📜 blueprint

#269 Modernize actions CI
  .github/ci-bionic/after_make.sh
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 📜 blueprint

#266 Sensor topics available through components and GUI
  include/ignition/gazebo/components/Sensor.hh
  include/ignition/gazebo/components/Serialization.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/imu/Imu.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  test/integration/air_pressure_system.cc
  test/integration/altimeter_system.cc
  test/integration/imu_system.cc
  test/integration/logical_camera_system.cc
  test/integration/magnetometer_system.cc
Labels: 📜 blueprint

#275 Touch plugin enabled
  src/systems/touch_plugin/TouchPlugin.cc
Labels: 🏰 citadel

#282 UI proposals to #263
  src/gui/plugins/resource_spawner/DownloadToUse.png
  src/gui/plugins/resource_spawner/NoThumbnail.png
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
Labels: GUI, 📜 blueprint

#283 Add simulation world with large number of entities
  examples/worlds/actors_population.sdf
  examples/worlds/actors_population.sdf.erb
  examples/worlds/shapes_population.sdf
  examples/worlds/shapes_population.sdf.erb
Labels: 🏰 citadel

#292 Fix non-specified material error
  src/rendering/MarkerManager.cc
Labels: 🏰 citadel

#290 Add checks for marker parent
  src/rendering/MarkerManager.cc
Labels: bug, rendering, 🏰 citadel

#254 igniton gazebo fullscreen
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: GUI, 🏰 citadel

#274 Add Fuel World Support
  src/ServerConfig.cc
  src/Server_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/ign.cc
  src/ign.hh
  src/ign_TEST.cc
  test/worlds/fuel.ignitionrobotics.org/OpenRobotics/worlds/Test%20world/2/test.sdf
  test/worlds/fuel.ignitionrobotics.org/OpenRobotics/worlds/Test%20world/2/thumbnails/1.png
Labels: 📜 blueprint

#263 Insert Fuel Models
  src/gui/plugins/resource_spawner/CloudDownload.png
  src/gui/plugins/resource_spawner/DownloadToUse.png
  src/gui/plugins/resource_spawner/NoThumbnail.png
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
Labels: 📜 blueprint

#209 Disable rendering tests on macOS that are known to fail
  CMakeLists.txt
  test/integration/depth_camera.cc
  test/integration/gpu_lidar.cc
  test/integration/rgbd_camera.cc
  test/integration/sensors_system.cc
Labels: macOS, rendering, tests, 📜 blueprint

#295 Fix tests on Blueprint
  include/ignition/gazebo/Server.hh
  src/Server.cc
  src/ServerConfig.cc
  src/Server_TEST.cc
Labels: bug, tests, 📜 blueprint

#252 Buoyancy
  Changelog.md
  examples/worlds/buoyancy.sdf
  include/ignition/gazebo/components/CenterOfVolume.hh
  include/ignition/gazebo/components/Volume.hh
  src/systems/CMakeLists.txt
  src/systems/buoyancy/Buoyancy.cc
  src/systems/buoyancy/Buoyancy.hh
  src/systems/buoyancy/CMakeLists.txt
  test/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/buoyancy.cc
  test/worlds/CMakeLists.txt
  test/worlds/buoyancy.sdf.in
Labels: 🏰 citadel

#296 2 ➡️ 3 (part 1)
  .github/ci-bionic/after_make.sh
  Changelog.md
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  src/SdfGenerator.cc
  src/SdfGenerator_TEST.cc
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/Util.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/Gui_TEST.cc
  src/gui/PathManager.cc
  src/gui/PathManager.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/performer_detector/PerformerDetector.cc
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.cc
  test/integration/performer_detector.cc
  test/worlds/models/scheme_resource_uri/meshes/box.dae
  test/worlds/models/scheme_resource_uri/model.config
  test/worlds/models/scheme_resource_uri/model.sdf
  test/worlds/performer_detector.sdf
  test/worlds/resource_paths.sdf
  tutorials/resources.md
Labels: 🏰 citadel

#291 Qt auto scale factor for HiDPI displays
  src/gui/Gui.cc
Labels: 🔮 dome

#308 Publish remaining breadcrumb deployments.
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
  test/integration/breadcrumbs.cc
Labels: 📜 blueprint

#302 Add marker array service
  examples/standalone/marker/marker.cc
  src/rendering/MarkerManager.cc
Labels: rendering, 🏰 citadel

#272 Sync components removal
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/SimulationRunner.cc
  src/gui/GuiRunner.cc
Labels: 🔮 dome

#298 ERB template tutorial
  tutorials/erb_template.md
Labels: documentation, 🏰 citadel
