Repository gazebosim/gz-sim, pull requests merged in 2020-06, with the labels that each got.

#155 Allow renaming breadcrumb models if there is a name conflict
  Changelog.md
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
  test/integration/breadcrumbs.cc
  test/worlds/breadcrumbs.sdf
Labels: enhancement, 📜 blueprint

#166 Use updated model names for spawned models when generating SDFormat
  Changelog.md
  src/SdfGenerator.cc
  test/integration/save_world.cc
Labels: 📜 blueprint

#165 Support joint force commands with the Battery plugin
  Changelog.md
  examples/worlds/lift_drag_battery.sdf
  src/systems/battery_plugin/LinearBatteryPlugin.cc
Labels: 📜 blueprint

#170 2.19.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#171 Merge 3 to 4
  CMakeLists.txt
  Changelog.md
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/shapes/CMakeLists.txt
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/shapes/Shapes.hh
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/box.png
  src/gui/plugins/shapes/cylinder.png
  src/gui/plugins/shapes/sphere.png
  src/rendering/SceneManager.cc
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/physics/Physics.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
Labels: 🔮 dome

#179 Add odom_topic to diff drive
  Changelog.md
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  test/integration/diff_drive_system.cc
  test/worlds/diff_drive_custom_topics.sdf
Labels: 📜 blueprint

#157 More actor components and follow plugin
  examples/worlds/follow_actor.sdf
  include/ignition/gazebo/components/Actor.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/follow_actor/CMakeLists.txt
  src/systems/follow_actor/FollowActor.cc
  src/systems/follow_actor/FollowActor.hh
  test/integration/CMakeLists.txt
  test/integration/follow_actor_system.cc
  test/worlds/follow_actor.sdf
Labels: 🔮 dome

#181 Move test Relay to its own file
  test/helpers/Relay.hh
  test/integration/altimeter_system.cc
  test/integration/apply_joint_force_system.cc
  test/integration/breadcrumbs.cc
  test/integration/detachable_joint.cc
  test/integration/diff_drive_system.cc
  test/integration/each_new_removed.cc
  test/integration/imu_system.cc
  test/integration/joint_controller_system.cc
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/lift_drag_system.cc
  test/integration/log_system.cc
  test/integration/magnetometer_system.cc
  test/integration/multicopter.cc
  test/integration/physics_system.cc
  test/integration/pose_publisher_system.cc
  test/integration/user_commands.cc
Labels: 📜 blueprint

#183 Battery updates
  examples/worlds/linear_battery_demo.sdf
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
Labels: 📜 blueprint

#161 diff_drive system with speed limiter
  src/systems/diff_drive/CMakeLists.txt
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  src/systems/diff_drive/SpeedLimiter.cc
  src/systems/diff_drive/SpeedLimiter.hh
  test/integration/diff_drive_system.cc
  test/worlds/diff_drive.sdf
  test/worlds/diff_drive_custom_topics.sdf
Labels: 📜 blueprint

#198 Prepare for 2.20.0 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#153 Fix for issue 43
  include/ignition/gazebo/components/Actor.hh
  src/SimulationRunner.hh
  src/gui/plugins/video_recorder/VideoRecorder.qml
  test/integration/follow_actor_system.cc
  test/integration/physics_system.cc
Labels: enhancement, 🔮 dome

#205 Battery updates - Part 2
  examples/worlds/lift_drag_battery.sdf
  examples/worlds/linear_battery_demo.sdf
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
Labels: 📜 blueprint

#160 Use collision bitmask flag for meshes
  CMakeLists.txt
  Changelog.md
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🔮 dome

#208 Capitalize openrobotics
  examples/worlds/breadcrumbs.sdf
  examples/worlds/camera_sensor.sdf
  examples/worlds/depth_camera_sensor.sdf
  examples/worlds/fuel_textured_mesh.sdf
  examples/worlds/gpu_lidar_sensor.sdf
  examples/worlds/log_record_resources.sdf
  examples/worlds/multicopter_velocity_control.sdf
  examples/worlds/quadcopter.sdf
  examples/worlds/sensors_demo.sdf
  examples/worlds/tunnel.sdf
  src/SdfGenerator_TEST.cc
  test/integration/log_system.cc
  test/integration/save_world.cc
  test/integration/sdf_include.cc
  test/worlds/breadcrumbs.sdf
  test/worlds/include.sdf
  test/worlds/log_record_resources.sdf
  test/worlds/save_world.sdf
Labels: 📜 blueprint

#212 Properly add new models into the scenegraph
  CMakeLists.txt
  Changelog.md
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
Labels: 📜 blueprint

#218 Fixed left menu events
  src/gui/resources/GazeboDrawer.qml
Labels: bug, 🔮 dome

#219 models_link
  examples/worlds/fuel.sdf
Labels: bug, 📜 blueprint

#223 Backport collide bitmask changes
  CMakeLists.txt
  Changelog.md
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🏰 citadel
