Repository gazebosim/gz-sim, pull requests merged in 2020-12, with the labels that each got.

#467 Clarify how time is represented in each phase of a System step
  include/ignition/gazebo/System.hh
  tutorials/create_system_plugins.md
Labels: 📜 blueprint

#472 Link link tutorial 🔗
  tutorials.md.in
Labels: documentation, 🏰 citadel

#469 3 ➡️ 4
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/network/PeerTracker_TEST.cc
  test/integration/log_system.cc
  test/integration/physics_system.cc
Labels: 🔮 dome

#461 Switch to async state service request
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/GuiRunner.cc
  src/systems/physics/Physics.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🔮 dome

#470 Use a std::promise/std::future to avoid busy waiting the step ack messages in NetworkManagerPrimary
  src/network/NetworkManagerPrimary.cc
  src/network/NetworkManagerPrimary.hh
Labels: 🔮 dome

#480 Fix tests that use Fuel paths with uppercase letters
  CMakeLists.txt
  test/integration/log_system.cc
  test/integration/sdf_include.cc
Labels: tests, 🏰 citadel

#229 Optical Tactile Sensor Plugin
  examples/worlds/optical_tactile_sensor_plugin.sdf
  src/systems/CMakeLists.txt
  src/systems/optical_tactile_plugin/CMakeLists.txt
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/optical_tactile_plugin/Visualization.cc
  src/systems/optical_tactile_plugin/Visualization.hh
Labels: 🔮 dome

#485 4.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#466 Update key event handling
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/transform_control/TransformControl.hh
  src/gui/plugins/transform_control/TransformControl.qml
Labels: enhancement, 🏰 citadel

#490 Fix slot in Plotting plugin
  src/gui/plugins/plotting/Plotting.cc
Labels: bug, 🔮 dome

#456 Tape Measure Plugin
  CMakeLists.txt
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/tape_measure/CMakeLists.txt
  src/gui/plugins/tape_measure/TapeMeasure.cc
  src/gui/plugins/tape_measure/TapeMeasure.hh
  src/gui/plugins/tape_measure/TapeMeasure.qml
  src/gui/plugins/tape_measure/TapeMeasure.qrc
  src/gui/plugins/tape_measure/tape_measure.png
  src/gui/plugins/tape_measure/trashcan.png
Labels: GUI, enhancement, 🏰 citadel

#491 Satisfy make codecheck
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/systems/buoyancy/Buoyancy.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/velocity_control/VelocityControl.cc
Labels: 🏰 citadel

#493 Move deselect and preview termination to render thread
  src/gui/plugins/scene3d/Scene3D.cc
Labels: GUI, 🏰 citadel

#499 Fix codecheck
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/gui/plugins/entity_tree/EntityTree.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/tape_measure/TapeMeasure.cc
  src/ign.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🏰 citadel

#445 Add support for sky
  examples/worlds/sky.sdf
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
Labels: needs upstream release, 🏢 edifice

#401 Logical audio sensor plugin
  examples/worlds/logical_audio_sensor_plugin.sdf
  include/ignition/gazebo/components/LogicalAudio.hh
  src/systems/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/LogicalAudio.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudio.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudio_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/worlds/logical_audio_sensor_plugin.sdf
  test/worlds/logical_audio_sensor_plugin_services.sdf
  tutorials.md.in
  tutorials/files/logical_audio_sensor_plugin.png
  tutorials/logical_audio_sensor.md
Labels: 🏰 citadel

#502 Codecheck - initialize primitive in LogicalAudio component
  include/ignition/gazebo/components/LogicalAudio.hh
Labels: 🏰 citadel

#361 add frame_id and child_frame_id attribute support for DiffDrive
  src/systems/diff_drive/DiffDrive.cc
  test/integration/diff_drive_system.cc
  test/worlds/diff_drive_custom_frame_id.sdf
Labels: 🏰 citadel

#505 3 to 4
  CMakeLists.txt
  examples/worlds/logical_audio_sensor_plugin.sdf
  include/ignition/gazebo/components/LogicalAudio.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  src/SimulationRunner.hh
  src/gui/GuiRunner.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/entity_tree/EntityTree.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/tape_measure/CMakeLists.txt
  src/gui/plugins/tape_measure/TapeMeasure.cc
  src/gui/plugins/tape_measure/TapeMeasure.hh
  src/gui/plugins/tape_measure/TapeMeasure.qml
  src/gui/plugins/tape_measure/TapeMeasure.qrc
  src/gui/plugins/tape_measure/tape_measure.png
  src/gui/plugins/tape_measure/trashcan.png
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/transform_control/TransformControl.hh
  src/gui/plugins/transform_control/TransformControl.qml
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/ign.cc
  src/systems/CMakeLists.txt
  src/systems/buoyancy/Buoyancy.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/follow_actor/FollowActor.cc
  src/systems/logical_audio_sensor_plugin/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/LogicalAudio.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudio.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudio_TEST.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/physics/Physics.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  src/systems/velocity_control/VelocityControl.cc
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/log_system.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/physics_system.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sdf_include.cc
  test/worlds/logical_audio_sensor_plugin.sdf
  test/worlds/logical_audio_sensor_plugin_services.sdf
  tutorials.md.in
  tutorials/files/logical_audio_sensor_plugin.png
  tutorials/logical_audio_sensor.md
Labels: 🔮 dome

#446 Fix shadow artifacts by disabling double sided rendering
  Migration.md
  examples/worlds/tunnel.sdf
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/rendering/SceneManager.cc
Labels: 🔮 dome

#414 Add ability to record video based on sim time
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
Labels: 🏰 citadel

#508 Suggestions to #281
  include/ignition/gazebo/config.hh.in
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/systems/log/LogRecord.cc
  tutorials/server_config.md
Labels: 🏰 citadel

#419 Add lockstep mode to video recording
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  tutorials.md.in
  tutorials/files/video_recorder/video_recorder.gif
  tutorials/files/video_recorder/video_recorder.png
  tutorials/video_recorder.md
Labels: 🏰 citadel

#512 2 ➡️ 3
  include/ignition/gazebo/System.hh
  tutorials/create_system_plugins.md
Labels: 🏰 citadel

#517 ⬆️ 2.26.0 🏁
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#492 Kinetic energy monitor plugin
  examples/worlds/kinetic_energy_monitor.sdf
  src/systems/CMakeLists.txt
  src/systems/kinetic_energy_monitor/CMakeLists.txt
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.hh
  test/integration/CMakeLists.txt
  test/integration/kinetic_energy_monitor_system.cc
  test/worlds/altimeter.sdf
Labels: 🔮 dome

#458 Disable right click menu when using measuring tool
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/tape_measure/TapeMeasure.cc
Labels: GUI, enhancement, 🏰 citadel

#524 ⬆️ 3.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
