Repository gazebosim/gz-sim, pull requests merged in 2021-08, with the labels that each got.

#951 5 ➡️ 6
  examples/worlds/plot_3d.sdf
  include/ignition/gazebo/Link.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  src/Link.cc
  src/Server.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/Util.cc
  src/Util_TEST.cc
  src/cmd/ModelCommandAPI.hh
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/GuiRunner.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/plot_3d/CMakeLists.txt
  src/gui/plugins/plot_3d/Plot3D.cc
  src/gui/plugins/plot_3d/Plot3D.hh
  src/gui/plugins/plot_3d/Plot3D.qml
  src/gui/plugins/plot_3d/Plot3D.qrc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/wind_effects/WindEffects.cc
  test/helpers/Relay.hh
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/link.cc
  test/plugins/MockSystem.cc
  test/plugins/MockSystem.hh
Labels: 🏯 fortress

#953 Fix logic to disable server default plugins loading
  src/ServerConfig.cc
Labels: 🏰 citadel

#799 Scale mode - part1
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/transform_control/TransformControl.hh
  src/gui/plugins/transform_control/TransformControl.qml
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: 🔮 dome

#926 Expose a test fixture helper class
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/standalone/gtest_setup/README.md
  examples/standalone/gtest_setup/command.sdf
  examples/standalone/gtest_setup/command_TEST.cc
  examples/standalone/gtest_setup/gravity.sdf
  examples/standalone/gtest_setup/gravity_TEST.cc
  include/ignition/gazebo/TestFixture.hh
  include/ignition/gazebo/Util.hh
  src/CMakeLists.txt
  src/TestFixture.cc
  src/TestFixture_TEST.cc
  test/helpers/Relay.hh
  test/integration/examples_build.cc
  test/test_config.hh.in
  tutorials.md.in
  tutorials/test_fixture.md
Labels: 🏰 citadel

#957 Set protobuf_MODULE_COMPATIBLE before any find_package call
  CMakeLists.txt
Labels: 🏰 citadel

#943 Simplifications to storage
  include/ignition/gazebo/EntityComponentStorage.hh
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/BaseView_TEST.cc
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentStorage.cc
  src/EntityComponentStorage_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/view.cc
Labels: 🏯 fortress

#881 Scale mode - Part2
  include/ignition/gazebo/components/Model.hh
  test/integration/components.cc
Labels: 🔮 dome

#786 Complaint if Joint doesn't exists before adding joint controller
  src/systems/joint_controller/JointController.cc
  test/integration/joint_controller_system.cc
  test/worlds/joint_controller_invalid.sdf
Labels: 🏢 edifice

#955 Allow referencing links in nested models in LiftDrag
  examples/worlds/lift_drag_nested.sdf
  src/systems/lift_drag/LiftDrag.cc
  src/systems/lift_drag/LiftDrag.hh
  test/integration/lift_drag_system.cc
  test/worlds/lift_drag_nested_model.sdf
  test/worlds/models/lift_drag_wing/model.config
  test/worlds/models/lift_drag_wing/model.sdf
Labels: 🏢 edifice

#939 Drag and drop mesh into scene
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: 🏰 citadel

#813 New scene manager GUI plugin that works with ign-gui's MinimalScene
  examples/worlds/minimal_scene.sdf
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene_manager/CMakeLists.txt
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/plugins/scene_manager/GzSceneManager.hh
  src/gui/plugins/scene_manager/GzSceneManager.qml
  src/gui/plugins/scene_manager/GzSceneManager.qrc
  src/rendering/RenderUtil.cc
Labels: GUI, rendering, 🏯 fortress

#965 Be more specific when looking for physics plugins
  src/systems/physics/Physics.cc
Labels: 🏰 citadel

#839 Removed pose topic from log system
  Migration.md
  src/systems/log/LogPlayback.cc
  src/systems/log/LogRecord.cc
  test/integration/log_system.cc
  test/media/rolling_shapes_log/state.tlog
Labels: 🏯 fortress

#967 🎈 3.9.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#958 Fix crash in the follow_actor example
  src/rendering/RenderUtil.cc
  test/integration/follow_actor_system.cc
  test/worlds/follow_actor.sdf
Labels: 🔮 dome

#968 4 ➡️ 5
  CMakeLists.txt
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/standalone/gtest_setup/README.md
  examples/standalone/gtest_setup/command.sdf
  examples/standalone/gtest_setup/command_TEST.cc
  examples/standalone/gtest_setup/gravity.sdf
  examples/standalone/gtest_setup/gravity_TEST.cc
  include/ignition/gazebo/TestFixture.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  src/CMakeLists.txt
  src/ServerConfig.cc
  src/TestFixture.cc
  src/TestFixture_TEST.cc
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/physics/Physics.cc
  src/systems/velocity_control/VelocityControl.hh
  test/helpers/Relay.hh
  test/integration/examples_build.cc
  test/integration/follow_actor_system.cc
  test/test_config.hh.in
  test/worlds/follow_actor.sdf
  tutorials.md.in
  tutorials/rendering_plugins.md
  tutorials/test_fixture.md
Labels: 🏢 edifice

#972 Fix msg in entity_creation example
  examples/standalone/entity_creation/entity_creation.cc
Labels: 🔮 dome

#970 5 ➡️ 6
  CMakeLists.txt
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/standalone/gtest_setup/README.md
  examples/standalone/gtest_setup/command.sdf
  examples/standalone/gtest_setup/command_TEST.cc
  examples/standalone/gtest_setup/gravity.sdf
  examples/standalone/gtest_setup/gravity_TEST.cc
  examples/worlds/lift_drag_nested.sdf
  include/ignition/gazebo/TestFixture.hh
  src/CMakeLists.txt
  src/ServerConfig.cc
  src/TestFixture.cc
  src/TestFixture_TEST.cc
  src/gui/GuiRunner.hh
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_controller/JointController.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/lift_drag/LiftDrag.hh
  src/systems/physics/Physics.cc
  src/systems/velocity_control/VelocityControl.hh
  test/helpers/Relay.hh
  test/integration/examples_build.cc
  test/integration/follow_actor_system.cc
  test/integration/joint_controller_system.cc
  test/integration/lift_drag_system.cc
  test/test_config.hh.in
  test/worlds/follow_actor.sdf
  test/worlds/joint_controller_invalid.sdf
  test/worlds/lift_drag_nested_model.sdf
  test/worlds/models/lift_drag_wing/model.config
  test/worlds/models/lift_drag_wing/model.sdf
  tutorials.md.in
  tutorials/rendering_plugins.md
  tutorials/test_fixture.md
Labels: 🏯 fortress

#617 Upgrade ign-sensors and support custom sensors
  CMakeLists.txt
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/plugin/custom_sensor_system/OdometerSystem.cc
  examples/plugin/custom_sensor_system/OdometerSystem.hh
  examples/plugin/custom_sensor_system/README.md
  examples/plugin/custom_sensor_system/odometer.sdf
  include/ignition/gazebo/components/CustomSensor.hh
  src/SdfEntityCreator.cc
  src/rendering/CMakeLists.txt
  src/systems/sensors/CMakeLists.txt
  src/systems/sensors/Sensors.cc
  test/integration/examples_build.cc
Labels: enhancement, sensors, 🏯 fortress

#856 Use statically-typed views for better performance
  Migration.md
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/Types.hh
  include/ignition/gazebo/components/Factory.hh
  include/ignition/gazebo/detail/BaseView.hh
  include/ignition/gazebo/detail/ComponentStorageBase.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  include/ignition/gazebo/detail/View.hh
  src/BaseView.cc
  src/BaseView_TEST.cc
  src/CMakeLists.txt
  src/ComponentFactory_TEST.cc
  src/Component_TEST.cc
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ServerConfig.cc
  src/View.cc
  test/helpers/EnvTestFixture.hh
Labels: performance, 🏯 fortress

#854 Added transform control and select entities GUI plugins
  examples/worlds/minimal_scene.sdf
  include/ignition/gazebo/gui/GuiEvents.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/select_entities/CMakeLists.txt
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/select_entities/SelectEntities.hh
  src/gui/plugins/select_entities/SelectEntities.qml
  src/gui/plugins/select_entities/SelectEntities.qrc
  src/gui/plugins/transform_control/TransformControl.cc
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#974 Entity tree: prevent creation of repeated entity items
  src/gui/plugins/entity_tree/EntityTree.cc
Labels: GUI, 🏰 citadel

#851 Add ModelSDF serializer
  include/ignition/gazebo/components/Model.hh
  test/integration/components.cc
Labels: 🏯 fortress

#980 Fix `INTEGRATION_log_system` regression
  include/ignition/gazebo/components/Model.hh
Labels: 🏯 fortress

#984 Removed unused variable in Shapes plugin
  src/gui/plugins/shapes/Shapes.cc
Labels: 🏰 citadel

#986 Deprecate particle emitter, and use scatter ratio in new particle mes…
  Migration.md
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/systems/particle_emitter/ParticleEmitter.hh
  test/integration/particle_emitter2.cc
Labels: 🏯 fortress

#976 🎈 3.9.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#991 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel

#994 👩‍🌾 Make thermal sensor test more robust
  src/rendering/RenderUtil.cc
  test/integration/thermal_sensor_system.cc
Labels: rendering, sensors, tests, 🏢 edifice

#982 Enable sensor metrics on example worlds
  CMakeLists.txt
  examples/worlds/logical_camera_sensor.sdf
  examples/worlds/sensors.sdf
  examples/worlds/sensors_demo.sdf
Labels: 🏰 citadel

#1002 Remove duplicate XML tag in pendulum_links example world
  examples/worlds/pendulum_links.sdf
Labels: 🏰 citadel
