Repository gazebosim/gz-sim, pull requests merged in 2021-02, with the labels that each got.

#530 Model creation tutorial using services
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/entity_creation/README.md
  examples/standalone/entity_creation/entity_creation.cc
  tutorials.md.in
  tutorials/entity_creation.md
Labels: documentation, 🔮 dome

#471 Add lightmap demo
  examples/worlds/lightmap.sdf
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/rendering/SceneManager.cc
Labels: 🏢 edifice

#600 Fix topLevelModel method
  include/ignition/gazebo/Util.hh
  src/Util.cc
  src/Util_TEST.cc
Labels: bug, 🔮 dome

#599 Use double sided field in material msg
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: 🏢 edifice

#498 add heat signature option to thermal system
  examples/worlds/thermal_camera.sdf
  include/ignition/gazebo/components/TemperatureRange.hh
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
  src/systems/thermal/Thermal.cc
  test/integration/components.cc
  test/integration/thermal_system.cc
  test/worlds/thermal.sdf
Labels: 🔮 dome

#591 Depend on ignition-utils1
  CMakeLists.txt
Labels: 🏢 edifice

#536 Add service and GUI to configure physics parameters (step size and real time factor)
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/components/Physics.hh
  include/ignition/gazebo/components/PhysicsCmd.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Physics.qml
  src/gui/plugins/plotting/Plotting.cc
  src/gui/plugins/plotting/Plotting.hh
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: GUI, close the gap, enhancement, physics, 🔮 dome

#598 Also use Ignition GUI render event
  src/gui/plugins/scene3d/Scene3D.cc
Labels: GUI, rendering, 🏰 citadel

#478 Added run to time feature
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
Labels: 🏢 edifice

#605 4.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#607 Fix build with latest sdformat11 branch
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/Model.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/components.cc
  test/plugins/Null.cc
Labels: 🏢 edifice

#606 Add /image suffix to thermal camera topic name
  Migration.md
  src/rendering/RenderUtil.cc
Labels: 🏢 edifice

#613 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#616 Fix Windows build, again
  src/systems/log/LogRecord.cc
  src/systems/physics/Physics.cc
  test/plugins/Null.cc
Labels: Windows, bug, 🏢 edifice

#495 Fix seg fault in `SetRemovedComponentsMsgs` when TransformControl tool is used
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
Labels: 🔮 dome

#487 Heightmap (rendering only)
  examples/worlds/heightmap.sdf
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/rendering/SceneManager.cc
Labels: rendering, 🏢 edifice

#584 Make topics configurable for joint controllers
  examples/worlds/joint_position_controller.sdf
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
Labels: enhancement, 🏰 citadel

#595 Deprecate some gazebo::gui events in favor of ign-gui events
  Migration.md
  include/ignition/gazebo/gui/GuiEvents.hh
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/resource_spawner/CMakeLists.txt
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/CMakeLists.txt
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/CMakeLists.txt
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/CMakeLists.txt
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: GUI, 🏢 edifice

#567 Prepare GuiRunner to be made private
  include/ignition/gazebo/gui/GuiRunner.hh
  src/cmd/ign.cc
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
Labels: GUI, 🏢 edifice

#609 Add AboutDialogHandler
  src/gui/AboutDialogHandler.cc
  src/gui/AboutDialogHandler.hh
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/resources/GazeboDrawer.qml
Labels: GUI, close the gap, 🏰 citadel

#614 Add thermal sensor system for configuring thermal camera properties
  examples/worlds/thermal_camera.sdf
  include/ignition/gazebo/components/Temperature.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  src/systems/thermal/CMakeLists.txt
  src/systems/thermal/ThermalSensor.cc
  src/systems/thermal/ThermalSensor.hh
  test/integration/CMakeLists.txt
  test/integration/thermal_sensor_system.cc
  test/integration/thermal_system.cc
  test/worlds/thermal.sdf
  test/worlds/thermal_invalid.sdf
Labels: enhancement, 🔮 dome

#623 3 to 4
  examples/worlds/joint_position_controller.sdf
  src/gui/AboutDialogHandler.cc
  src/gui/AboutDialogHandler.hh
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/resources/GazeboDrawer.qml
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
Labels: 🔮 dome

#625 4.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#473 Add JointTrajectoryController system plugin
  CMakeLists.txt
  examples/worlds/joint_trajectory_controller.sdf
  src/systems/CMakeLists.txt
  src/systems/joint_trajectory_controller/CMakeLists.txt
  src/systems/joint_trajectory_controller/JointTrajectoryController.cc
  src/systems/joint_trajectory_controller/JointTrajectoryController.hh
  test/integration/CMakeLists.txt
  test/integration/joint_trajectory_controller_system.cc
  test/worlds/joint_trajectory_controller.sdf
Labels: 🔮 dome

#574 Fix pose of plane visual with non-default normal vector
  src/rendering/SceneManager.cc
Labels: rendering, 🏰 citadel

#596 Examples and tutorial on using rendering API from plugins
  examples/plugin/command_actor/README.md
  examples/plugin/custom_component/README.md
  examples/plugin/gui_system_plugin/README.md
  examples/plugin/rendering_plugins/CMakeLists.txt
  examples/plugin/rendering_plugins/README.md
  examples/plugin/rendering_plugins/RenderingGuiPlugin.cc
  examples/plugin/rendering_plugins/RenderingGuiPlugin.hh
  examples/plugin/rendering_plugins/RenderingGuiPlugin.qml
  examples/plugin/rendering_plugins/RenderingGuiPlugin.qrc
  examples/plugin/rendering_plugins/RenderingServerPlugin.cc
  examples/plugin/rendering_plugins/RenderingServerPlugin.hh
  examples/plugin/rendering_plugins/rendering_plugins.sdf
  examples/standalone/joy_to_twist/README.md
  examples/standalone/joystick/README.md
  examples/standalone/keyboard/README.md
  tutorials.md.in
  tutorials/files/rendering_plugins.gif
  tutorials/rendering_plugins.md
Labels: GUI, documentation, rendering, 🏢 edifice

#612 Added light intensity
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SimulationRunner_TEST.cc
  src/rendering/SceneManager.cc
  test/integration/components.cc
Labels: 🏢 edifice

#603 Add laser_retro support
  examples/worlds/gpu_lidar_retro_values_sensor.sdf
  include/ignition/gazebo/components/LaserRetro.hh
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  test/worlds/shapes.sdf
Labels: close the gap, needs upstream release, 🏰 citadel

#632 Add SDF topic validity check
  src/systems/joint_controller/JointController.cc
Labels: 🔮 dome

#601 Fix EntityComponentManager race condition
  src/gui/GuiRunner.cc
Labels: bug, 🔮 dome

#627 Added link to HW-accelerated video recording
  tutorials/video_recorder.md
Labels: documentation, 🔮 dome

#631 Remove issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#615 Particle system - Part4
  examples/worlds/particle_emitter.sdf
  include/ignition/gazebo/components/ParticleEmitter.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/particle_emitter/CMakeLists.txt
  src/systems/particle_emitter/ParticleEmitter.cc
  src/systems/particle_emitter/ParticleEmitter.hh
  test/integration/components.cc
  test/integration/particle_emitter.cc
  test/worlds/particle_emitter.sdf
Labels: enhancement, rendering

#516 Particle system - Part 1
  CMakeLists.txt
  Changelog.md
  examples/worlds/particle_emitter.sdf
  include/ignition/gazebo/components/ParticleEmitter.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/CMakeLists.txt
  src/systems/particle_emitter/CMakeLists.txt
  src/systems/particle_emitter/ParticleEmitter.cc
  src/systems/particle_emitter/ParticleEmitter.hh
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/particle_emitter.cc
  test/worlds/particle_emitter.sdf
Labels: needs upstream release, rendering, 🔮 dome

#587 Plugin to spawn lights
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/components/LightType.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SdfEntityCreator.cc
  src/gui/gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/lights/CMakeLists.txt
  src/gui/plugins/lights/Lights.cc
  src/gui/plugins/lights/Lights.hh
  src/gui/plugins/lights/Lights.qml
  src/gui/plugins/lights/Lights.qrc
  src/gui/plugins/lights/directionallight.png
  src/gui/plugins/lights/pointlight.png
  src/gui/plugins/lights/spotlight.png
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: GUI, close the gap, 🏢 edifice

#639 Validity check for user defined topics in JointPositionController
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
Labels: 🔮 dome

#642 👩‍🌾 Improve velocity control test
  test/integration/velocity_control_system.cc
Labels: tests, 🏰 citadel

#577 Bump in edifice: ign-common4
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
  docker/Dockerfile.nightly
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  src/SdfGenerator_TEST.cc
  tutorials/erb_template.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/video_recorder.md
Labels: 🏢 edifice

#640 👩‍🌾 Relax flaky performance test
  test/performance/each.cc
Labels: tests, 🏰 citadel

#548 add TF/Pose_V pub in DiffDrive
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  test/integration/diff_drive_system.cc
  test/worlds/diff_drive_custom_tf_topic.sdf
Labels: 🏰 citadel

#643 Add msg to show the computed temperature range computed from temperature gradient
  src/systems/sensors/Sensors.cc
Labels: 🔮 dome

#629 Add a convenience function for getting possibly non-existing components.
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/EntityComponentManager_TEST.cc
Labels: 🔮 dome

#641 👩‍🌾 Fix flaky SceneBroadcaster test
  test/integration/scene_broadcaster_system.cc
Labels: tests, 🏰 citadel

#636 3 to 4 20210217
  examples/worlds/gpu_lidar_retro_values_sensor.sdf
  include/ignition/gazebo/components/LaserRetro.hh
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  test/worlds/shapes.sdf
Labels: needs upstream release, 🔮 dome

#648 👩‍🌾 3 ➡️ 4
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  test/integration/diff_drive_system.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/velocity_control_system.cc
  test/performance/each.cc
  test/worlds/diff_drive_custom_tf_topic.sdf
Labels: 🔮 dome

#650 👩‍🌾 Set LD_LIBRARY_PATH on Actions CI (fix user_commands test)
  .github/ci/after_make.sh
  CMakeLists.txt
Labels: tests, 🔮 dome

#653 Suggestion to #497
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/GuiRunner.cc
  src/systems/physics/Physics.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/scene_broadcaster/SceneBroadcaster.hh
Labels: 🏰 citadel

#497 Limit scene broadcast publications when paused
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/GuiRunner.cc
  src/systems/physics/Physics.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/scene_broadcaster/SceneBroadcaster.hh
Labels: performance, 🏰 citadel

#654 Deprecate TmpIface: it's leftover from prototyping
  include/ignition/gazebo/gui/TmpIface.hh
  src/cmd/ign.cc
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/resources/GazeboDrawer.qml
Labels: 🏢 edifice
