Repository gazebosim/gz-sim, pull requests merged in 2021-12, with the labels that each got.

#1196 Model Editor: Add Joints to model
  include/ignition/gazebo/SdfEntityCreator.hh
  include/ignition/gazebo/gui/GuiEvents.hh
  src/SdfEntityCreator.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ModelEditor.cc
  src/systems/physics/Physics.cc
Labels: GUI, editor

#1198 Allow user to modify joint type
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/JointType.cc
  src/gui/plugins/component_inspector/JointType.hh
  src/gui/plugins/component_inspector/JointType.qml
  src/gui/plugins/component_inspector/ModelEditor.cc
Labels: GUI, editor, 🏯 fortress

#1201 Update SdfGenerator to save link and sensor data to file
  CMakeLists.txt
  src/SdfGenerator.cc
  src/SdfGenerator.hh
  src/SdfGenerator_TEST.cc
  test/integration/save_world.cc
  test/worlds/joint_sensor.sdf
  test/worlds/non_rendering_sensors.sdf
  test/worlds/save_world.sdf
  test/worlds/sensor.sdf
Labels: 🏯 fortress

#1188 Add sensors to a link via the GUI
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/component_inspector/AirPressure.cc
  src/gui/plugins/component_inspector/Altimeter.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ExpandingTypeHeader.qml
  src/gui/plugins/component_inspector/Imu.cc
  src/gui/plugins/component_inspector/JointType.cc
  src/gui/plugins/component_inspector/Lidar.cc
  src/gui/plugins/component_inspector/Magnetometer.cc
  src/gui/plugins/component_inspector/ModelEditor.cc
  src/gui/plugins/entity_tree/EntityTree.qml
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/resources/gazebo.qrc
  src/gui/resources/images/chevron-down.svg
  src/gui/resources/images/chevron-right.svg
  src/gui/resources/images/plus-link.png
  src/gui/resources/images/plus-sensor.png
Labels: GUI, sensors, editor, 🏯 fortress

#1224 Fix visualize lidar
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: 🔮 dome

#1226 Added sensor plugin to be able to visualize camera in plane_propeller_demo.sdf
  examples/worlds/plane_propeller_demo.sdf
Labels: 🏯 fortress

#1234 Bumps in garden : ci_matching_branch/bump_garden_ign-gazebo7
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  docker/Dockerfile.nightly
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🌱 garden

#1238 Docker fixs
  docker/README.md
  docker/build.bash
Labels: 🏯 fortress

#1236 6 ➡️ 7 (main)
  CMakeLists.txt
  Changelog.md
  examples/worlds/plane_propeller_demo.sdf
  examples/worlds/sensors.sdf
  include/ignition/gazebo/gui/GuiEvents.hh
  src/SdfGenerator.cc
  src/SdfGenerator.hh
  src/SdfGenerator_TEST.cc
  src/gui/CMakeLists.txt
  src/gui/GuiEvents.cc
  src/gui/GuiEvents_TEST.cc
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/view_angle/ViewAngle.qml
  src/systems/buoyancy/Buoyancy.cc
  src/systems/force_torque/ForceTorque.cc
  test/integration/buoyancy.cc
  test/integration/force_torque_system.cc
  test/integration/save_world.cc
  test/worlds/force_torque.sdf
  test/worlds/joint_sensor.sdf
  test/worlds/non_rendering_sensors.sdf
  test/worlds/save_world.sdf
  test/worlds/sensor.sdf
Labels: 🌱 garden

#1239 Fix ViewAngle's size
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: bug, GUI, 🏯 fortress

#1235 Send state message when components are removed
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🏯 fortress

#1105 View entity frames from the GUI
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
Labels: GUI, close the gap, needs upstream release, 🏯 fortress

#1243 🎈 6.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1246 Add visibility to ModelEditorAddEntity to fix Windows
  include/ignition/gazebo/gui/GuiEvents.hh
Labels: 🏯 fortress

#1255 Support battery draining start via topics
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  test/integration/battery_plugin.cc
  test/integration/imu_system.cc
  test/worlds/battery.sdf
Labels: 🔮 dome

#1257 [backport] 👩‍🌾 Make depth camera tests more robust (#897)
  test/integration/depth_camera.cc
  test/integration/pose_publisher_system.cc
  test/integration/rgbd_camera.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🏰 citadel

#1261 🎈 4.14.0 🏁
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#1240 Implement /server_control::stop
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/gui/TmpIface.hh
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/gui/TmpIface.cc
Labels: 🏰 citadel

#1222 Light Commands via topic
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: 🏯 fortress

#1264 Bumps in garden: use ign-math7 and dependents
  .github/ci/packages.apt
  CMakeLists.txt
  docker/Dockerfile.nightly
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  include/ignition/gazebo/gui/GuiEvents.hh
  src/SdfGenerator_TEST.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/SceneManager.cc
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  src/systems/multicopter_control/Common.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/optical_tactile_plugin/Visualization.cc
  src/systems/track_controller/TrackController.cc
  test/integration/CMakeLists.txt
  test/integration/wheel_slip.cc
  tutorials/migrating_ardupilot_plugin.md
Labels: 🌱 garden
