Repository gazebosim/gz-sim, pull requests merged in 2021-07, with the labels that each got.

#897 👩‍🌾 Make depth camera tests more robust
  test/integration/depth_camera.cc
  test/integration/pose_publisher_system.cc
  test/integration/rgbd_camera.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/thermal_sensor_system.cc
Labels: tests, 🏢 edifice

#898 Fix documentation for the Sensor component
  include/ignition/gazebo/components/Sensor.hh
Labels: 🏰 citadel

#699 Hello world plugin added
  examples/plugin/hello_world/CMakeLists.txt
  examples/plugin/hello_world/HelloWorld.cc
  examples/plugin/hello_world/HelloWorld.hh
  examples/plugin/hello_world/README.md
  examples/plugin/hello_world/hello_world_plugin.sdf
Labels: 🔮 dome

#874 Fix textures not exporting after loading a world that uses obj models
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  test/integration/collada_world_exporter.cc
  test/worlds/models/building_L1/meshes/blue_linoleum.png
  test/worlds/models/building_L1/meshes/default.png
  test/worlds/models/building_L1/meshes/floor_1.mtl
  test/worlds/models/building_L1/meshes/floor_1.obj
  test/worlds/models/building_L1/meshes/model.material
  test/worlds/models/building_L1/meshes/wall_1.mtl
  test/worlds/models/building_L1/meshes/wall_1.obj
  test/worlds/models/building_L1/model.config
  test/worlds/models/building_L1/model.sdf
  test/worlds/office.sdf
Labels: 🏢 edifice

#861 Visualize inertia
  include/ignition/gazebo/rendering/RenderUtil.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: GUI, needs upstream release, 🏯 fortress

#903 Visualize center of mass
  include/ignition/gazebo/rendering/RenderUtil.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#734 Banana for Scale
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/banana_for_scale/BananaForScale.cc
  src/gui/plugins/banana_for_scale/BananaForScale.hh
  src/gui/plugins/banana_for_scale/BananaForScale.qml
  src/gui/plugins/banana_for_scale/BananaForScale.qrc
  src/gui/plugins/banana_for_scale/CMakeLists.txt
  src/gui/plugins/banana_for_scale/banana.png
Labels: 🏢 edifice

#905 Moved marker example to ign-gui
  Migration.md
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/marker/README.md
  examples/standalone/marker/marker.cc
Labels: 🏯 fortress

#895 Add blender sdf export tutorial
  examples/scripts/blender/sdf_exporter.py
  tutorials.md.in
  tutorials/blender_sdf_exporter.md
Labels: 🏢 edifice

#876 Physics system: update link poses if the canonical link pose has been updated
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/worlds/only_canonical_link_moves.sdf
Labels: 🔮 dome

#873 Proposal for #856: Deprecations instead of removals
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/Types.hh
  include/ignition/gazebo/components/Factory.hh
  include/ignition/gazebo/detail/ComponentStorageBase.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  test/integration/view.cc
Labels: 🏯 fortress

#916 3 to 4
  include/ignition/gazebo/Types.hh
  include/ignition/gazebo/components/Sensor.hh
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 🔮 dome

#904 Fix updating GUI plugin on load
  src/gui/GuiRunner.cc
Labels: needs upstream release, 🏰 citadel

#918 4 to 5
  examples/plugin/hello_world/CMakeLists.txt
  examples/plugin/hello_world/HelloWorld.cc
  examples/plugin/hello_world/HelloWorld.hh
  examples/plugin/hello_world/README.md
  examples/plugin/hello_world/hello_world_plugin.sdf
  include/ignition/gazebo/Model.hh
  include/ignition/gazebo/Types.hh
  include/ignition/gazebo/components/Sensor.hh
  src/Model.cc
  src/Model_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/physics/Physics.cc
  test/integration/diff_drive_system.cc
  test/integration/odometry_publisher.cc
  test/integration/optical_tactile_plugin.cc
  test/integration/physics_system.cc
  test/worlds/only_canonical_link_moves.sdf
Labels: 🏢 edifice

#915 Adds Mesh Tutorial
  tutorials.md.in
  tutorials/files/model_and_optimize_meshes/10_loop_cut.jpg
  tutorials/files/model_and_optimize_meshes/11_duplicate.jpg
  tutorials/files/model_and_optimize_meshes/12_other_modifiers.png
  tutorials/files/model_and_optimize_meshes/13_polygons.jpg
  tutorials/files/model_and_optimize_meshes/14_export_model.png
  tutorials/files/model_and_optimize_meshes/15_axis.png
  tutorials/files/model_and_optimize_meshes/16_check_scale.png
  tutorials/files/model_and_optimize_meshes/17_check_pivot_point_a.jpg
  tutorials/files/model_and_optimize_meshes/18_check_pivot_point_b.jpg
  tutorials/files/model_and_optimize_meshes/1_wheels.jpg
  tutorials/files/model_and_optimize_meshes/2_cylinder.jpg
  tutorials/files/model_and_optimize_meshes/3_transform_gizmos.png
  tutorials/files/model_and_optimize_meshes/4_move.png
  tutorials/files/model_and_optimize_meshes/5_rotate.jpg
  tutorials/files/model_and_optimize_meshes/7_scale.jpg
  tutorials/files/model_and_optimize_meshes/8_bevel.jpg
  tutorials/files/model_and_optimize_meshes/9_extrude.png
  tutorials/model_and_optimize_meshes.md
Labels: 🏰 citadel

#661 Heightmap physics (with DART) 🏔️
  CMakeLists.txt
  examples/worlds/heightmap.sdf
  src/rendering/RenderUtil.cc
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/media/heightmap_bowl.png
  test/worlds/heightmap.sdf
Labels: enhancement, physics, 🏢 edifice

#923 Fix blender sdf export script and remove .material file from collada light export test
  examples/scripts/blender/sdf_exporter.py
  test/worlds/models/building_L1/meshes/model.material
  test/worlds/models/building_L1/model.sdf
Labels: 🏢 edifice

#921 Make Gazebo aware of SetCameraPassCountPerGpuFlush
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/sensors/Sensors.cc
Labels: needs upstream release, 🏯 fortress

#927 don't create components for entities that don't exist
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/diff_drive/DiffDrive.cc
Labels: 🏰 citadel

#919 Support Bullet on Edifice
  src/systems/physics/Physics.cc
Labels: 🏢 edifice

#930 Add a way to perform startup checks using `TestFixture`.
  examples/standalone/gtest_setup/gravity_TEST.cc
  include/ignition/gazebo/TestFixture.hh
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/TestFixture.cc
Labels: 🏯 fortress

#893 CLI model info dump
  src/CMakeLists.txt
  src/ModelCommandAPI_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/cmd/cmdmodel.rb.in
  src/cmd/model.yaml.in
  test/worlds/static_diff_drive_vehicle.sdf
  tutorials.md.in
  tutorials/model_command.md
Labels: 🏰 citadel

#932 🎈 3.9.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#931 Fix tests that use multiple root level models or lights
  test/integration/user_commands.cc
  test/worlds/models/include_nested/model.sdf
Labels: 🏯 fortress

#933 3 to 4
  CMakeLists.txt
  Changelog.md
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ModelCommandAPI_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/cmd/cmdmodel.rb.in
  src/cmd/model.yaml.in
  src/gui/GuiRunner.cc
  src/systems/diff_drive/DiffDrive.cc
  test/integration/diff_drive_system.cc
  test/worlds/static_diff_drive_vehicle.sdf
  tutorials.md.in
  tutorials/files/model_and_optimize_meshes/10_loop_cut.jpg
  tutorials/files/model_and_optimize_meshes/11_duplicate.jpg
  tutorials/files/model_and_optimize_meshes/12_other_modifiers.png
  tutorials/files/model_and_optimize_meshes/13_polygons.jpg
  tutorials/files/model_and_optimize_meshes/14_export_model.png
  tutorials/files/model_and_optimize_meshes/15_axis.png
  tutorials/files/model_and_optimize_meshes/16_check_scale.png
  tutorials/files/model_and_optimize_meshes/17_check_pivot_point_a.jpg
  tutorials/files/model_and_optimize_meshes/18_check_pivot_point_b.jpg
  tutorials/files/model_and_optimize_meshes/1_wheels.jpg
  tutorials/files/model_and_optimize_meshes/2_cylinder.jpg
  tutorials/files/model_and_optimize_meshes/3_transform_gizmos.png
  tutorials/files/model_and_optimize_meshes/4_move.png
  tutorials/files/model_and_optimize_meshes/5_rotate.jpg
  tutorials/files/model_and_optimize_meshes/7_scale.jpg
  tutorials/files/model_and_optimize_meshes/8_bevel.jpg
  tutorials/files/model_and_optimize_meshes/9_extrude.png
  tutorials/model_and_optimize_meshes.md
  tutorials/model_command.md
  tutorials/particle_tutorial.md
Labels: needs upstream release, 🔮 dome

#937 Fix joint controller with empty joint velocity data
  src/systems/joint_controller/JointController.cc
Labels: 🔮 dome

#938 4 to 5
  CMakeLists.txt
  Changelog.md
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ModelCommandAPI_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/cmd/cmdmodel.rb.in
  src/cmd/model.yaml.in
  src/gui/GuiRunner.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_controller/JointController.cc
  test/integration/diff_drive_system.cc
  test/worlds/static_diff_drive_vehicle.sdf
  tutorials.md.in
  tutorials/files/model_and_optimize_meshes/10_loop_cut.jpg
  tutorials/files/model_and_optimize_meshes/11_duplicate.jpg
  tutorials/files/model_and_optimize_meshes/12_other_modifiers.png
  tutorials/files/model_and_optimize_meshes/13_polygons.jpg
  tutorials/files/model_and_optimize_meshes/14_export_model.png
  tutorials/files/model_and_optimize_meshes/15_axis.png
  tutorials/files/model_and_optimize_meshes/16_check_scale.png
  tutorials/files/model_and_optimize_meshes/17_check_pivot_point_a.jpg
  tutorials/files/model_and_optimize_meshes/18_check_pivot_point_b.jpg
  tutorials/files/model_and_optimize_meshes/1_wheels.jpg
  tutorials/files/model_and_optimize_meshes/2_cylinder.jpg
  tutorials/files/model_and_optimize_meshes/3_transform_gizmos.png
  tutorials/files/model_and_optimize_meshes/4_move.png
  tutorials/files/model_and_optimize_meshes/5_rotate.jpg
  tutorials/files/model_and_optimize_meshes/7_scale.jpg
  tutorials/files/model_and_optimize_meshes/8_bevel.jpg
  tutorials/files/model_and_optimize_meshes/9_extrude.png
  tutorials/model_and_optimize_meshes.md
  tutorials/model_command.md
  tutorials/particle_tutorial.md
Labels: needs upstream release, 🏢 edifice

#917 3D plot GUI plugin
  examples/worlds/plot_3d.sdf
  include/ignition/gazebo/Util.hh
  src/Util.cc
  src/Util_TEST.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/plot_3d/CMakeLists.txt
  src/gui/plugins/plot_3d/Plot3D.cc
  src/gui/plugins/plot_3d/Plot3D.hh
  src/gui/plugins/plot_3d/Plot3D.qml
  src/gui/plugins/plot_3d/Plot3D.qrc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
Labels: GUI, 🏰 citadel

#936 Support adding systems that don't come from a plugin
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  src/Server.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/Util.cc
  src/Util_TEST.cc
  test/helpers/Relay.hh
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/plugins/MockSystem.cc
  test/plugins/MockSystem.hh
Labels: 🏰 citadel

#935 Functions to enable velocity and acceleration checks on Link
  include/ignition/gazebo/Link.hh
  include/ignition/gazebo/Util.hh
  src/Link.cc
  src/Util_TEST.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/link.cc
Labels: 🏰 citadel

#944 removed unneeded plugin update
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
Labels: bug, 🏰 citadel

#946 3 ➡️ 4
  examples/worlds/plot_3d.sdf
  include/ignition/gazebo/Link.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  src/Link.cc
  src/Server.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/Util.cc
  src/Util_TEST.cc
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/plot_3d/CMakeLists.txt
  src/gui/plugins/plot_3d/Plot3D.cc
  src/gui/plugins/plot_3d/Plot3D.hh
  src/gui/plugins/plot_3d/Plot3D.qml
  src/gui/plugins/plot_3d/Plot3D.qrc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/wind_effects/WindEffects.cc
  test/helpers/Relay.hh
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/link.cc
  test/plugins/MockSystem.cc
  test/plugins/MockSystem.hh
Labels: 🔮 dome

#948 4 ➡️ 5
  examples/worlds/plot_3d.sdf
  include/ignition/gazebo/Link.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  src/Link.cc
  src/Server.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/Util.cc
  src/Util_TEST.cc
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/plot_3d/CMakeLists.txt
  src/gui/plugins/plot_3d/Plot3D.cc
  src/gui/plugins/plot_3d/Plot3D.hh
  src/gui/plugins/plot_3d/Plot3D.qml
  src/gui/plugins/plot_3d/Plot3D.qrc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/wind_effects/WindEffects.cc
  test/helpers/Relay.hh
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/link.cc
  test/plugins/MockSystem.cc
  test/plugins/MockSystem.hh
Labels: 🏢 edifice
