Repository gazebosim/gz-sim, pull requests merged in 2021-01, with the labels that each got.

#528 Don't make docs on macOS
  CMakeLists.txt
Labels: 🏰 citadel

#523 Don't make docs on macOS
  CMakeLists.txt
Labels: macOS, 📜 blueprint

#525 Updates to ardupilot migration tutorial
  tutorials/migrating_ardupilot_plugin.md
Labels: documentation, migration, 🏰 citadel

#527 change nullptr to a int ptr for qt 5.15.2 bug
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 🔮 dome

#522 Generate valid topics everywhere (support names with spaces)
  CMakeLists.txt
  examples/worlds/spaces.sdf
  include/ignition/gazebo/Util.hh
  src/LevelManager.cc
  src/SimulationRunner.cc
  src/Util.cc
  src/Util_TEST.cc
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/log/LogRecord.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/multicopter_control/MulticopterVelocityControl.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/velocity_control/VelocityControl.cc
  src/systems/wind_effects/WindEffects.cc
Labels: 🔮 dome

#281 Automatically load a subset of world plugins
  examples/worlds/default.sdf
  examples/worlds/shapes.sdf
  include/ignition/gazebo/CMakeLists.txt
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/config.hh.in
  include/ignition/gazebo/playback_server.config
  include/ignition/gazebo/server.config
  src/CMakeLists.txt
  src/Server.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/systems/log/LogRecord.cc
  test/worlds/plugins_empty.sdf
  test/worlds/server_invalid.config
  test/worlds/server_valid.config
  test/worlds/server_valid2.config
  test/worlds/shapes.sdf
  tutorials.md.in
  tutorials/files/server_config/camera_env.gif
  tutorials/files/server_config/camera_no_env.gif
  tutorials/files/server_config/default_server.gif
  tutorials/files/server_config/from_sdf.png
  tutorials/files/server_config/from_sdf_no_plugins.gif
  tutorials/files/server_config/modified_default_config.gif
  tutorials/server_config.md
Labels: migration, 🏰 citadel

#532 Add support for topic statistics on breadcrumb deployments
  CMakeLists.txt
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/breadcrumbs/Breadcrumbs.hh
Labels: 🔮 dome

#477 Improve ign tool support on macOS
  CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/cmdgazebo.rb.in
  src/ign_TEST.cc
Labels: macOS, tests, 🔮 dome

#541 Added missing version namespace
  include/ignition/gazebo/detail/EntityComponentManager.hh
Labels: 🏰 citadel

#543 Fix examples in migration plugins tutorial
  tutorials/migration_plugins.md
Labels: documentation, 🏰 citadel

#539 [FIX] Handle multiple logical cameras
  src/systems/logical_camera/LogicalCamera.cc
  test/integration/logical_camera_system.cc
  test/worlds/logical_camera_sensor.sdf
Labels: 🔮 dome

#546 Bump in edifice: ign-msgs7
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  docker/Dockerfile.nightly
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🏢 edifice

#537 Port: Automatically load a subset of world plugins (#281)
  examples/worlds/default.sdf
  examples/worlds/shapes.sdf
  include/ignition/gazebo/CMakeLists.txt
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/config.hh.in
  include/ignition/gazebo/playback_server.config
  include/ignition/gazebo/server.config
  src/CMakeLists.txt
  src/Server.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/systems/log/LogRecord.cc
  test/worlds/plugins_empty.sdf
  test/worlds/server_invalid.config
  test/worlds/server_valid.config
  test/worlds/server_valid2.config
  test/worlds/shapes.sdf
  tutorials.md.in
  tutorials/files/server_config/camera_env.gif
  tutorials/files/server_config/camera_no_env.gif
  tutorials/files/server_config/default_server.gif
  tutorials/files/server_config/from_sdf.png
  tutorials/files/server_config/from_sdf_no_plugins.gif
  tutorials/files/server_config/modified_default_config.gif
  tutorials/server_config.md
Labels: 🔮 dome

#552 Prepare for 3.7.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#554 Nkoenig/3 to 4 20210113
  Changelog.md
  include/ignition/gazebo/detail/EntityComponentManager.hh
  tutorials/migration_plugins.md
Labels: 🔮 dome

#559 Prepare for 4.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#555 Non-blocking paths request
  src/ServerPrivate.cc
  src/gui/PathManager.cc
Labels: GUI, 🏰 citadel

#560 Suggestions to #451
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
Labels: performance, 🏰 citadel

#451 Parallelize State call in ECM
  src/EntityComponentManager.cc
Labels: enhancement, performance, 🏰 citadel

#486 Use ComponentState::PeriodicChange in UpdateState to avoid forcing full scene update
  src/EntityComponentManager.cc
  src/network/NetworkManagerSecondary.cc
Labels: enhancement, performance, 🏢 edifice

#569 Suggestions to #513
  examples/worlds/empty.sdf
  src/systems/user_commands/UserCommands.cc
Labels: 🔮 dome

#549 Bump edifice sdformat11 and ign-physics4
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
  docker/Dockerfile.nightly
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🏢 edifice

#513 Allow to create light with the create service
  examples/worlds/empty.sdf
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: 🔮 dome

#564 Fix visibility macro names when used by a different component (Windows)
  include/ignition/gazebo/gui/Gui.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  include/ignition/gazebo/rendering/MarkerManager.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/systems/air_pressure/AirPressure.hh
  src/systems/altimeter/Altimeter.hh
  src/systems/apply_joint_force/ApplyJointForce.hh
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/buoyancy/Buoyancy.hh
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/contact/Contact.hh
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/diff_drive/DiffDrive.hh
  src/systems/diff_drive/SpeedLimiter.hh
  src/systems/follow_actor/FollowActor.hh
  src/systems/imu/Imu.hh
  src/systems/joint_controller/JointController.hh
  src/systems/joint_position_controller/JointPositionController.hh
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/lift_drag/LiftDrag.hh
  src/systems/log/LogPlayback.hh
  src/systems/log/LogRecord.hh
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/logical_camera/LogicalCamera.hh
  src/systems/magnetometer/Magnetometer.hh
  src/systems/multicopter_control/Common.hh
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/multicopter_motor_model/MulticopterMotorModel.hh
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/optical_tactile_plugin/Visualization.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.hh
  src/systems/pose_publisher/PosePublisher.hh
  src/systems/scene_broadcaster/SceneBroadcaster.hh
  src/systems/sensors/Sensors.hh
  src/systems/thermal/Thermal.hh
  src/systems/touch_plugin/TouchPlugin.hh
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/triggered_publisher/TriggeredPublisher.hh
  src/systems/user_commands/UserCommands.hh
  src/systems/velocity_control/VelocityControl.hh
  src/systems/wheel_slip/WheelSlip.hh
  src/systems/wind_effects/WindEffects.hh
Labels: 🏢 edifice

#572 👩‍🌾 Fix deprecation warnings
  CMakeLists.txt
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/network/NetworkManagerPrimary.cc
  src/systems/breadcrumbs/Breadcrumbs.cc
  src/systems/log/LogRecord.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/sdf_frame_semantics.cc
Labels: 🏢 edifice

#561 Use common::setenv for portability to Windows
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/Util.cc
  src/gui/Gui_TEST.cc
  src/ign_TEST.cc
  src/network/PeerTracker_TEST.cc
  test/integration/air_pressure_system.cc
  test/integration/altimeter_system.cc
  test/integration/apply_joint_force_system.cc
  test/integration/battery_plugin.cc
  test/integration/breadcrumbs.cc
  test/integration/buoyancy.cc
  test/integration/camera_video_record_system.cc
  test/integration/contact_system.cc
  test/integration/depth_camera.cc
  test/integration/detachable_joint.cc
  test/integration/diff_drive_system.cc
  test/integration/each_new_removed.cc
  test/integration/entity_erase.cc
  test/integration/events.cc
  test/integration/examples_build.cc
  test/integration/follow_actor_system.cc
  test/integration/gpu_lidar.cc
  test/integration/imu_system.cc
  test/integration/joint_controller_system.cc
  test/integration/joint_position_controller_system.cc
  test/integration/joint_state_publisher_system.cc
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/lift_drag_system.cc
  test/integration/link.cc
  test/integration/log_system.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/logical_camera_system.cc
  test/integration/magnetometer_system.cc
  test/integration/model.cc
  test/integration/multicopter.cc
  test/integration/performer_detector.cc
  test/integration/physics_system.cc
  test/integration/pose_publisher_system.cc
  test/integration/rgbd_camera.cc
  test/integration/save_world.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sdf_frame_semantics.cc
  test/integration/sensors_system.cc
  test/integration/thermal_system.cc
  test/integration/touch_plugin.cc
  test/integration/triggered_publisher.cc
  test/integration/user_commands.cc
  test/integration/velocity_control_system.cc
  test/integration/wheel_slip.cc
  test/integration/wind_effects.cc
  test/integration/world.cc
  test/performance/level_manager.cc
  test/test_config.hh.in
Labels: 🏢 edifice

#571 Change SelectedEntities to return a const ref
  Migration.md
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
Labels: 🏢 edifice

#575 Fix finding PBR materials
  src/rendering/SceneManager.cc
Labels: 🔮 dome

#576 4 ➡️ 5
  src/rendering/SceneManager.cc
Labels: 🏢 edifice

#501 Compilation fixes for Windows - codecheck patches (part 1)
  CMakeLists.txt
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/EventManager.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/World.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  include/ignition/gazebo/gui/GuiRunner.hh
  include/ignition/gazebo/gui/GuiSystem.hh
  include/ignition/gazebo/gui/TmpIface.hh
  src/CMakeLists.txt
  src/EventManager.cc
  src/SdfGenerator.hh
  src/Server.cc
  src/ServerPrivate.hh
  src/SimulationRunner.hh
  src/gui/GuiFileHandler.hh
  src/gui/PathManager.hh
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/systems/CMakeLists.txt
  test/integration/entity_erase.cc
Labels: Windows, 🏢 edifice

#544 Publish all periodic change components in Scene Broadcaster
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
Labels: enhancement, 🏰 citadel

#578 Set thermal camera sensor ambient temperature range using temperature gradient
  examples/worlds/thermal_camera.sdf
  src/systems/sensors/Sensors.cc
Labels: enhancement, needs upstream release, 🔮 dome

#514 Added renderOrder to convert functions
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/rendering/SceneManager.cc
Labels: needs upstream release, 🏢 edifice

#583 Backport state update changes from pull request #486
  src/EntityComponentManager.cc
  src/network/NetworkManagerSecondary.cc
Labels: performance, 🏰 citadel

#565 Remove invalid visibility macros to fix Windows compilation
  include/ignition/gazebo/System.hh
  include/ignition/gazebo/components/Factory.hh
  src/CMakeLists.txt
  src/System.cc
  src/cmd/ign.cc
  src/ign.cc
  src/ign.hh
  test/plugins/EventTriggerSystem.hh
  test/plugins/MockSystem.hh
  test/plugins/Null.hh
Labels: 🏢 edifice

#582 Fix code_check errors
  src/SimulationRunner.cc
  test/integration/logical_camera_system.cc
Labels: 🔮 dome

#531 Visualize collisions
  include/ignition/gazebo/rendering/RenderUtil.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: GUI, close the gap, rendering, 🏰 citadel

#585 Final Windows fixes to complete compilation
  include/ignition/gazebo/EventManager.hh
  include/ignition/gazebo/gui/GuiSystem.hh
  include/ignition/gazebo/gui/TmpIface.hh
  src/gui/CMakeLists.txt
  src/systems/CMakeLists.txt
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudio.hh
  test/integration/examples_build.cc
  test/integration/kinetic_energy_monitor_system.cc
  test/plugins/CMakeLists.txt
Labels: Windows, 🏢 edifice

#570 Remove playback <path> SDF param in Dome
  Migration.md
  src/ServerConfig.cc
  src/systems/log/LogPlayback.cc
  test/integration/log_system.cc
  test/worlds/log_playback.sdf
  tutorials/log.md
Labels: 🔮 dome

#400 Tutorial on migrating SDF files from Gazebo classic
  tutorials.md.in
  tutorials/migration_sdf.md
Labels: documentation, 🏰 citadel

#474 World exporter
  CMakeLists.txt
  examples/worlds/collada_world_exporter.sdf
  src/ServerPrivate.cc
  src/systems/CMakeLists.txt
  src/systems/collada_world_exporter/CMakeLists.txt
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  src/systems/collada_world_exporter/ColladaWorldExporter.hh
  test/integration/CMakeLists.txt
  test/integration/collada_world_exporter.cc
  test/integration/diff_drive_system.cc
  test/worlds/collada_world_exporter.sdf
  tutorials.md.in
  tutorials/collada_world_exporter.md
Labels: 🔮 dome
