Repository gazebosim/gz-sim, pull requests merged in 2021-06, with the labels that each got.

#837 Using math::SpeedLimiter on the ackermann_steering controller.
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/CMakeLists.txt
  src/systems/ackermann_steering/SpeedLimiter.cc
  src/systems/ackermann_steering/SpeedLimiter.hh
Labels: 🔮 dome

#857 Remove unneeded camera follow offset checks
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 🔮 dome

#855 Added service to set camera's follow offset
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: 🔮 dome

#841 Multi-LRAUV Swimming Race Example
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/multi_lrauv_race/README.md
  examples/standalone/multi_lrauv_race/multi_lrauv_race.cc
  examples/worlds/multi_lrauv_race.sdf
Labels: enhancement, 🏯 fortress

#848 Fix potentially flaky integration component test case
  test/integration/components.cc
Labels: 🏰 citadel

#832 Update wireframe visualization to support nested models
  src/rendering/RenderUtil.cc
Labels: GUI, 🏯 fortress

#860 Add Particle Emitter tutorial
  tutorials.md.in
  tutorials/files/particle_emitter/fog_generator.png
  tutorials/files/particle_emitter/particle_scatter_ratio.png
  tutorials/files/particle_emitter/sensor_scatter_tutorial.gif
  tutorials/particle_tutorial.md
Labels: documentation, 🔮 dome

#684 Set collision detector and solver from SDF
  examples/worlds/physics_options.sdf
  include/ignition/gazebo/components/Physics.hh
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  test/integration/physics_system.cc
  test/worlds/physics_options.sdf
  tutorials/physics.md
Labels: close the gap, enhancement, physics, 🏢 edifice

#844 Fix WindEffects Plugin bug, not configuring new links
  src/systems/wind_effects/WindEffects.cc
  test/integration/wind_effects.cc
  test/worlds/wind_effects.sdf
Labels: 🏢 edifice

#859 New example: get an ECM snapshot from an external program
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/external_ecm/README.md
  examples/standalone/external_ecm/external_ecm.cc
Labels: 🏰 citadel

#833 Using math::SpeedLimiter on the diff_drive controller.
  src/systems/diff_drive/CMakeLists.txt
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/SpeedLimiter.cc
  src/systems/diff_drive/SpeedLimiter.hh
  test/integration/diff_drive_system.cc
  test/worlds/diff_drive.sdf
  test/worlds/diff_drive_custom_topics.sdf
Labels: 🏰 citadel

#867 Depend on ign-rendering 3.5
  CMakeLists.txt
Labels: rendering, 🏰 citadel

#850 Enables confirmation dialog when closing Gazebo.
  CMakeLists.txt
  src/gui/gui.config
Labels: enhancement, 🏰 citadel

#858 Refactor RenderUtil::Update with helper functions
  src/rendering/RenderUtil.cc
Labels: 🔮 dome

#863 Set gui camera pose
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: GUI, 🏰 citadel

#870 Removed and moved tape measure and grid config to ign-gui
  Migration.md
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/grid_config/CMakeLists.txt
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/grid_config/GridConfig.hh
  src/gui/plugins/grid_config/GridConfig.qml
  src/gui/plugins/grid_config/GridConfig.qrc
  src/gui/plugins/tape_measure/CMakeLists.txt
  src/gui/plugins/tape_measure/TapeMeasure.cc
  src/gui/plugins/tape_measure/TapeMeasure.hh
  src/gui/plugins/tape_measure/TapeMeasure.qml
  src/gui/plugins/tape_measure/TapeMeasure.qrc
  src/gui/plugins/tape_measure/tape_measure.png
  src/gui/plugins/tape_measure/trashcan.png
Labels: 🏯 fortress

#866 3 ➡️ 4
  CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/external_ecm/README.md
  examples/standalone/external_ecm/external_ecm.cc
  src/gui/gui.config
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/align_tool/AlignTool.hh
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/diff_drive/CMakeLists.txt
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/SpeedLimiter.cc
  src/systems/diff_drive/SpeedLimiter.hh
  src/systems/wind_effects/WindEffects.cc
  test/integration/components.cc
  test/integration/diff_drive_system.cc
  test/integration/wind_effects.cc
  test/worlds/diff_drive.sdf
  test/worlds/diff_drive_custom_topics.sdf
  test/worlds/wind_effects.sdf
Labels: 🔮 dome

#875 Remove deprecations: tock 🕑
  examples/scripts/distributed/primary.sh
  examples/scripts/distributed/secondary.sh
  examples/scripts/distributed_levels/primary.sh
  examples/scripts/distributed_levels/secondary.sh
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/gui/TmpIface.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/ServerConfig.cc
  src/cmd/cmdgazebo.rb.in
  src/cmd/ign.cc
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/GuiRunner.hh
  src/gui/TmpIface.cc
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/lights/Lights.cc
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/network/NetworkConfig.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#879 Fix mouse view control target position
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 🏰 citadel

#887 Fix codecheck
  src/rendering/RenderUtil.cc
  src/systems/diff_drive/DiffDrive.cc
  test/integration/diff_drive_system.cc
  test/integration/odometry_publisher.cc
  test/integration/optical_tactile_plugin.cc
Labels: 🔮 dome

#889 Use UINT64_MAX for kComponentTpyeIdInvalid instead of relying on underflow
  include/ignition/gazebo/Types.hh
Labels: 🏰 citadel

#892 🎈 5.1.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#896 🎈 5.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice
