Repository gazebosim/gz-sim, pull requests merged in 2021-11, with the labels that each got.

#1153 Backport gazebo::Util::validTopic() from ign-gazebo4.
  include/ignition/gazebo/Util.hh
  src/Util.cc
  src/Util_TEST.cc
Labels: 🏰 citadel

#1160 Fix generation of systems library symlinks in build directory
  src/systems/CMakeLists.txt
Labels: 🏰 citadel

#1162 Set camera clipping plane distance
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: GUI, rendering, 🏯 fortress, 🌱 garden

#1157 Support printing sensors using `ign model`
  CMakeLists.txt
  src/CMakeLists.txt
  src/ModelCommandAPI_TEST.cc
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/cmd/cmdmodel.rb.in
  test/CMakeLists.txt
  test/find_dri.cmake
  test/worlds/magnetometer.sdf
  test/worlds/rgbd_camera_sensor.sdf
  tutorials/model_command.md
Labels: 🏯 fortress, 🌱 garden

#1104 Fixed sensor plugins
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
Labels: 🏰 citadel

#1166 minimal_scene.sdf example: add camera_clip params
  examples/worlds/minimal_scene.sdf
  test/integration/CMakeLists.txt
Labels: 🏯 fortress, 🌱 garden

#1169 Create expanding type header to reduce code duplication
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/ExpandingTypeHeader.qml
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Physics.qml
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/SphericalCoordinates.qml
  src/gui/plugins/component_inspector/Vector3d.qml
Labels: GUI, 🏯 fortress, 🌱 garden

#1109 Get updated GUI ECM info when a user presses 'play'
  CMakeLists.txt
  examples/plugin/rendering_plugins/rendering_plugins.sdf
  examples/scripts/log_video_recorder/log_video_recorder.sdf
  examples/worlds/camera_sensor.sdf
  examples/worlds/fuel_textured_mesh.sdf
  examples/worlds/grid.sdf
  examples/worlds/minimal_scene.sdf
  examples/worlds/optical_tactile_sensor_plugin.sdf
  examples/worlds/plot_3d.sdf
  examples/worlds/segmentation_camera.sdf
  examples/worlds/sensors_demo.sdf
  examples/worlds/sky.sdf
  examples/worlds/thermal_camera.sdf
  examples/worlds/tunnel.sdf
  examples/worlds/video_record_dbl_pendulum.sdf
  examples/worlds/visibility.sdf
  examples/worlds/visualize_contacts.sdf
  examples/worlds/visualize_lidar.sdf
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/gui/GuiRunner.cc
  src/gui/GuiRunner.hh
  src/gui/gui.config
  src/gui/playback_gui.config
Labels: needs upstream release, 🏯 fortress, 🌱 garden

#1101 Add functionality to add entities via the entity tree
  include/ignition/gazebo/Primitives.hh
  src/CMakeLists.txt
  src/Primitives.cc
  src/Primitives_TEST.cc
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/entity_tree/EntityTree.hh
  src/gui/plugins/entity_tree/EntityTree.qml
  src/gui/plugins/lights/Lights.cc
  src/gui/plugins/shapes/Shapes.cc
Labels: GUI, 🏯 fortress, 🌱 garden

#1167 Prevent a segfault when updating ComponentInspector
  src/gui/plugins/component_inspector/ComponentInspector.cc
Labels: bug, GUI, 🏯 fortress, 🌱 garden

#1149 [backport #1131] fix updating a component's data via SerializedState msg
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
Labels: 🏰 citadel

#1163 Publish 10 world stats msgs/sec instead of 5
  src/SimulationRunner.cc
Labels: 🏯 fortress, 🌱 garden

#1078 Tweaks install instructions
  README.md
  tutorials.md.in
  tutorials/install.md
Labels: documentation, 🏯 fortress

#1179 Move AirPressure functions out of ComponentInspector (suggestion to #1171)
  src/gui/plugins/component_inspector/AirPressure.cc
  src/gui/plugins/component_inspector/AirPressure.qml
  src/gui/plugins/component_inspector/ComponentInspector.qml
Labels: GUI, 🏯 fortress

#1013 Support copy/paste
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/copy_paste/CMakeLists.txt
  src/gui/plugins/copy_paste/CopyPaste.cc
  src/gui/plugins/copy_paste/CopyPaste.hh
  src/gui/plugins/copy_paste/CopyPaste.qml
  src/gui/plugins/copy_paste/CopyPaste.qrc
  src/gui/plugins/copy_paste/copy_object.png
  src/gui/plugins/copy_paste/paste_object.png
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/spawn/Spawn.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: editor, 🏯 fortress

#1180 Extend odom publisher to allow 3D
  examples/worlds/multicopter_velocity_control.sdf
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  test/integration/odometry_publisher.cc
  test/worlds/odometry_publisher_3d.sdf
Labels: 🏢 edifice

#1053 Remove bounding box when entities are removed
  include/ignition/gazebo/gui/GuiEvents.hh
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/plugins/select_entities/SelectEntities.cc
Labels: bug, 🏯 fortress

#1181 3 ➡️ 4
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Float.qml
  src/gui/plugins/component_inspector/Integer.qml
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  test/integration/CMakeLists.txt
  test/integration/camera_sensor_background.cc
  test/worlds/camera_sensor_empty_scene.sdf
Labels: 🔮 dome

#1165 Model editor: Add links to model
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ModelEditor.cc
  src/gui/plugins/component_inspector/ModelEditor.hh
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/entity_tree/EntityTree.hh
  src/gui/plugins/entity_tree/EntityTree.qml
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/rendering/RenderUtil.cc
Labels: GUI, 🏯 fortress, 🌱 garden

#847 Added components to dynamically set joint limits
  CMakeLists.txt
  include/ignition/gazebo/components/JointEffortLimitsCmd.hh
  include/ignition/gazebo/components/JointPositionLimitsCmd.hh
  include/ignition/gazebo/components/JointVelocityLimitsCmd.hh
  include/ignition/gazebo/components/Serialization.hh
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/physics_system.cc
  test/worlds/revolute_joint_equilibrium.sdf
Labels: 🏰 citadel

#869 Added support for tracked vehicles
  examples/worlds/conveyor.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  include/ignition/gazebo/components/Collision.hh
  include/ignition/gazebo/physics/Events.hh
  src/systems/CMakeLists.txt
  src/systems/physics/Physics.cc
  src/systems/track_controller/CMakeLists.txt
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  src/systems/tracked_vehicle/CMakeLists.txt
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/tracked_vehicle/TrackedVehicle.hh
  test/integration/CMakeLists.txt
  test/integration/tracked_vehicle_system.cc
  test/worlds/conveyor.sdf
  test/worlds/tracked_vehicle_simple.sdf
Labels: 🏰 citadel

#1186 4 ➡️ 5
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/components/VisualCmd.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Float.qml
  src/gui/plugins/component_inspector/Integer.qml
  src/gui/plugins/component_inspector/Material.qml
  src/gui/plugins/shapes/Shapes.cc
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  src/systems/user_commands/UserCommands.cc
  test/integration/CMakeLists.txt
  test/integration/camera_sensor_background.cc
  test/worlds/camera_sensor_empty_scene.sdf
Labels: 🏢 edifice

#1185 Add sdfString to copy constructor.
  src/ServerConfig.cc
Labels: 🏯 fortress, 🌱 garden

#1192 Prevent creation of spurious <plugin> elements when saving worlds
  src/LevelManager.cc
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
Labels: 🏰 citadel

#1193 🎈 3.12.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#1187 Together
  include/ignition/gazebo/detail/View.hh
  src/EntityComponentManager.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/gui/plugins/component_inspector/ModelEditor.cc
  src/systems/physics/Physics.cc
  test/integration/recreate_entities.cc
Labels: GUI, editor, 🏯 fortress

#1195 3 ➡️ 4
  CMakeLists.txt
  Changelog.md
  examples/worlds/conveyor.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  include/ignition/gazebo/components/Collision.hh
  include/ignition/gazebo/components/JointEffortLimitsCmd.hh
  include/ignition/gazebo/components/JointPositionLimitsCmd.hh
  include/ignition/gazebo/components/JointVelocityLimitsCmd.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/physics/Events.hh
  src/LevelManager.cc
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/physics/Physics.cc
  src/systems/track_controller/CMakeLists.txt
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  src/systems/tracked_vehicle/CMakeLists.txt
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/tracked_vehicle/TrackedVehicle.hh
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/physics_system.cc
  test/integration/tracked_vehicle_system.cc
  test/worlds/conveyor.sdf
  test/worlds/revolute_joint_equilibrium.sdf
  test/worlds/tracked_vehicle_simple.sdf
Labels: 🔮 dome

#1189 5 ➡️ 6
  examples/worlds/multicopter_velocity_control.sdf
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/components/VisualCmd.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/EntityComponentManager.cc
  src/Primitives.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Float.qml
  src/gui/plugins/component_inspector/Integer.qml
  src/gui/plugins/component_inspector/Material.qml
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  src/systems/user_commands/UserCommands.cc
  test/integration/CMakeLists.txt
  test/integration/camera_sensor_background.cc
  test/integration/odometry_publisher.cc
  test/worlds/camera_sensor_empty_scene.sdf
  test/worlds/odometry_publisher_3d.sdf
Labels: 🏯 fortress, 🌱 garden

#1197 4 ➡️ 5
  CMakeLists.txt
  Changelog.md
  examples/worlds/conveyor.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  include/ignition/gazebo/components/Collision.hh
  include/ignition/gazebo/components/JointEffortLimitsCmd.hh
  include/ignition/gazebo/components/JointPositionLimitsCmd.hh
  include/ignition/gazebo/components/JointVelocityLimitsCmd.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/physics/Events.hh
  src/LevelManager.cc
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/physics/Physics.cc
  src/systems/track_controller/CMakeLists.txt
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  src/systems/tracked_vehicle/CMakeLists.txt
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/tracked_vehicle/TrackedVehicle.hh
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/physics_system.cc
  test/integration/tracked_vehicle_system.cc
  test/worlds/conveyor.sdf
  test/worlds/revolute_joint_equilibrium.sdf
  test/worlds/tracked_vehicle_simple.sdf
Labels: 🏢 edifice

#1200 🎈 5.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#1190 Thruster plugin: add tests and velocity control
  Migration.md
  examples/worlds/auv_controls.sdf
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/CMakeLists.txt
  test/integration/thruster.cc
  test/worlds/thruster_pid.sdf
  test/worlds/thruster_vel_cmd.sdf
Labels: 🏢 edifice

#1076 Configurable joint state publisher's topic
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/joint_state_publisher/JointStatePublisher.hh
Labels: 🏢 edifice

#1206 Recreate entities joints
  src/EntityComponentManager.cc
  test/integration/recreate_entities.cc
  test/worlds/double_pendulum.sdf
Labels: GUI, editor, 🏯 fortress

#1207 🎈 4.13.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#1199 5 ➡️ 6
  CMakeLists.txt
  Changelog.md
  Migration.md
  examples/worlds/auv_controls.sdf
  examples/worlds/conveyor.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  include/ignition/gazebo/components/Collision.hh
  include/ignition/gazebo/components/JointEffortLimitsCmd.hh
  include/ignition/gazebo/components/JointPositionLimitsCmd.hh
  include/ignition/gazebo/components/JointVelocityLimitsCmd.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/physics/Events.hh
  src/LevelManager.cc
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/physics/Physics.cc
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  src/systems/track_controller/CMakeLists.txt
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  src/systems/tracked_vehicle/CMakeLists.txt
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/tracked_vehicle/TrackedVehicle.hh
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/physics_system.cc
  test/integration/thruster.cc
  test/integration/tracked_vehicle_system.cc
  test/worlds/conveyor.sdf
  test/worlds/revolute_joint_equilibrium.sdf
  test/worlds/thruster_pid.sdf
  test/worlds/thruster_vel_cmd.sdf
  test/worlds/tracked_vehicle_simple.sdf
Labels: 🏯 fortress

#1170 Support recreating model entities
  CMakeLists.txt
  include/ignition/gazebo/components/Recreate.hh
  include/ignition/gazebo/detail/View.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ModelEditor.cc
  src/systems/physics/Physics.cc
  src/systems/sensors/Sensors.cc
  test/integration/CMakeLists.txt
  test/integration/recreate_entities.cc
  test/worlds/double_pendulum.sdf
  test/worlds/fixed_world_joint.sdf
Labels: editor, 🏯 fortress

#1213 Update new / removed entity GUI events
  include/ignition/gazebo/gui/GuiEvents.hh
  src/gui/CMakeLists.txt
  src/gui/GuiEvents.cc
  src/gui/GuiEvents_TEST.cc
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/plugins/select_entities/SelectEntities.cc
Labels: 🏯 fortress

#1171 Support editing air pressure sensor in the GUI
  CMakeLists.txt
  src/cmd/ModelCommandAPI.cc
  src/gui/plugins/component_inspector/AirPressure.cc
  src/gui/plugins/component_inspector/AirPressure.hh
  src/gui/plugins/component_inspector/AirPressure.qml
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/ExpandingTypeHeader.qml
  src/gui/plugins/component_inspector/Noise.qml
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/StateAwareSpin.qml
  src/gui/plugins/component_inspector/TypeHeader.qml
  src/gui/plugins/component_inspector/Types.cc
  src/gui/plugins/component_inspector/Types.hh
  src/gui/plugins/component_inspector/Vector3d.qml
  src/gui/plugins/modules/TypeIcon.qml
  src/gui/resources/gazebo.qrc
  src/gui/resources/images/sensor.png
  src/systems/scene_broadcaster/SceneBroadcaster.cc
Labels: GUI, sensors, editor, 🏯 fortress

#1159 Fix the force-torque sensor update rate
  examples/worlds/sensors.sdf
  src/systems/force_torque/ForceTorque.cc
  test/integration/force_torque_system.cc
  test/worlds/force_torque.sdf
Labels: 🏯 fortress

#1172 Added altimeter sensor inspector
  src/gui/plugins/component_inspector/Altimeter.cc
  src/gui/plugins/component_inspector/Altimeter.hh
  src/gui/plugins/component_inspector/Altimeter.qml
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qrc
Labels: GUI, sensors, editor, 🏯 fortress

#1173 Added magnetometer inspector
  src/cmd/ModelCommandAPI.cc
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Magnetometer.cc
  src/gui/plugins/component_inspector/Magnetometer.hh
  src/gui/plugins/component_inspector/Magnetometer.qml
  test/integration/recreate_entities.cc
Labels: GUI, sensors, editor, 🏯 fortress

#1183 Bumps in garden : ign-gazebo7
  .github/ci/packages.apt
  CMakeLists.txt
  docker/Dockerfile.nightly
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/plugin/rendering_plugins/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🌱 garden

#1204 Disable user commands light test on macOS
  test/integration/user_commands.cc
Labels: 🔮 dome

#1203 Added lidar component inspector
  examples/worlds/sensors.sdf
  src/cmd/ModelCommandAPI.cc
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Lidar.cc
  src/gui/plugins/component_inspector/Lidar.hh
  src/gui/plugins/component_inspector/Lidar.qml
  src/gui/plugins/component_inspector/LidarScan.qml
  src/gui/plugins/component_inspector/Noise.qml
  src/gui/plugins/component_inspector/StateAwareSpin.qml
Labels: GUI, sensors, editor, 🏯 fortress

#1221 Increase maximum values in ViewAngle widget
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: GUI, 🏯 fortress

#1211 Fix buoyancy not being applied for one iteration
  src/systems/buoyancy/Buoyancy.cc
  test/integration/buoyancy.cc
Labels: 🏯 fortress

#1220 Update SdfGenerator to save joint data to file
  src/SdfGenerator.cc
  src/SdfGenerator.hh
  test/integration/save_world.cc
  test/worlds/joint_sensor.sdf
Labels: editor

#1209 Update SdfGenerator to save light data to file
  src/SdfGenerator.cc
  src/SdfGenerator.hh
  test/integration/save_world.cc
  test/worlds/joint_sensor.sdf
Labels: editor, 🏯 fortress
