Repository gazebosim/gz-sim, pull requests merged in 2021-10, with the labels that each got.

#1079 🎈 6.0.0
  CMakeLists.txt
  Changelog.md
  README.md
Labels: beta, 🏯 fortress

#1077 Fix light control standalone example
  examples/standalone/light_control/light_control.cc
Labels: 🔮 dome

#1082 Fix View Angle's home button
  src/gui/plugins/view_angle/ViewAngle.cc
Labels: bug, 🏯 fortress

#1081 Fix transform controls
  src/gui/plugins/transform_control/TransformControl.cc
Labels: bug, 🏯 fortress

#1083 Performance: use std::unordered_map where possible in SceneManager
  src/rendering/SceneManager.cc
Labels: 🏰 citadel, performance

#1075 Set a cloned joint's parent/child link names to the cloned parent/child link names
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
Labels: 🏯 fortress

#1021 Add support for configuring point size in Visualize Lidar GUI plugin
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.hh
  src/gui/plugins/visualize_lidar/VisualizeLidar.qml
Labels: needs upstream release, 🏯 fortress

#1151 Add a default value for isHeadlessRendering.
  src/ServerConfig.cc
Labels: 🏯 fortress, 🌱 garden
