Repository gazebosim/gz-sim, pull requests merged in 2021-09, with the labels that each got.

#1001 Lock views during system PostUpdates
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/SimulationRunner.cc
Labels: 🏯 fortress

#1005 Update DART deps to Focal
  docker/scripts/install_ign_deps.sh
Labels: 🏢 edifice

#969 Fix selection buffer crash on resize
  src/gui/plugins/scene3d/Scene3D.cc
Labels: 🔮 dome

#983 Added Spawn plugin
  examples/worlds/minimal_scene.sdf
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/spawn/CMakeLists.txt
  src/gui/plugins/spawn/Spawn.cc
  src/gui/plugins/spawn/Spawn.hh
  src/gui/plugins/spawn/Spawn.qml
  src/gui/plugins/spawn/Spawn.qrc
Labels: 🏯 fortress

#1015 Fix setting cast_shadows for visuals without material
  src/rendering/SceneManager.cc
Labels: 🏰 citadel, rendering

#1017 3 ➡️ 4
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  examples/worlds/logical_camera_sensor.sdf
  examples/worlds/pendulum_links.sdf
  examples/worlds/sensors.sdf
  examples/worlds/sensors_demo.sdf
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/Events.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/components/ContactSensor.hh
  include/ignition/gazebo/components/Factory.hh
  include/ignition/gazebo/components/LogicalCamera.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/gui/GuiSystem.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/gui/plugins/align_tool/AlignTool.hh
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/modules/EntityContextMenu.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/shapes/Shapes.cc
  src/rendering/SceneManager.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/buoyancy/Buoyancy.hh
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/EntityFeatureMap.hh
  src/systems/touch_plugin/TouchPlugin.hh
  src/systems/triggered_publisher/TriggeredPublisher.hh
  src/systems/wind_effects/WindEffects.hh
  tutorials/distributed_simulation.md
Labels: 🔮 dome, beta

#1018 Fixed GUI's ComponentInspector light parameter
  src/gui/plugins/component_inspector/ComponentInspector.cc
Labels: GUI, 🔮 dome

#912 Collada world exporter now exporting lights
  CMakeLists.txt
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  test/integration/collada_world_exporter.cc
  test/worlds/collada_world_exporter_lights.sdf
Labels: 🏢 edifice

#1023 Fix test failures due to recent changes in SDFormat
  src/SdfGenerator_TEST.cc
Labels: bug, beta, 🏯 fortress

#1003 Adds velocity control to JointPositionController.
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_position_controller/JointPositionController.hh
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller_velocity.sdf
Labels: beta, 🏯 fortress

#988 Added VisualizationCapabilities plugin
  examples/worlds/minimal_scene.sdf
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/visualization_capabilities/CMakeLists.txt
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.hh
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.qml
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.qrc
Labels: beta, 🏯 fortress

#1026 Remove unused ignition gui header
  src/ServerPrivate.cc
Labels: 🏢 edifice

#701 Add a flag to force headless rendering mode
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/components/RenderEngineServerHeadless.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/LevelManager.cc
  src/ServerConfig.cc
  src/cmd/cmdgazebo.rb.in
  src/ign.cc
  src/ign.hh
  src/rendering/RenderUtil.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/sensors/Sensors.cc
Labels: enhancement, rendering, beta, 🏯 fortress

#1028 Fix crash on resize
  src/gui/plugins/scene3d/Scene3D.cc
Labels: bug, beta, 🏯 fortress

#1029 Prepare for 4.10.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#1033 Fix Windows build
  src/systems/joint_position_controller/JointPositionController.cc
Labels: bug, Windows, beta, 🏯 fortress

#1009 Buoyancy engine
  examples/worlds/buoyancy_engine.sdf
  src/systems/CMakeLists.txt
  src/systems/buoyancy_engine/BuoyancyEngine.cc
  src/systems/buoyancy_engine/BuoyancyEngine.hh
  src/systems/buoyancy_engine/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/buoyancy_engine.cc
  test/worlds/buoyancy_engine.sdf
Labels: beta, 🏯 fortress

#1035 [Testing] Use System plugin to manage same process
  include/ignition/gazebo/Events.hh
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/gui/Gui.hh
  include/ignition/gazebo/gui/GuiSystem.hh
  src/Server.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/gui/CMakeLists.txt
  src/gui/ClientSystem.cc
  src/gui/ClientSystem.hh
  src/gui/Gui.cc
  src/gui/GuiRunner.cc
  src/gui/Gui_TEST.cc
  src/ign.cc
Labels: beta, 🏯 fortress

#989 Populate JointConstraintWrench from physics
  include/ignition/gazebo/components/JointTransmittedWrench.hh
  src/systems/physics/Physics.cc
  test/integration/components.cc
  test/integration/physics_system.cc
  test/worlds/joint_transmitted_wrench.sdf
Labels: beta, 🏯 fortress

#900 Make Video recorder plugin work with MinimalScene
  examples/worlds/minimal_scene.sdf
  src/gui/plugins/video_recorder/CMakeLists.txt
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/video_recorder/VideoRecorder.hh
Labels: beta, 🏯 fortress

#1034 Fix minimal scene render engine gui name from command line arg
  include/ignition/gazebo/gui/Gui.hh
  src/cmd/cmdgazebo.rb.in
  src/gui/Gui.cc
  src/gui/Gui_TEST.cc
  src/ign.cc
  src/ign.hh
Labels: beta, 🏯 fortress

#818 Buoyancy improvements
  examples/worlds/graded_buoyancy.sdf
  src/systems/buoyancy/Buoyancy.cc
  src/systems/buoyancy/Buoyancy.hh
  test/integration/buoyancy.cc
  test/worlds/graded_buoyancy.sdf
Labels: beta, 🏯 fortress

#1008 🌐 Spherical coordinates
  CMakeLists.txt
  examples/worlds/spherical_coordinates.sdf
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/World.hh
  include/ignition/gazebo/components/Serialization.hh
  include/ignition/gazebo/components/SphericalCoordinates.hh
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/Util.cc
  src/World.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/SphericalCoordinates.qml
  src/gui/plugins/plotting/Plotting.cc
  src/gui/plugins/plotting/Plotting.hh
  src/systems/user_commands/UserCommands.cc
  test/integration/CMakeLists.txt
  test/integration/spherical_coordinates.cc
  test/integration/world.cc
  test/worlds/spherical_coordinates.sdf
  tutorials.md.in
  tutorials/files/spherical_coordinates/ENU.svg
  tutorials/files/spherical_coordinates/inspector.png
  tutorials/spherical_coordinates.md
Labels: close the gap, beta, 🏯 fortress

#959 Add support for cloning entities
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/rendering/SceneManager.hh
  src/Component_TEST.cc
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/spawn/Spawn.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/user_commands/UserCommands.cc
Labels: editor, beta, 🏯 fortress

#977 Joint Force-Torque Systems Plugin
  CMakeLists.txt
  include/ignition/gazebo/components/ForceTorque.hh
  src/SdfEntityCreator.cc
  src/systems/CMakeLists.txt
  src/systems/force_torque/CMakeLists.txt
  src/systems/force_torque/ForceTorque.cc
  src/systems/force_torque/ForceTorque.hh
  test/integration/CMakeLists.txt
  test/integration/force_torque_system.cc
  test/worlds/force_torque.sdf
Labels: beta, 🏯 fortress

#853 Label Component & System
  CMakeLists.txt
  examples/worlds/segmentation_camera.sdf
  include/ignition/gazebo/components/SegmentationCamera.hh
  include/ignition/gazebo/components/SemanticLabel.hh
  src/SdfEntityCreator.cc
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/label/CMakeLists.txt
  src/systems/label/Label.cc
  src/systems/label/Label.hh
  src/systems/sensors/CMakeLists.txt
  src/systems/sensors/Sensors.cc
Labels: beta, 🏯 fortress

#862 Support locked entities, and headless video recording using sim time
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
Labels: 🔮 dome

#1044 4 11 0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#1047 Don't save segmentation data by default in the example world
  examples/worlds/segmentation_camera.sdf
Labels: documentation, beta, 🏯 fortress

#1046 Enable new CMake policy to fix protobuf compilation
  CMakeLists.txt
Labels: bug, Windows, beta

#1048 Fix performance issue with contact data and AABB updates
  src/systems/physics/Physics.cc
Labels: 🔮 dome, performance

#1052 Fix GUI crash when accessing bad rendering UserData
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/entity_context_menu/EntityContextMenuPlugin.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/spawn/Spawn.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
Labels: bug, GUI, rendering, beta, 🏯 fortress

#1050 Place config files in a versioned directory
  Migration.md
  src/ServerConfig.cc
  src/cmd/ign.cc
  src/gui/Gui.cc
  tutorials/gui_config.md
  tutorials/migration_sdf.md
  tutorials/resources.md
  tutorials/server_config.md
  tutorials/video_recorder.md
Labels: bug, beta, 🏯 fortress

#1051 Fixes to GUI config and minimal scene example
  examples/worlds/minimal_scene.sdf
  src/gui/gui.config
Labels: bug, GUI, beta, 🏯 fortress

#1054 Support setting heightmap position through sdf
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#1055 Fix finding heightmap blend textures
  src/rendering/SceneManager.cc
Labels: bug, beta, 🏯 fortress

#1064 Fix rotating cubes when placed by GUI tool while using the buoyancy plugin
  src/systems/buoyancy/Buoyancy.cc
  test/integration/buoyancy.cc
Labels: bug, beta, 🏯 fortress

#1062 5 ➡️ main
  Changelog.md
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ServerPrivate.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/physics/Physics.cc
Labels: bug, beta, 🏯 fortress

#1068 Suppress missing canonical link error messages for static models
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
Labels: 🏯 fortress

#1069 Fix SDFormat generation of pose elements
  src/SdfGenerator.cc
  src/SdfGenerator_TEST.cc
Labels: bug, beta, 🏯 fortress

#1070 Make sure config directory is created
  src/cmd/ign.cc
Labels: bug, beta, 🏯 fortress

#1074 Link to ERB template tutorial
  tutorials.md.in
Labels: 🏯 fortress

#1063 Non desired window opening alongside ignition GUI
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
Labels: bug, rendering, beta, 🏯 fortress

#899 Parse new param for enabling / disabling IMU orientation output
  src/systems/imu/Imu.cc
  test/integration/imu_system.cc
  test/worlds/imu_no_orientation.sdf
Labels: 🔮 dome, needs upstream release

#1067 Enable specific entities on buoyancy plugin
  examples/worlds/graded_buoyancy.sdf
  src/gui/plugins/video_recorder/VideoRecorder.hh
  src/systems/buoyancy/Buoyancy.cc
  src/systems/buoyancy/Buoyancy.hh
  test/integration/buoyancy.cc
  test/worlds/graded_buoyancy.sdf
Labels: bug, beta, 🏯 fortress

#1073 Fix guirunner timing
  src/gui/GuiRunner.cc
Labels: bug, beta, 🏯 fortress
