Repository gazebosim/gz-sim, pull requests merged in 2021-04, with the labels that each got.

#674 Support configuring particle scatter ratio in particle emitter system
  src/rendering/SceneManager.cc
  src/systems/particle_emitter/ParticleEmitter.cc
  test/integration/particle_emitter.cc
  test/worlds/particle_emitter.sdf
Labels: needs upstream release, 🔮 dome

#733 Update description
  src/gui/plugins/playback_scrubber/PlaybackScrubber.hh
Labels: 🏢 edifice

#678 iterate through changed links only in UpdateSim
  src/systems/physics/EntityFeatureMap.hh
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  test/integration/wind_effects.cc
  test/worlds/wind_effects.sdf
Labels: enhancement, performance, 🏢 edifice

#716 Do not pass -Wno-unused-parameter to MSVC compiler
  src/CMakeLists.txt
Labels: Windows, bug

#715 Use Protobuf_IMPORT_DIRS instead of PROTOBUF_IMPORT_DIRS for compatibility with Protobuf CMake config
  CMakeLists.txt
Labels: Windows, bug, 🏰 citadel

#724 Fix component inspector shutdown crash
  src/gui/plugins/component_inspector/ComponentInspector.cc
Labels: GUI, 🏢 edifice

#740 Validate step size and RTF parameters
  src/SimulationRunner.cc
  test/integration/user_commands.cc
Labels: 🔮 dome

#737 Fix compute_rtfs arguments
  test/performance/ign_perf.py
Labels: 🔮 dome

#746 Dome: fixed collision visual bounding boxes
  src/rendering/RenderUtil.cc
Labels: 🔮 dome

#750 3 to 4 20210408
  CMakeLists.txt
  Changelog.md
  src/CMakeLists.txt
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/altimeter_with_pose.sdf
Labels: 🔮 dome

#742 ECM's ChangedState gets message with modified components
  include/ignition/gazebo/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  test/integration/log_system.cc
Labels: 🔮 dome

#745 Fix log playback for particle emitters
  src/systems/log/LogPlayback.cc
Labels: 🔮 dome

#730 Particle emitter based on SDF
  examples/worlds/particle_emitter.sdf
  examples/worlds/particle_emitter2.sdf
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/SdfEntityCreator.hh
  include/ignition/gazebo/Util.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SdfEntityCreator.cc
  src/Util.cc
  src/Util_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/particle_emitter/ParticleEmitter.hh
  src/systems/particle_emitter2/CMakeLists.txt
  src/systems/particle_emitter2/ParticleEmitter2.cc
  src/systems/particle_emitter2/ParticleEmitter2.hh
  test/integration/CMakeLists.txt
  test/integration/particle_emitter2.cc
  test/worlds/particle_emitter2.sdf
Labels: 🔮 dome

#755 4 7 0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🏯 fortress

#754 Fix 'invalid animation update data' message for actors
  src/rendering/RenderUtil.cc
Labels: 🏢 edifice, 🏯 fortress

#766 Update benchmark comparison instructions
  test/benchmark/README.md
Labels: 🏰 citadel

#772 [DiffDrive] add enable/disable
  src/systems/diff_drive/DiffDrive.cc
  test/integration/diff_drive_system.cc
Labels: 🏢 edifice

#547 Add odometry publisher system
  src/systems/CMakeLists.txt
  src/systems/odometry_publisher/CMakeLists.txt
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  test/integration/CMakeLists.txt
  test/integration/odometry_publisher.cc
  test/worlds/odometry_publisher.sdf
  test/worlds/odometry_publisher_custom.sdf
Labels: 🔮 dome

#777 Patch particle emitter2 service
  src/systems/particle_emitter2/ParticleEmitter2.cc
Labels: 🔮 dome

#780 Preparing for 4.8.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#646 👩‍🌾 Enable Focal CI
  .github/workflows/ci.yml
  src/ServerPrivate.cc
  src/SimulationRunner.cc
  test/integration/diff_drive_system.cc
  test/integration/wheel_slip.cc
Labels: tests, 🏰 citadel

#427 [TPE] Support setting individual link velocity
  examples/worlds/pendulum_links.sdf
  src/systems/physics/Physics.cc
  src/systems/velocity_control/VelocityControl.cc
  test/integration/velocity_control_system.cc
  test/worlds/velocity_control.sdf
Labels: physics, 🏰 citadel

#751 Don't store duplicate ComponentTypeId in ECM
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
Labels: performance, 🏰 citadel

#749 Feature/hydrodynamics
  examples/worlds/auv_controls.sdf
  src/systems/CMakeLists.txt
  src/systems/hydrodynamics/CMakeLists.txt
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  src/systems/thruster/CMakeLists.txt
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  tutorials/files/underwater/MBARI forces.png
  tutorials/underwater_vehicles.md
Labels: 🏢 edifice

#784 👩‍🌾 Fix macOS build: components::Name in benchmark
  test/benchmark/each.cc
Labels: macOS, 🏰 citadel

#763 Fix ColladaExporter submesh index bug
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  test/integration/collada_world_exporter.cc
  test/worlds/collada_world_exporter_submesh.sdf
  test/worlds/models/mesh_with_submeshes/materials/textures/cordless_drill.png
  test/worlds/models/mesh_with_submeshes/meshes/mesh_with_submeshes.dae
  test/worlds/models/mesh_with_submeshes/model.config
  test/worlds/models/mesh_with_submeshes/model.sdf
Labels: bug, 🏢 edifice

#782 👩‍🌾 Fix Windows build and some warnings
  src/ComponentFactory_TEST.cc
  src/Component_TEST.cc
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/SdfEntityCreator_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
  src/gui/CMakeLists.txt
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/tape_measure/TapeMeasure.cc
  src/rendering/CMakeLists.txt
  src/rendering/SceneManager.cc
  src/systems/CMakeLists.txt
  src/systems/joint_traj_control/CMakeLists.txt
  src/systems/joint_traj_control/JointTrajectoryController.cc
  src/systems/joint_traj_control/JointTrajectoryController.hh
  src/systems/optical_tactile_plugin/Visualization.cc
  test/integration/CMakeLists.txt
  test/integration/altimeter_system.cc
  test/integration/components.cc
  test/integration/imu_system.cc
  test/integration/log_system.cc
  test/integration/physics_system.cc
  test/integration/user_commands.cc
  test/performance/sdf_runner.cc
  test/plugins/CMakeLists.txt
Labels: Windows, 🏢 edifice

#747 Prevent crash on Plotting plugin with mutex
  src/gui/plugins/plotting/Plotting.cc
Labels: GUI, bug, 🏢 edifice

#788 explain why detail::View symbols are visible
  include/ignition/gazebo/detail/View.hh
Labels: 🏯 fortress

#795 Fix documentation for EntityComponentManager::EachNew
  include/ignition/gazebo/EntityComponentManager.hh
Labels: 🏰 citadel

#792 3 ➡️ 4
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/worlds/pendulum_links.sdf
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/physics/Physics.cc
  src/systems/velocity_control/VelocityControl.cc
  test/benchmark/README.md
  test/benchmark/each.cc
  test/integration/diff_drive_system.cc
  test/integration/velocity_control_system.cc
  test/integration/wheel_slip.cc
  test/worlds/velocity_control.sdf
Labels: 🔮 dome
