Repository gazebosim/gz-sim, pull requests merged in 2021-05, with the labels that each got.

#431 Add functionalities for optical tactile plugin
  examples/worlds/optical_tactile_sensor_plugin.sdf
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/optical_tactile_plugin/Visualization.cc
  src/systems/optical_tactile_plugin/Visualization.hh
  test/integration/CMakeLists.txt
  test/integration/optical_tactile_plugin.cc
  test/worlds/optical_tactile_plugin.sdf
Labels: tests, 🔮 dome

#234 Visualize ContactSensorData
  examples/worlds/visualize_contacts.sdf
  src/EntityComponentManager.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/visualize_contacts/CMakeLists.txt
  src/gui/plugins/visualize_contacts/VisualizeContacts.cc
  src/gui/plugins/visualize_contacts/VisualizeContacts.hh
  src/gui/plugins/visualize_contacts/VisualizeContacts.qml
  src/gui/plugins/visualize_contacts/VisualizeContacts.qrc
  src/systems/physics/Physics.cc
  src/systems/user_commands/UserCommands.cc
Labels: close the gap, 🔮 dome

#804 Backport #763
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  test/integration/collada_world_exporter.cc
  test/worlds/collada_world_exporter_submesh.sdf
  test/worlds/models/mesh_with_submeshes/materials/textures/cordless_drill.png
  test/worlds/models/mesh_with_submeshes/meshes/mesh_with_submeshes.dae
  test/worlds/models/mesh_with_submeshes/model.config
  test/worlds/models/mesh_with_submeshes/model.sdf
Labels: 🔮 dome

#794 Util: Use public API from libsdformat for detecting non-file source
  src/Util.cc
Labels: 🏢 edifice

#812 [Backport #536 3 ⬅️ 4] Add service and GUI to configure physics parameters
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/components/Physics.hh
  include/ignition/gazebo/components/PhysicsCmd.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Physics.qml
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: 🏰 citadel

#809 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#817 Trigger delay
  examples/worlds/triggered_publisher.sdf
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/triggered_publisher/TriggeredPublisher.hh
  test/integration/triggered_publisher.cc
  test/worlds/triggered_publisher.sdf
Labels: 🔮 dome

#814 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🏰 citadel

#802 ColladaExporter, export submesh selected
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  test/integration/collada_world_exporter.cc
  test/worlds/models/mesh_with_submeshes/model.sdf
Labels: 🏢 edifice

#816 Wireframe mode
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/rendering/RenderUtil.cc
Labels: GUI, rendering, 🏯 fortress

#728 Adding HaltMotion (Or new suggested name) to physics plugin
  include/ignition/gazebo/components/HaltMotion.hh
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.hh
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/halt_motion.cc
Labels: 🔮 dome

#828 3 to 4 2021 05 20
  .github/workflows/ci.yml
  CMakeLists.txt
  include/ignition/gazebo/EntityComponentManager.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cppcheck_rules/header_guard.rule
  tools/cppcheck_rules/namespace_AZ.rule
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🔮 dome

#829 Prepare for 4.9.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#800 Adds support for ocean currents
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  tutorials.md.in
  tutorials/underwater_vehicles.md
Labels: 🏢 edifice

#823 Update collision visualization to support nested models
  src/rendering/RenderUtil.cc
Labels: 🏢 edifice

#830 Make halt motion act like a brake
  src/systems/physics/Physics.cc
Labels: 🔮 dome

#815 Add view control gui plugin and support orthographic view
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: 🏯 fortress

#831 4.9.1 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#825 Use moveToHelper from ign-rendering
  src/gui/plugins/scene3d/Scene3D.cc
Labels: enhancement, needs upstream release, 🏰 citadel

#834 Remove unused headers in video_recoder plugin
  src/gui/plugins/video_recorder/VideoRecorder.cc
Labels: enhancement, 🏰 citadel

#819 Removed duplicated code with rendering::sceneFromFirstRenderEngine
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
Labels: enhancement, needs upstream release, 🏰 citadel

#836 5 ➡️ 6
  src/rendering/RenderUtil.cc
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  tutorials.md.in
  tutorials/underwater_vehicles.md
Labels: 🏢 edifice

#774 Fix race condition when rendering the UI
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: 🏢 edifice

#838 Cleanup and alphabetize plugin headers
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/align_tool/AlignTool.hh
  src/gui/plugins/grid_config/GridConfig.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/transform_control/TransformControl.cc
Labels: enhancement, 🏰 citadel
