Repository gazebosim/gz-sim, pull requests merged in 2021-03, with the labels that each got.

#656 Cache top level and static to speed up physics system
  src/systems/physics/Physics.cc
Labels: performance, 🔮 dome

#586 Use a custom data structure to manage entity feature maps
  src/systems/physics/CMakeLists.txt
  src/systems/physics/EntityFeatureMap.hh
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🏰 citadel

#658 3 ➡️ 4
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/GuiRunner.cc
  src/systems/physics/CMakeLists.txt
  src/systems/physics/EntityFeatureMap.hh
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/scene_broadcaster/SceneBroadcaster.hh
Labels: 🔮 dome

#660 4.6.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#664 Update links v3 -> v4
  tutorials/resources.md
Labels: documentation, 🔮 dome

#668 4 ➡️ 5
  Changelog.md
  include/ignition/gazebo/gui/GuiRunner.hh
  src/gui/GuiRunner.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/particle_emitter/ParticleEmitter.cc
  src/systems/performer_detector/PerformerDetector.cc
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/CMakeLists.txt
  src/systems/physics/EntityFeatureMap.hh
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/scene_broadcaster/SceneBroadcaster.hh
  test/integration/components.cc
  test/integration/particle_emitter.cc
  test/integration/performer_detector.cc
  tutorials/resources.md
Labels: 🏢 edifice

#662 Check empty world name in Scene3d
  src/gui/plugins/scene3d/Scene3D.cc
Labels: GUI, 🔮 dome

#669 Cache link poses to improve performance
  src/systems/physics/Physics.cc
Labels: performance, 🔮 dome

#666 Backport #561: Use common::setenv
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/Util.cc
  src/gui/Gui_TEST.cc
  src/ign_TEST.cc
  src/network/PeerTracker_TEST.cc
  test/integration/air_pressure_system.cc
  test/integration/altimeter_system.cc
  test/integration/apply_joint_force_system.cc
  test/integration/battery_plugin.cc
  test/integration/breadcrumbs.cc
  test/integration/buoyancy.cc
  test/integration/camera_video_record_system.cc
  test/integration/contact_system.cc
  test/integration/depth_camera.cc
  test/integration/detachable_joint.cc
  test/integration/diff_drive_system.cc
  test/integration/each_new_removed.cc
  test/integration/entity_erase.cc
  test/integration/events.cc
  test/integration/examples_build.cc
  test/integration/gpu_lidar.cc
  test/integration/imu_system.cc
  test/integration/joint_controller_system.cc
  test/integration/joint_position_controller_system.cc
  test/integration/joint_state_publisher_system.cc
  test/integration/level_manager.cc
  test/integration/level_manager_runtime_performers.cc
  test/integration/lift_drag_system.cc
  test/integration/link.cc
  test/integration/log_system.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/logical_camera_system.cc
  test/integration/magnetometer_system.cc
  test/integration/model.cc
  test/integration/multicopter.cc
  test/integration/performer_detector.cc
  test/integration/physics_system.cc
  test/integration/pose_publisher_system.cc
  test/integration/rgbd_camera.cc
  test/integration/save_world.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sdf_frame_semantics.cc
  test/integration/sensors_system.cc
  test/integration/thermal_system.cc
  test/integration/touch_plugin.cc
  test/integration/triggered_publisher.cc
  test/integration/user_commands.cc
  test/integration/velocity_control_system.cc
  test/integration/wheel_slip.cc
  test/integration/wind_effects.cc
  test/integration/world.cc
  test/performance/level_manager.cc
  test/test_config.hh.in
Labels: Windows, 🏰 citadel

#672 Master branch updates
  .github/workflows/ci.yml
  README.md
  doc/architecture_design.md
  examples/standalone/joy_to_twist/README.md
  examples/standalone/joystick/README.md
  test/integration/examples_build.cc
  tutorials/distributed_simulation.md
  tutorials/resources.md
Labels: 🏰 citadel

#673 Fix entity tree for large worlds
  src/gui/plugins/entity_tree/EntityTree.cc
Labels: GUI, bug, 🏰 citadel

#675 Remove bounding box when model is deleted
  src/rendering/RenderUtil.cc
Labels: GUI, bug, rendering, 🔮 dome

#670 Add light intensity field to ComponentInspector
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/plotting/Plotting.cc
  src/rendering/RenderUtil.cc
  src/systems/user_commands/UserCommands.cc
Labels: rendering, 🏢 edifice

#542 Support SDFormat 1.8 Composition
  src/SdfEntityCreator.cc
  src/rendering/RenderUtil.cc
  test/integration/CMakeLists.txt
  test/integration/nested_model_physics.cc
  test/integration/physics_system.cc
  test/integration/sdf_frame_semantics.cc
  test/worlds/include_connected_nested_models.sdf
  test/worlds/include_nested_models.sdf
  test/worlds/models/connected_nested_models/model.config
  test/worlds/models/connected_nested_models/model.sdf
  test/worlds/models/include_connected_nested/model.config
  test/worlds/models/include_connected_nested/model.sdf
  test/worlds/models/include_nested/model.config
  test/worlds/models/include_nested/model.sdf
  test/worlds/models/nested_models/model.config
  test/worlds/models/nested_models/model.sdf
Labels: 🏢 edifice

#671 Depend on cli component of ignition-utils1
  .github/ci/packages.apt
  CMakeLists.txt
  Migration.md
Labels: 🏢 edifice

#588 Added screenshot to toolbar
  CMakeLists.txt
  src/gui/gui.config
Labels: 🏰 citadel

#665 Remove visibility from headers that are not installed
  src/Conversions.cc
  src/gui/AboutDialogHandler.hh
  src/gui/GuiFileHandler.hh
  src/gui/PathManager.hh
  src/network/NetworkConfig.hh
  src/network/NetworkManager.hh
  src/network/NetworkManagerPrimary.hh
  src/network/NetworkManagerPrivate.hh
  src/network/NetworkManagerSecondary.hh
  src/network/PeerInfo.hh
  src/network/PeerTracker.hh
  src/systems/air_pressure/AirPressure.hh
  src/systems/altimeter/Altimeter.hh
  src/systems/apply_joint_force/ApplyJointForce.hh
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/buoyancy/Buoyancy.hh
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/contact/Contact.hh
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/diff_drive/DiffDrive.hh
  src/systems/diff_drive/SpeedLimiter.hh
  src/systems/imu/Imu.hh
  src/systems/joint_controller/JointController.hh
  src/systems/joint_position_controller/JointPositionController.hh
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/lift_drag/LiftDrag.hh
  src/systems/log/LogPlayback.hh
  src/systems/log/LogRecord.hh
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/logical_camera/LogicalCamera.hh
  src/systems/magnetometer/Magnetometer.hh
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/multicopter_motor_model/MulticopterMotorModel.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.hh
  src/systems/pose_publisher/PosePublisher.hh
  src/systems/scene_broadcaster/SceneBroadcaster.hh
  src/systems/sensors/Sensors.hh
  src/systems/thermal/Thermal.hh
  src/systems/touch_plugin/TouchPlugin.hh
  src/systems/triggered_publisher/TriggeredPublisher.hh
  src/systems/user_commands/UserCommands.hh
  src/systems/velocity_control/VelocityControl.hh
  src/systems/wheel_slip/WheelSlip.hh
  src/systems/wind_effects/WindEffects.hh
Labels: Windows, 🏰 citadel

#618 Ackermann Steering Plugin
  examples/worlds/ackermann_steering.sdf
  src/systems/CMakeLists.txt
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/ackermann_steering/CMakeLists.txt
  src/systems/ackermann_steering/SpeedLimiter.cc
  src/systems/ackermann_steering/SpeedLimiter.hh
  test/integration/CMakeLists.txt
  test/integration/ackermann_steering_system.cc
  test/worlds/ackermann_steering.sdf
  test/worlds/ackermann_steering_custom_frame_id.sdf
  test/worlds/ackermann_steering_custom_topics.sdf
  test/worlds/ackermann_steering_limited_joints_pub.sdf
  test/worlds/ackermann_steering_slow_odom.sdf
Labels: enhancement, 🔮 dome

#534 Add joint position controller GUI, also enable tests for GUI plugins
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/joint_position_controller/CMakeLists.txt
  src/gui/plugins/joint_position_controller/Joint.qml
  src/gui/plugins/joint_position_controller/JointPositionController.cc
  src/gui/plugins/joint_position_controller/JointPositionController.hh
  src/gui/plugins/joint_position_controller/JointPositionController.qml
  src/gui/plugins/joint_position_controller/JointPositionController.qrc
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/systems/physics/Physics.cc
Labels: GUI, close the gap, tests, 🏰 citadel

#688 🎈 3.8.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#689 3 to 4
  src/Conversions.cc
  src/gui/AboutDialogHandler.hh
  src/gui/GuiFileHandler.hh
  src/gui/PathManager.hh
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/joint_position_controller/CMakeLists.txt
  src/gui/plugins/joint_position_controller/Joint.qml
  src/gui/plugins/joint_position_controller/JointPositionController.cc
  src/gui/plugins/joint_position_controller/JointPositionController.hh
  src/gui/plugins/joint_position_controller/JointPositionController.qml
  src/gui/plugins/joint_position_controller/JointPositionController.qrc
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/network/NetworkConfig.hh
  src/network/NetworkManager.hh
  src/network/NetworkManagerPrimary.hh
  src/network/NetworkManagerPrivate.hh
  src/network/NetworkManagerSecondary.hh
  src/network/PeerInfo.hh
  src/network/PeerTracker.hh
  src/systems/air_pressure/AirPressure.hh
  src/systems/altimeter/Altimeter.hh
  src/systems/apply_joint_force/ApplyJointForce.hh
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/buoyancy/Buoyancy.hh
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/contact/Contact.hh
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/diff_drive/DiffDrive.hh
  src/systems/diff_drive/SpeedLimiter.hh
  src/systems/imu/Imu.hh
  src/systems/joint_controller/JointController.hh
  src/systems/joint_position_controller/JointPositionController.hh
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/lift_drag/LiftDrag.hh
  src/systems/log/LogPlayback.hh
  src/systems/log/LogRecord.hh
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/logical_camera/LogicalCamera.hh
  src/systems/magnetometer/Magnetometer.hh
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/multicopter_motor_model/MulticopterMotorModel.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  src/systems/pose_publisher/PosePublisher.hh
  src/systems/scene_broadcaster/SceneBroadcaster.hh
  src/systems/sensors/Sensors.hh
  src/systems/thermal/Thermal.hh
  src/systems/touch_plugin/TouchPlugin.hh
  src/systems/triggered_publisher/TriggeredPublisher.hh
  src/systems/user_commands/UserCommands.hh
  src/systems/velocity_control/VelocityControl.hh
  src/systems/wheel_slip/WheelSlip.hh
  src/systems/wind_effects/WindEffects.hh
Labels: 🔮 dome

#696 Quiet warnings from Joint State Publisher
  src/systems/joint_state_publisher/JointStatePublisher.cc
Labels: 🔮 dome

#635 Remove static for maps from Factory.hh
  include/ignition/gazebo/components/Factory.hh
Labels: beta, 🏢 edifice

#697 Fix joint controller GUI test
  src/gui/plugins/joint_position_controller/JointPositionController.cc
Labels: GUI, bug, tests, 🔮 dome

#693 Setting the intiial velocity for a model or joint
  examples/worlds/joint_controller.sdf
  examples/worlds/velocity_control.sdf
  src/systems/joint_controller/JointController.cc
  src/systems/joint_controller/JointController.hh
  src/systems/velocity_control/VelocityControl.cc
  src/systems/velocity_control/VelocityControl.hh
  test/integration/joint_controller_system.cc
  test/integration/velocity_control_system.cc
  test/worlds/joint_controller.sdf
  test/worlds/velocity_control.sdf
Labels: beta, 🏢 edifice

#690 [BULLET] Making GetContactsFromLastStepFeature optional in Collision Features
  src/systems/physics/Physics.cc
Labels: enhancement, physics, 🔮 dome

#695 4 ➡️ 5
  .github/workflows/ci.yml
  README.md
  doc/architecture_design.md
  examples/standalone/joy_to_twist/README.md
  examples/standalone/joystick/README.md
  examples/worlds/ackermann_steering.sdf
  src/gui/gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/entity_tree/EntityTree.cc
  src/gui/plugins/joint_position_controller/CMakeLists.txt
  src/gui/plugins/joint_position_controller/Joint.qml
  src/gui/plugins/joint_position_controller/JointPositionController.cc
  src/gui/plugins/joint_position_controller/JointPositionController.hh
  src/gui/plugins/joint_position_controller/JointPositionController.qml
  src/gui/plugins/joint_position_controller/JointPositionController.qrc
  src/gui/plugins/joint_position_controller/JointPositionController_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/ackermann_steering/CMakeLists.txt
  src/systems/ackermann_steering/SpeedLimiter.cc
  src/systems/ackermann_steering/SpeedLimiter.hh
  src/systems/physics/Physics.cc
  src/systems/velocity_control/VelocityControl.hh
  test/integration/CMakeLists.txt
  test/integration/ackermann_steering_system.cc
  test/integration/examples_build.cc
  test/integration/thermal_sensor_system.cc
  test/worlds/ackermann_steering.sdf
  test/worlds/ackermann_steering_custom_frame_id.sdf
  test/worlds/ackermann_steering_custom_topics.sdf
  test/worlds/ackermann_steering_limited_joints_pub.sdf
  test/worlds/ackermann_steering_slow_odom.sdf
  tutorials/collada_world_exporter.md
  tutorials/distributed_simulation.md
  tutorials/mesh_to_fuel.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/migration_plugins.md
  tutorials/migration_sdf.md
  tutorials/point_cloud_to_mesh.md
  tutorials/resources.md
Labels: beta, 🏢 edifice

#698 Scenebroadcaster sensors
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/altimeter_with_pose.sdf
Labels: enhancement, 🔮 dome

#703 Fixed material colors for Ackermann SDF files
  examples/worlds/ackermann_steering.sdf
  test/worlds/ackermann_steering.sdf
  test/worlds/ackermann_steering_custom_frame_id.sdf
  test/worlds/ackermann_steering_custom_topics.sdf
  test/worlds/ackermann_steering_limited_joints_pub.sdf
  test/worlds/ackermann_steering_slow_odom.sdf
Labels: beta, bug, 🏢 edifice

#702 Fixed collision visual bounding boxes
  src/rendering/RenderUtil.cc
Labels: GUI, beta, bug, rendering, 🏢 edifice

#683 Mecanum wheels demo
  CMakeLists.txt
  examples/worlds/mecanum_drive.sdf
  examples/worlds/skid_steer_mecanum.sdf
  src/systems/CMakeLists.txt
  src/systems/mecanum_drive/CMakeLists.txt
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/mecanum_drive/MecanumDrive.hh
Labels: beta, enhancement, needs upstream release, 🏢 edifice

#685 Support individual canonical links for nested models
  include/ignition/gazebo/SdfEntityCreator.hh
  include/ignition/gazebo/components/CanonicalLink.hh
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/worlds/nested_model_canonical_link.sdf
Labels: beta, enhancement, 🏢 edifice

#621 Add thermal camera test for object temperature below 0
  CMakeLists.txt
  test/integration/thermal_sensor_system.cc
  test/worlds/thermal_invalid.sdf
Labels: sensors, tests

#581 Added Ellipsoid and Capsule geometries
  examples/standalone/marker/marker.cc
  examples/worlds/rolling_shapes.sdf
  examples/worlds/shapes.sdf
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SdfEntityCreator_TEST.cc
  src/SdfGenerator_TEST.cc
  src/ServerConfig.cc
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/gui/gui.config
  src/gui/plugins/shapes/Shapes.cc
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/capsule.png
  src/gui/plugins/shapes/ellipsoid.png
  src/rendering/MarkerManager.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.hh
  test/integration/entity_erase.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/user_commands.cc
  test/worlds/shapes.sdf
Labels: beta, 🏢 edifice

#707 Fix diffuse and ambient values for ackermann example
  examples/worlds/ackermann_steering.sdf
Labels: 🔮 dome

#708 🎈 5.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#710 entity creation tutorial snippets fix
  tutorials/entity_creation.md
Labels: 🏢 edifice

#719 Add UserCommands Plugin.
  examples/worlds/fuel.sdf
Labels: 🏢 edifice

#718 Respect spotlight direction
  Migration.md
  src/rendering/SceneManager.cc
Labels: beta, bug, 🏢 edifice

#723 Replace deprecated function FreeGroup::CanonicalLink with FreeGroup::RootLink
  src/systems/physics/Physics.cc
Labels: beta, 🏢 edifice

#727 Reorder progress topics instructions in joint_trajectory_controller demo
  examples/worlds/joint_trajectory_controller.sdf
Labels: 🏢 edifice
