Repository gazebosim/gz-sim, pull requests merged in 2022-05, with the labels that each got.

#1463 Fix running simulation with no world specified on the command line
  include/ignition/gazebo/ServerConfig.hh
  src/ServerConfig.cc
Labels: 🏯 fortress

#1466 3 ➡️ 6
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#1454 Skip serializing nested model with //pose/@relative_to attribute
  examples/worlds/sensors_demo.sdf
  include/ignition/gazebo/components/Model.hh
Labels: 🏯 fortress

#1469 Fix finding DART on macOS
  CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🏯 fortress

#1468 Revert sensors demo camera format change
  examples/worlds/sensors_demo.sdf
Labels: 🏯 fortress

#1417 SceneBroadcaster: Use double for state publish frequency instead of int
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🏯 fortress

#1451 Use uint64_t with gazebo-entity user dataa
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/shader_param/ShaderParam.cc
  test/integration/sensors_system.cc
Labels: 🌱 garden

#1445 Test case to check if velocity limits are applied to joints
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/physics_system.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/joint_velocity_limit.sdf
Labels: physics, 🏯 fortress

#1474 Remove dead ign.cc file
  src/cmd/ign.cc
Labels: bug, 🏯 fortress

#1450 Extend Multicoptor Control system to include nested model inertial params
  src/systems/multicopter_control/MulticopterVelocityControl.cc
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  test/integration/multicopter.cc
  test/worlds/quadcopter_velocity_control_nested.sdf
Labels: 🏯 fortress, mbzirc

#1384 Camera trigger integration test
  examples/worlds/triggered_camera_sensor.sdf
  test/integration/CMakeLists.txt
  test/integration/triggered_camera.cc
  test/worlds/triggered_camera_sensor.sdf
Labels: sensors, needs upstream release, 🏯 fortress

#1456 Extruded 2D polyline geometries
  examples/worlds/polylines.sdf
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
Labels: 🏰 citadel, rendering, physics, MBARI buoy

#1327 Implement reset interface in the physics system
  examples/plugin/reset_plugin/CMakeLists.txt
  examples/plugin/reset_plugin/JointPositionRandomizer.cc
  examples/plugin/reset_plugin/README.md
  examples/plugin/reset_plugin/joint_position_randomizer.sdf
  src/EntityComponentManager_TEST.cc
  src/systems/physics/CanonicalLinkModelTracker.hh
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  test/integration/CMakeLists.txt
  test/integration/reset.cc
  test/plugins/MockSystem.cc
  test/plugins/MockSystem.hh
  test/worlds/reset.sdf
Labels: 🌱 garden

#1482 Adding rssi
  src/systems/rf_comms/RFComms.cc
  test/integration/rf_comms.cc
Labels: 🏯 fortress, 🌱 garden, mbzirc

#1495 Makes thruster stop when battery runs out.
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_battery.sdf
Labels: 🏯 fortress

#1502 Updating hydrodynamics plugin description
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
Labels: documentation, 🏯 fortress, MBARI buoy

#1500 Update documentation in the linear battery plugin example.
  examples/worlds/linear_battery_demo.sdf
Labels: documentation, 🌱 garden, MBARI-LRAUV
