Repository gazebosim/gz-sim, pull requests merged in 2022-02, with the labels that each got.

#1315 3 ➡️ 5
  Migration.md
  include/ignition/gazebo/components/CenterOfVolume.hh
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/buoyancy/Buoyancy.cc
  src/systems/imu/Imu.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  test/integration/air_pressure_system.cc
  test/integration/altimeter_system.cc
  test/integration/buoyancy.cc
  test/integration/imu_system.cc
  test/integration/logical_camera_system.cc
  test/integration/magnetometer_system.cc
  test/worlds/center_of_volume.sdf
Labels: 🏢 edifice

#1275 Load and run visual plugin (system) on GUI side
  examples/worlds/shader_param.sdf
  include/ignition/gazebo/components/Visual.hh
  include/ignition/gazebo/gui/GuiEvents.hh
  include/ignition/gazebo/rendering/Events.hh
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/SdfEntityCreator.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/gui/GuiEvents.cc
  src/gui/GuiRunner.cc
  src/gui/GuiRunner.hh
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/rendering/RenderUtil.cc
  src/systems/CMakeLists.txt
  src/systems/sensors/Sensors.cc
  src/systems/shader_param/CMakeLists.txt
  src/systems/shader_param/ShaderParam.cc
  src/systems/shader_param/ShaderParam.hh
  test/integration/CMakeLists.txt
  test/integration/shader_param_system.cc
  test/plugins/CMakeLists.txt
  test/plugins/TestVisualSystem.cc
  test/plugins/TestVisualSystem.hh
  test/worlds/plugins.sdf
Labels: 🏯 fortress

#1318 Limit thruster system's input thrust cmd
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_pid.sdf
  test/worlds/thruster_vel_cmd.sdf
Labels: 🏢 edifice

#1321 Removed unused variables in shapes plugin
  src/gui/plugins/shapes/Shapes.cc
Labels: 🏰 citadel

#535 Add elevator system
  examples/worlds/elevator.sdf
  src/systems/CMakeLists.txt
  src/systems/elevator/CMakeLists.txt
  src/systems/elevator/Elevator.cc
  src/systems/elevator/Elevator.hh
  src/systems/elevator/ElevatorCommonPrivate.hh
  src/systems/elevator/ElevatorStateMachine.hh
  src/systems/elevator/state_machine/ActionsImpl.hh
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/elevator/state_machine/EventsImpl.hh
  src/systems/elevator/state_machine/GuardsImpl.hh
  src/systems/elevator/state_machine/StatesImpl.hh
  src/systems/elevator/utils/DoorTimer.cc
  src/systems/elevator/utils/DoorTimer.hh
  src/systems/elevator/utils/JointMonitor.cc
  src/systems/elevator/utils/JointMonitor.hh
  src/systems/elevator/vender/afsm/LICENSE
  src/systems/elevator/vender/afsm/include/afsm/definition.hpp
  src/systems/elevator/vender/afsm/include/afsm/definition_fwd.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/actions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/base_states.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/debug_io.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/def_traits.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/event_identity.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/exception_safety_guarantees.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/helpers.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/observer.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/orthogonal_regions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/reject_policies.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/tags.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/transitions.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm_fwd.hpp
  src/systems/elevator/vender/metapushkin/LICENSE
  src/systems/elevator/vender/metapushkin/include/pushkin/meta.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/algorithm.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/callable.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/char_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/function_traits.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/functions.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/index_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/integer_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/nth_type.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_map.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/util/demangle.hpp
  test/integration/CMakeLists.txt
  test/integration/elevator_system.cc
  test/worlds/elevator.sdf
Labels: enhancement, 🏰 citadel, close the gap

#1324 [style-fix] Fix weird indentation in `Link.hh`
  include/ignition/gazebo/Link.hh
Labels: 🏯 fortress

#1326 Forward port 4 to 5 Feb 7 2022
  Changelog.md
Labels: 🏢 edifice

#1319 Fix UNIT_SdfGenerator_TEST
  src/SdfGenerator_TEST.cc
Labels: 🏢 edifice

#1322 5 -> 6
  Changelog.md
  Migration.md
  include/ignition/gazebo/components/CenterOfVolume.hh
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/buoyancy/Buoyancy.cc
  src/systems/imu/Imu.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/air_pressure_system.cc
  test/integration/altimeter_system.cc
  test/integration/buoyancy.cc
  test/integration/imu_system.cc
  test/integration/logical_camera_system.cc
  test/integration/magnetometer_system.cc
  test/integration/thruster.cc
  test/worlds/center_of_volume.sdf
  test/worlds/thruster_pid.sdf
  test/worlds/thruster_vel_cmd.sdf
Labels: 🏯 fortress

#1323 Adds a `Link::SetLinearVelocity()` method
  include/ignition/gazebo/Link.hh
  src/Link.cc
  test/integration/link.cc
Labels: 🏯 fortress

#1310 Extend ShaderParam system to support textures
  examples/worlds/shader_param.sdf
  src/systems/shader_param/ShaderParam.cc
Labels: rendering, 🏯 fortress

#1332 New trajectory follower system
  examples/worlds/shader_param.sdf
  examples/worlds/trajectory_follower.sdf
  src/systems/CMakeLists.txt
  src/systems/trajectory_follower/CMakeLists.txt
  src/systems/trajectory_follower/TrajectoryFollower.cc
  src/systems/trajectory_follower/TrajectoryFollower.hh
Labels: 🏯 fortress

#1330 3 -> 5
  examples/worlds/elevator.sdf
  src/gui/plugins/shapes/Shapes.cc
  src/systems/CMakeLists.txt
  src/systems/elevator/CMakeLists.txt
  src/systems/elevator/Elevator.cc
  src/systems/elevator/Elevator.hh
  src/systems/elevator/ElevatorCommonPrivate.hh
  src/systems/elevator/ElevatorStateMachine.hh
  src/systems/elevator/state_machine/ActionsImpl.hh
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/elevator/state_machine/EventsImpl.hh
  src/systems/elevator/state_machine/GuardsImpl.hh
  src/systems/elevator/state_machine/StatesImpl.hh
  src/systems/elevator/utils/DoorTimer.cc
  src/systems/elevator/utils/DoorTimer.hh
  src/systems/elevator/utils/JointMonitor.cc
  src/systems/elevator/utils/JointMonitor.hh
  src/systems/elevator/vender/afsm/LICENSE
  src/systems/elevator/vender/afsm/include/afsm/definition.hpp
  src/systems/elevator/vender/afsm/include/afsm/definition_fwd.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/actions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/base_states.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/debug_io.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/def_traits.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/event_identity.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/exception_safety_guarantees.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/helpers.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/observer.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/orthogonal_regions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/reject_policies.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/tags.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/transitions.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm_fwd.hpp
  src/systems/elevator/vender/metapushkin/LICENSE
  src/systems/elevator/vender/metapushkin/include/pushkin/meta.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/algorithm.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/callable.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/char_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/function_traits.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/functions.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/index_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/integer_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/nth_type.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_map.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/util/demangle.hpp
  test/integration/CMakeLists.txt
  test/integration/elevator_system.cc
  test/worlds/elevator.sdf
Labels: 🏢 edifice

#1338 Prepare for releasing 6.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1337 Fixed light gui component inspector
  src/gui/plugins/component_inspector/Light.qml
  src/rendering/RenderUtil.cc
Labels: 🏢 edifice

#1339 5 -> 6
  examples/worlds/elevator.sdf
  src/gui/plugins/shapes/Shapes.cc
  src/systems/CMakeLists.txt
  src/systems/elevator/CMakeLists.txt
  src/systems/elevator/Elevator.cc
  src/systems/elevator/Elevator.hh
  src/systems/elevator/ElevatorCommonPrivate.hh
  src/systems/elevator/ElevatorStateMachine.hh
  src/systems/elevator/state_machine/ActionsImpl.hh
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/elevator/state_machine/EventsImpl.hh
  src/systems/elevator/state_machine/GuardsImpl.hh
  src/systems/elevator/state_machine/StatesImpl.hh
  src/systems/elevator/utils/DoorTimer.cc
  src/systems/elevator/utils/DoorTimer.hh
  src/systems/elevator/utils/JointMonitor.cc
  src/systems/elevator/utils/JointMonitor.hh
  src/systems/elevator/vender/afsm/LICENSE
  src/systems/elevator/vender/afsm/include/afsm/definition.hpp
  src/systems/elevator/vender/afsm/include/afsm/definition_fwd.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/actions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/base_states.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/debug_io.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/def_traits.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/event_identity.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/exception_safety_guarantees.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/helpers.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/observer.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/orthogonal_regions.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/reject_policies.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/tags.hpp
  src/systems/elevator/vender/afsm/include/afsm/detail/transitions.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm.hpp
  src/systems/elevator/vender/afsm/include/afsm/fsm_fwd.hpp
  src/systems/elevator/vender/metapushkin/LICENSE
  src/systems/elevator/vender/metapushkin/include/pushkin/meta.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/algorithm.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/callable.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/char_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/function_traits.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/functions.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/index_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/integer_sequence.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/nth_type.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_map.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/meta/type_tuple.hpp
  src/systems/elevator/vender/metapushkin/include/pushkin/util/demangle.hpp
  test/integration/CMakeLists.txt
  test/integration/elevator_system.cc
  test/worlds/elevator.sdf
Labels: 🏯 fortress

#1345 JointStatePublisher publish parent, child and axis data
  src/systems/joint_state_publisher/JointStatePublisher.cc
Labels: 🏰 citadel

#1307 Logs a warning if a buoyancy mode is not clearly specified.
  src/systems/buoyancy/Buoyancy.cc
  test/integration/buoyancy.cc
  test/worlds/center_of_volume_graded.sdf
Labels: 🏯 fortress

#1347 Adding ability to pause/resume the trajectory follower behavior.
  examples/worlds/trajectory_follower.sdf
  src/systems/trajectory_follower/TrajectoryFollower.cc
Labels: 🏯 fortress

#1360 3 -> 5
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
Labels: 🏢 edifice

#1359 5 -> 6
  src/gui/plugins/component_inspector/Light.qml
  src/rendering/RenderUtil.cc
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
Labels: 🏯 fortress

#1342 Support disabling pose publisher from publishing top level model pose
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/pose_publisher/PosePublisher.hh
  test/integration/pose_publisher_system.cc
  test/worlds/nested_model.sdf
Labels: 🏯 fortress

#1349 Add parameter to TrajectoryFollower stop rotation when bearing is reached
  include/ignition/gazebo/Link.hh
  src/Link.cc
  src/systems/physics/Physics.cc
  src/systems/trajectory_follower/TrajectoryFollower.cc
  src/systems/trajectory_follower/TrajectoryFollower.hh
  test/integration/link.cc
Labels: 🏯 fortress

#1366 Fix accessing empty JointPosition component in lift drag plugin
  src/systems/lift_drag/LiftDrag.cc
Labels: 🏯 fortress

#1365 Prepare for 6.6.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1219 Added Python interfaces to some Ignition Gazebo methods
  .github/ci/packages-focal.apt
  .github/ci/packages.apt
  CMakeLists.txt
  examples/scripts/python_api/README.md
  examples/scripts/python_api/gravity.sdf
  examples/scripts/python_api/testFixture.py
  python/CMakeLists.txt
  python/src/ignition/common/Console.cc
  python/src/ignition/common/Console.hh
  python/src/ignition/common/_ignition_common_pybind11.cc
  python/src/ignition/gazebo/EntityComponentManager.cc
  python/src/ignition/gazebo/EntityComponentManager.hh
  python/src/ignition/gazebo/EventManager.cc
  python/src/ignition/gazebo/EventManager.hh
  python/src/ignition/gazebo/Server.cc
  python/src/ignition/gazebo/Server.hh
  python/src/ignition/gazebo/ServerConfig.cc
  python/src/ignition/gazebo/ServerConfig.hh
  python/src/ignition/gazebo/TestFixture.cc
  python/src/ignition/gazebo/TestFixture.hh
  python/src/ignition/gazebo/UpdateInfo.cc
  python/src/ignition/gazebo/UpdateInfo.hh
  python/src/ignition/gazebo/Util.cc
  python/src/ignition/gazebo/Util.hh
  python/src/ignition/gazebo/World.cc
  python/src/ignition/gazebo/World.hh
  python/src/ignition/gazebo/_ignition_gazebo_pybind11.cc
  python/src/ignition/gazebo/wrap_functions.hh
  python/src/ignition/sdformat/Element.cc
  python/src/ignition/sdformat/Element.hh
  python/src/ignition/sdformat/_sdformat_pybind11.cc
  python/test/gravity.sdf
  python/test/testFixture_TEST.py
  tutorials.md.in
  tutorials/python_interfaces.md
Labels: enhancement, needs upstream release, 🏯 fortress, scripting

#1340 Refactor System functionality into SystemManager
  src/CMakeLists.txt
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
  src/WorldControl.hh
Labels: 🌱 garden

#1351 Populate names of colliding entities in contact points message
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  test/integration/contact_system.cc
  test/worlds/contact_with_entity_names.sdf
  test/worlds/contact_without_entity_names.sdf
Labels: 🏯 fortress
