Repository gazebosim/gz-sim, pull requests merged in 2022-04, with the labels that each got.

#1333 ServerConfig accepts an sdf::Root DOM object
  include/ignition/gazebo/ServerConfig.hh
  include/ignition/gazebo/Util.hh
  src/Server.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/Server_TEST.cc
  src/Util.cc
  src/Util_TEST.cc
Labels: needs upstream release, 🏯 fortress

#1422 5 ➡️ 6
  Changelog.md
  examples/worlds/model_photo_shoot.sdf
  include/ignition/gazebo/components/WheelSlipCmd.hh
  src/systems/CMakeLists.txt
  src/systems/model_photo_shoot/CMakeLists.txt
  src/systems/model_photo_shoot/ModelPhotoShoot.cc
  src/systems/model_photo_shoot/ModelPhotoShoot.hh
  src/systems/user_commands/UserCommands.cc
  src/systems/wheel_slip/WheelSlip.cc
  test/integration/CMakeLists.txt
  test/integration/ModelPhotoShootTest.hh
  test/integration/model_photo_shoot_default_joints.cc
  test/integration/model_photo_shoot_random_joints.cc
  test/integration/user_commands.cc
  test/worlds/model_photo_shoot_random_joints.sdf
  tutorials.md.in
  tutorials/model_photo_shoot.md
Labels: 🏯 fortress

#1425 Preparing 6.8.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1393 Add Gaussian noise to Odometry Publisher
  CMakeLists.txt
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  test/integration/odometry_publisher.cc
  test/worlds/odometry_noise.sdf
Labels: 🏯 fortress

#1317 Fix segfault at exit
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/detail/BaseView.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  include/ignition/gazebo/detail/View.hh
  src/BaseView.cc
  src/BaseView_TEST.cc
  src/CMakeLists.txt
  src/View.cc
  src/gui/CMakeLists.txt
  src/gui/Gui_clean_exit_TEST.cc
Labels: 🏯 fortress

#1411 Add desktop entry and svg logo
  CMakeLists.txt
  tools/desktop/ignition-gazebo.desktop.in
  tools/desktop/ignition-gazebo.svg
Labels: 🏰 citadel, OOBE 📦✨

#1426 Fix faulty assumption in INTEGRATION_log_system
  test/integration/log_system.cc
Labels: 🌱 garden

#1357 Make WindEffects configurable on a location basis
  src/systems/wind_effects/WindEffects.cc
  src/systems/wind_effects/WindEffects.hh
  test/integration/wind_effects.cc
  test/worlds/sea_storm_effects.sdf
Labels: 🌱 garden, MBARI-LRAUV

#1427 Supply world frame orientation and heading to IMU sensor : DCO fix
  src/systems/imu/Imu.cc
  test/integration/imu_system.cc
  test/worlds/imu_heading_deg.sdf
  test/worlds/imu_named_frame.sdf
  test/worlds/imu_rotating_demo.sdf
Labels: 🏯 fortress

#1430 Use versioned svg file
  CMakeLists.txt
  tools/desktop/ignition-gazebo.desktop.in
  tools/desktop/ignition-gazebo.svg.in
Labels: 🏰 citadel

#1432 Removed screenToPlane method and use rendering::screenToPlane from Spawn plugin
  src/gui/plugins/spawn/Spawn.cc
Labels: 🏯 fortress

#1436 Replace deprecated common::SubMesh::MaterialIndex() with GetMaterialIndex()
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
Labels: 🌱 garden

#1440 remove unused `View::Clone` method
  include/ignition/gazebo/detail/BaseView.hh
  include/ignition/gazebo/detail/View.hh
Labels: 🌱 garden

#1438 3 ➡️ 6
  CMakeLists.txt
  tools/desktop/ignition-gazebo.desktop.in
  tools/desktop/ignition-gazebo.svg.in
Labels: 🏯 fortress

#1441 Cherry-Pick #1317: Fix segfault at exit
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/detail/BaseView.hh
  include/ignition/gazebo/detail/EntityComponentManager.hh
  include/ignition/gazebo/detail/View.hh
  src/BaseView.cc
  src/BaseView_TEST.cc
  src/CMakeLists.txt
  src/View.cc
  src/gui/CMakeLists.txt
  src/gui/Gui_clean_exit_TEST.cc
Labels: 🌱 garden

#1416 Add comms infrastructure
  examples/standalone/comms/CMakeLists.txt
  examples/standalone/comms/publisher.cc
  examples/worlds/perfect_comms.sdf
  include/ignition/gazebo/comms/Broker.hh
  include/ignition/gazebo/comms/ICommsModel.hh
  include/ignition/gazebo/comms/MsgManager.hh
  src/CMakeLists.txt
  src/comms/Broker.cc
  src/comms/Broker_TEST.cc
  src/comms/ICommsModel.cc
  src/comms/MsgManager.cc
  src/comms/MsgManager_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/comms_endpoint/CMakeLists.txt
  src/systems/comms_endpoint/CommsEndpoint.cc
  src/systems/comms_endpoint/CommsEndpoint.hh
  src/systems/perfect_comms/CMakeLists.txt
  src/systems/perfect_comms/PerfectComms.cc
  src/systems/perfect_comms/PerfectComms.hh
  test/integration/CMakeLists.txt
  test/integration/perfect_comms.cc
Labels: needs upstream release, 🏯 fortress, mbzirc

#1439 🎈 6.9.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1447 Remove internal python bindings for sdformat
  python/CMakeLists.txt
  python/src/ignition/gazebo/wrap_functions.hh
  python/src/ignition/sdformat/Element.cc
  python/src/ignition/sdformat/Element.hh
  python/src/ignition/sdformat/_sdformat_pybind11.cc
  python/test/testFixture_TEST.py
Labels: 🌱 garden

#1379 Updated test for libsdformat behavior change
  src/SdfGenerator_TEST.cc
Labels: needs upstream release, 🌱 garden

#1448 Tweaks to python docs
  examples/scripts/python_api/testFixture.py
  python/CMakeLists.txt
  python/test/testFixture_TEST.py
  tutorials/python_interfaces.md
Labels: scripting, 🌱 garden

#1453 Use message field visualize_visual
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/rendering/RenderUtil.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: 🌱 garden

#1415 Set simulation time to Rendering
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
Labels: rendering, needs upstream release, 🏯 fortress

#1452 Improve contact sensor / visualization performance
  src/systems/physics/EntityFeatureMap.hh
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
Labels: 🏯 fortress, mbzirc

#1449 Used Light ign-msgs is_light_off
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/rendering/RenderUtil.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: 🌱 garden

#1455 Bump rendering dependency version
  CMakeLists.txt
Labels: 🏯 fortress

#1459 python: remove semicolons
  examples/scripts/python_api/testFixture.py
  python/test/testFixture_TEST.py
Labels: 🏯 fortress

#1461 Add repo specific issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏰 citadel
