Repository gazebosim/gz-sim, pull requests merged in 2022-06, with the labels that each got.

#1404 System inspector GUI widget
  include/ignition/gazebo/Conversions.hh
  include/ignition/gazebo/components/SystemPluginInfo.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/ExpandingTypeHeader.qml
  src/gui/plugins/component_inspector/SystemPluginInfo.cc
  src/gui/plugins/component_inspector/SystemPluginInfo.hh
  src/gui/plugins/component_inspector/SystemPluginInfo.qml
  src/gui/plugins/component_inspector/TypeHeader.qml
  src/gui/plugins/component_inspector_editor/Pose3d.qml
Labels: GUI, 🏯 fortress, OOBE 📦✨

#1512 🎈 3.13.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#1470 Add new GZ_GUI_RESOURCE_PATH to help message
  src/cmd/cmdgazebo.rb.in
Labels: 🏰 citadel, OOBE 📦✨

#1518 ign -> gz Environment Variable Migration : gz-sim
  Migration.md
  docker/run.bash
  examples/plugin/command_actor/README.md
  examples/plugin/custom_component/README.md
  examples/plugin/custom_sensor_system/README.md
  examples/plugin/hello_world/README.md
  examples/plugin/rendering_plugins/README.md
  examples/plugin/reset_plugin/README.md
  include/gz/sim/ServerConfig.hh
  include/gz/sim/Util.hh
  include/gz/sim/components/Factory.hh
  src/CMakeLists.txt
  src/ComponentFactory_TEST.cc
  src/Component_TEST.cc
  src/Conversions.cc
  src/ServerConfig.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/SystemLoader.cc
  src/Util.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/Gui_TEST.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/ign_TEST.cc
  src/network/PeerTracker_TEST.cc
  src/rendering/RenderUtil.cc
  src/systems/physics/Physics.cc
  test/helpers/EnvTestFixture.hh
  test/integration/collada_world_exporter.cc
  test/integration/elevator_system.cc
  test/integration/fuel_cached_server.cc
  test/integration/lift_drag_system.cc
  test/integration/log_system.cc
  test/integration/nested_model_physics.cc
  test/integration/physics_system.cc
  test/integration/save_world.cc
  test/integration/sdf_frame_semantics.cc
  test/integration/tracked_vehicle_system.cc
  test/performance/level_manager.cc
  test/worlds/lift_drag_nested_model.sdf
  tutorials/migration_sdf.md
  tutorials/physics.md
  tutorials/resources.md
  tutorials/server_config.md
Labels: 🌱 garden, ign to gz

#1475 Allow rendering to be forced externally
  include/gz/sim/rendering/Events.hh
  src/systems/sensors/Sensors.cc
  tutorials/rendering_plugins.md
Labels: rendering, 🌱 garden, MBARI-LRAUV

#1504 Bash completion for flags
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/gazebo.bash_completion.sh
  src/cmd/model.bash_completion.sh
  src/ign_TEST.cc
Labels: 🏰 citadel, OOBE 📦✨

#1538 Fix locks in Visualize Lidar GUI plugin
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: bug, GUI, 🏯 fortress

#1534 Odometry publisher: also publish Pose_V (TF)
  examples/worlds/multicopter_velocity_control.sdf
  src/systems/diff_drive/DiffDrive.hh
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  test/integration/odometry_publisher.cc
Labels: enhancement, 🏯 fortress, MBARI buoy

#1542 [ign -> gz] CMake functions
  CMakeLists.txt
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/plugin/hello_world/CMakeLists.txt
  include/gz/sim/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/gazebo.yaml.in
  src/cmd/model.yaml.in
  src/gui/CMakeLists.txt
  src/gui/plugins/CMakeLists.txt
  src/rendering/CMakeLists.txt
  src/systems/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/CMakeLists.txt
  src/systems/physics/CMakeLists.txt
  test/benchmark/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#1503 Add QML Debugging support
  src/ign.cc
Labels: GUI, 🌱 garden

#1539 Expose rendering teardown event
  include/gz/sim/rendering/Events.hh
  src/systems/sensors/Sensors.cc
Labels: rendering, 🌱 garden, MBARI-LRAUV

#1547 Merge ign-gazebo3 ➡️ ign-gazebo6
  CMakeLists.txt
  Changelog.md
  src/cmd/CMakeLists.txt
  src/cmd/cmdgazebo.rb.in
  src/cmd/gazebo.bash_completion.sh
  src/cmd/model.bash_completion.sh
  src/ign_TEST.cc
  test/integration/log_system.cc
Labels: 🏯 fortress

#1545 Disable MacOS flakies Citadel
  src/Server_TEST.cc
  src/network/PeerTracker_TEST.cc
  test/integration/altimeter_system.cc
  test/integration/diff_drive_system.cc
  test/integration/level_manager.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/network_handshake.cc
  test/integration/performer_detector.cc
  test/integration/pose_publisher_system.cc
  test/integration/touch_plugin.cc
  test/integration/velocity_control_system.cc
Labels: 🏰 citadel, tests, macOS

#1516 Added particle emitters to scene broadcaster
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/particle_emitter2.sdf
Labels: 🏯 fortress

#1299 Fix Protobuf Windows warnings on ign-gazebo6
  include/ignition/gazebo/components/Serialization.hh
  src/CMakeLists.txt
  src/gui/plugins/CMakeLists.txt
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/physics/CMakeLists.txt
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/scene_broadcaster_system.cc
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: Windows, 🏯 fortress

#1551 Expose the ability to stop a server
  include/ignition/gazebo/Server.hh
  src/Server.cc
  src/Server_TEST.cc
Labels: 🏯 fortress

#1552 🎈 6.10.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1557 Detect gz program instead of using CMake module to check for gz-tools
  .github/ci/after_make.sh
  CMakeLists.txt
  src/CMakeLists.txt
  src/ModelCommandAPI_TEST.cc
  src/gz_TEST.cc
  test/integration/CMakeLists.txt
Labels: bug, 🌱 garden

#1558 ign -> gz Partial Docs Migration and Project Name Followups : gz-sim
  .github/ISSUE_TEMPLATE/bug_report.md
  CMakeLists.txt
  Changelog.md
  Migration.md
  README.md
  examples/plugin/command_actor/README.md
  examples/plugin/custom_component/README.md
  examples/plugin/custom_sensor_system/README.md
  examples/plugin/gui_system_plugin/README.md
  examples/plugin/hello_world/README.md
  examples/plugin/rendering_plugins/README.md
  examples/scripts/log_video_recorder/README.md
  examples/standalone/custom_server/README.md
  examples/standalone/external_ecm/README.md
  examples/standalone/joy_to_twist/README.md
  examples/standalone/joystick/README.md
  examples/standalone/keyboard/README.md
  examples/worlds/multi_lrauv_race.sdf
  examples/worlds/perfect_comms.sdf
  examples/worlds/rf_comms.sdf
  include/gz/sim/config.hh.in
  src/CMakeLists.txt
  src/ModelCommandAPI_TEST.cc
  src/SimulationRunner.cc
  src/Util.cc
  src/gui/GuiFileHandler.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/CMakeLists.txt
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/imu/Imu.cc
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/navsat/NavSat.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/thermal_sensor_system.cc
  tutorials/battery.md
  tutorials/distributed_simulation.md
  tutorials/install.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/physics.md
  tutorials/test_fixture.md
Labels: 🌱 garden, ign to gz

#1355 Implement system Reset interface for Sensors and SceneBroadcaster
  src/SimulationRunner.cc
  src/SystemInternal.hh
  src/SystemLoader.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/rendering/RenderUtil.cc
  src/systems/log/LogPlayback.cc
  src/systems/log/LogPlayback.hh
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/scene_broadcaster/SceneBroadcaster.hh
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  test/integration/CMakeLists.txt
  test/integration/reset.cc
  test/integration/reset_sensors.cc
  test/worlds/reset.sdf
  test/worlds/reset_sensors.sdf
Labels: 🌱 garden
