Repository gazebosim/gz-sim, pull requests merged in 2022-07, with the labels that each got.

#1568 Refactor: Utilizes function to load animations
  include/ignition/gazebo/rendering/SceneManager.hh
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#1577 Fix UNIT_Server_TEST on Windows
  src/Server_TEST.cc
  src/Util.cc
Labels: tests, Windows, 🏯 fortress

#1578 Garden: ensure targets exist before referencing
  src/gui/plugins/component_inspector_editor/CMakeLists.txt
  src/systems/collada_world_exporter/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: Windows, 🌱 garden

#1535 ign -> gz Shared Lib Migration : gz-sim
  Migration.md
  examples/plugin/custom_sensor_system/odometer.sdf
  examples/scripts/log_video_recorder/log_video_recorder.sdf
  examples/worlds/buoyancy_engine.sdf
  examples/worlds/conveyor.sdf
  examples/worlds/joint_trajectory_controller.sdf
  examples/worlds/mecanum_drive.sdf
  examples/worlds/nested_model.sdf
  examples/worlds/optical_tactile_sensor_plugin.sdf
  examples/worlds/particle_emitter.sdf
  examples/worlds/pendulum_links.sdf
  examples/worlds/plane_propeller_demo.sdf
  examples/worlds/skid_steer_mecanum.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  examples/worlds/triggered_camera_sensor.sdf
  examples/worlds/trisphere_cycle_wheel_slip.sdf
  examples/worlds/tunnel.sdf
  examples/worlds/visualize_contacts.sdf
  examples/worlds/visualize_lidar.sdf
  python/src/gz/sim/Server.cc
  python/src/gz/sim/Server.hh
  python/src/gz/sim/ServerConfig.cc
  python/src/gz/sim/ServerConfig.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
  src/ServerConfig.cc
  src/SystemLoader_TEST.cc
  src/gz_TEST.cc
  src/systems/CMakeLists.txt
  test/integration/components.cc
  test/integration/nested_model_physics.cc
  test/integration/network_handshake.cc
  test/integration/physics_system.cc
  test/integration/sdf_frame_semantics.cc
  test/integration/touch_plugin.cc
  test/test_config.hh.in
  test/worlds/camera_sensor_scene_background.sdf
  test/worlds/nested_model.sdf
  test/worlds/reset_sensors.sdf
  test/worlds/shininess.sdf
  tutorials/gui_config.md
  tutorials/server_config.md
  tutorials/video_recorder.md
Labels: 🌱 garden, ign to gz

#1586 Restore CXX_STANDARD 17 and test gz-cmake PR
  src/CMakeLists.txt
Labels: 🌱 garden

#1571 Implement Pose3d with common widget pose
  src/gui/plugins/component_inspector/Pose3d.qml
Labels: GUI, 🏰 citadel, OOBE 📦✨

#1594 Add Model::CanonicalLink getter
  include/ignition/gazebo/Model.hh
  src/Model.cc
  test/integration/model.cc
Labels: 🏰 citadel, MBARI buoy

#1596 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, QA

#1595 Helper function to get an entity from an entity message
  CMakeLists.txt
  include/ignition/gazebo/Util.hh
  src/Util.cc
  src/Util_TEST.cc
  src/systems/user_commands/UserCommands.cc
Labels: 🏰 citadel, MBARI buoy

#1603 [garden] cherry pick build fix
  test/integration/scene_broadcaster_system.cc
Labels: 🌱 garden

#1528 Use base RenderingSensor::HasConnections function in sensors system
  src/systems/sensors/Sensors.cc
Labels: 🌱 garden

#1401 Tutorial for mesh distortion in Blender Python
  examples/scripts/blender/distort_mesh.py
  tutorials.md.in
  tutorials/blender_distort_meshes.md
  tutorials/files/blender_distort_meshes/Coke_Can_distort_less.png
  tutorials/files/blender_distort_meshes/Coke_Can_distort_less_textured.png
  tutorials/files/blender_distort_meshes/Coke_Can_distort_more.png
  tutorials/files/blender_distort_meshes/Coke_Can_distort_more_textured.png
  tutorials/files/blender_distort_meshes/Coke_Can_distort_most.png
  tutorials/files/blender_distort_meshes/Coke_Can_distort_most_textured.png
  tutorials/files/blender_distort_meshes/Coke_distort_less.png
  tutorials/files/blender_distort_meshes/Coke_distort_more.png
  tutorials/files/blender_distort_meshes/Coke_distort_most.png
Labels: documentation, 🌱 garden

#1590 Update playback_gui.config
  src/gui/playback_gui.config
Labels: GUI, 🏯 fortress

#1602 Merge 3 ➡️ 6 part1
  test/integration/altimeter_system.cc
  test/integration/diff_drive_system.cc
  test/integration/level_manager.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/multiple_servers.cc
  test/integration/network_handshake.cc
  test/integration/performer_detector.cc
  test/integration/pose_publisher_system.cc
  test/integration/touch_plugin.cc
  test/integration/velocity_control_system.cc
Labels: 🏯 fortress

#1569 Implement vector3 with common widget vector3
  CMakeLists.txt
  src/gui/plugins/component_inspector/Vector3d.qml
Labels: GUI, 🏰 citadel, OOBE 📦✨

#1591 ign -> gz Provisional Finale: Source Migration : gz-sim
  src/ComponentFactory_TEST.cc
  src/Component_TEST.cc
  src/EntityComponentManager_TEST.cc
  src/SimulationRunner_TEST.cc
  src/cmd/model.yaml.in
  src/cmd/sim.yaml.in
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Material.qml
  src/gui/plugins/component_inspector/Physics.qml
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/SphericalCoordinates.qml
  src/gui/plugins/component_inspector/Vector3d.qml
  src/gui/plugins/component_inspector_editor/Light.qml
  src/gui/plugins/component_inspector_editor/Material.qml
  src/gui/plugins/component_inspector_editor/Physics.qml
  src/gui/plugins/component_inspector_editor/SphericalCoordinates.qml
  src/gui/plugins/component_inspector_editor/StateAwareSpin.qml
  src/gui/plugins/component_inspector_editor/Vector3d.qml
  src/gui/plugins/joint_position_controller/Joint.qml
  src/gui/plugins/plot_3d/Plot3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/spawn/Spawn.cc
  src/gui/plugins/transform_control/TransformControl.qml
  src/gui/plugins/view_angle/ViewAngle.qml
  src/gui/plugins/visualize_contacts/VisualizeContacts.qml
  src/gui/plugins/visualize_lidar/VisualizeLidar.qml
Labels: 🌱 garden, ign to gz

#1580 Fix component updates
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: bug, 🏯 fortress, OOBE 📦✨

#1606 ign -> gz : Fix Python bindings
  python/src/gz/sim/EntityComponentManager.cc
  python/src/gz/sim/EntityComponentManager.hh
  python/src/gz/sim/EventManager.cc
  python/src/gz/sim/EventManager.hh
  python/src/gz/sim/TestFixture.cc
  python/src/gz/sim/TestFixture.hh
  python/src/gz/sim/UpdateInfo.cc
  python/src/gz/sim/UpdateInfo.hh
  python/src/gz/sim/Util.cc
  python/src/gz/sim/Util.hh
  python/src/gz/sim/World.cc
  python/src/gz/sim/World.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
Labels: bug, 🌱 garden

#1511 Test case for simulation reset with detachable joints
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/reset_detachable_joint.cc
  test/worlds/reset_detachable_joint.sdf
Labels: tests, 🌱 garden

#1523 Don't use 'EachNew' in ForceTorque PreUpdate function
  src/systems/force_torque/ForceTorque.cc
Labels: 🌱 garden

#1576 Add Tf publishing to AckermannSteering system
  .gitignore
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/diff_drive/DiffDrive.hh
  test/integration/ackermann_steering_system.cc
Labels: enhancement, 🏯 fortress

#1593 New Apply Link Wrench system
  examples/worlds/apply_link_wrench.sdf
  src/Util_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.hh
  src/systems/apply_link_wrench/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/apply_link_wrench_system.cc
  test/worlds/apply_link_wrench.sdf
Labels: 🏰 citadel, MBARI buoy

#1604 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  include/ignition/gazebo/config.hh.in
  src/CMakeLists.txt
  src/systems/CMakeLists.txt
  tutorials.md.in
Labels: ign to gz

#1612 Use stepping field in message
  Migration.md
  src/SimulationRunner.cc
Labels: bug, 🌱 garden

#1581 Populate Add System dialog's filename list
  include/ignition/gazebo/SystemLoader.hh
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  test/integration/entity_system.cc
Labels: enhancement, GUI, 🏯 fortress, OOBE 📦✨

#1621 Quiet libSDFormat console on --verbose 0
  src/ign.cc
Labels: 🏰 citadel

#1622 Alternative quick setup menu
  CMakeLists.txt
  examples/worlds/thumbnails/chapulina.Ignition Dome demo.png
  examples/worlds/thumbnails/openrobotics.empty.png
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/config.hh.in
  src/Util.cc
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/Gui_TEST.cc
  src/gui/QuickStartHandler.cc
  src/gui/QuickStartHandler.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/resources/FuelThumbnail.qml
  src/gui/resources/QuickStart.qml
  src/gui/resources/gazebo.qrc
  src/gui/resources/images/gazebo_horz_pos_topbar.svg
  src/gui/resources/images/search.svg
Labels: enhancement, GUI, 🏰 citadel, OOBE 📦✨

#1624 Just the ABI breaking parts of #1560
  src/systems/physics/Physics.cc
Labels: enhancement, 🌱 garden, Breaking change
