Repository gazebosim/gz-sim, pull requests merged in 2022-09, with the labels that each got.

#1683 Fix reference link in ackermann steering
  src/systems/ackermann_steering/AckermannSteering.hh
Labels: 🏯 fortress

#1649 Use RTLD_NODELETE=true when loading libraries
  src/SystemLoader.cc
  src/gui/Gui_clean_exit_TEST.cc
Labels: bug, 🌱 garden, Breaking change

#1686 Fix from source installation instructions on Ubuntu 22.04
  tutorials/install.md
Labels: documentation, 🏯 fortress

#1611 Add a service to trigger functionality
  examples/worlds/triggered_publisher.sdf
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/triggered_publisher/TriggeredPublisher.hh
  test/integration/triggered_publisher.cc
  test/worlds/triggered_publisher.sdf
  tutorials/triggered_publisher.md
Labels: enhancement, 🏯 fortress

#1694 Fix loading render engine plugins in GUI
  include/ignition/gazebo/rendering/RenderUtil.hh
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/rendering/RenderUtil.cc
Labels: 🏯 fortress

#1680 Fix display of Pose3d and Vector3d on macOS
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Vector3d.qml
Labels: bug, GUI, macOS, 🌱 garden

#1699 Remove actors from screen when they are supposed to
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: 🏰 citadel

#1703 Visibility example documentation tweak
  examples/worlds/visibility.sdf
Labels: 🌱 garden, tutorial-party

#1716 Rename python library as gz.sim7
  Migration.md
  examples/scripts/python_api/testFixture.py
  python/CMakeLists.txt
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/testFixture_TEST.py
Labels: 🌱 garden

#1723 Add code quotes to TestFixture.hh
  include/gz/sim/TestFixture.hh
Labels: 🌱 garden, tutorial-party

#1707 Lock step video recording is broken, disabling
  examples/worlds/minimal_scene.sdf
  examples/worlds/video_record_dbl_pendulum.sdf
Labels: 🌱 garden, tutorial-party

#1702 Fix some warnings in visualize_lidar.sdf
  examples/worlds/visualize_lidar.sdf
Labels: 🌱 garden, tutorial-party

#1689 Enable inherited model topic name.
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
Labels: 🏯 fortress

#1728 Fix macOS test segfaults
  src/SdfEntityCreator.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🌱 garden

#1729 Update changelogs for sim 7.0.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1732 Fix reset_sensor test
  src/SystemManager.cc
Labels: 🌱 garden

#1701 Add ResourceSpawner example file
  examples/worlds/resource_spawner.sdf
Labels: 🏯 fortress

#1733 Add benchmark to list packages to be installed
  .github/ci/packages.apt
Labels: 🌱 garden

#1720 Update examples for `camera_sensor` and `depth_camera_sensor`
  examples/worlds/camera_sensor.sdf
  examples/worlds/depth_camera_sensor.sdf
Labels: 🌱 garden

#1737 Silly typo mistake for triggered_publisher example
  examples/worlds/triggered_publisher.sdf
Labels: 🏯 fortress

#1713 Fix shader params system on macOS
  src/systems/shader_param/ShaderParam.cc
Labels: 🌱 garden

#1734 Disable flaky scenebroadcaster test
  test/integration/scene_broadcaster_system.cc
Labels: 🌱 garden

#1717 Update tutorial for `model_and_optimize_meshes`
  tutorials/model_and_optimize_meshes.md
Labels: 🌱 garden

#1739 Adds sky cubemap URI to the sky.proto's header
  CMakeLists.txt
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: needs upstream release, 🏯 fortress
