Repository gazebosim/gz-sim, pull requests merged in 2022-08, with the labels that each got.

#1536 Quick start dialog
  CMakeLists.txt
  examples/worlds/CMakeLists.txt
  examples/worlds/thumbnails/CMakeLists.txt
  examples/worlds/thumbnails/OpenRobotics.NAO joint control.png
  examples/worlds/thumbnails/OpenRobotics.Panda joint control world.png
  examples/worlds/thumbnails/OpenRobotics.Prius on Sonoma Raceway.png
  examples/worlds/thumbnails/OpenRobotics.Quadcopter teleop.png
  examples/worlds/thumbnails/OpenRobotics.Tugbot in Warehouse.png
  examples/worlds/thumbnails/openrobotics.empty.png
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/config.hh.in
  include/ignition/gazebo/gui/Gui.hh
  src/Util.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/Gui_TEST.cc
  src/gui/QuickStartHandler.cc
  src/gui/QuickStartHandler.hh
  src/gui/gui.config
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/resources/FuelThumbnail.qml
  src/gui/resources/QuickStart.qml
  src/gui/resources/gazebo.qrc
  src/gui/resources/images/gazebo_horz_pos_topbar.svg
  src/gui/resources/images/search.svg
  src/ign.cc
  src/ign.hh
Labels: enhancement, 🏰 citadel, OOBE 📦✨

#1549 Add system to an entity through Component Inspector
  include/ignition/gazebo/SystemLoader.hh
  src/ServerConfig.cc
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  test/integration/entity_system.cc
  test/worlds/diff_drive_no_plugin.sdf
Labels: enhancement, GUI, 🏯 fortress, OOBE 📦✨

#1627 Fix loading worlds from CLI
  src/gui/Gui.cc
Labels: bug, GUI, 🏰 citadel

#1626 Merge ign-gazebo3 ➡️ ign-gazebo6
  CMakeLists.txt
  README.md
  examples/worlds/CMakeLists.txt
  examples/worlds/apply_link_wrench.sdf
  examples/worlds/thumbnails/CMakeLists.txt
  examples/worlds/thumbnails/OpenRobotics.NAO joint control.png
  examples/worlds/thumbnails/OpenRobotics.Panda joint control world.png
  examples/worlds/thumbnails/OpenRobotics.Prius on Sonoma Raceway.png
  examples/worlds/thumbnails/OpenRobotics.Quadcopter teleop.png
  examples/worlds/thumbnails/OpenRobotics.Tugbot in Warehouse.png
  examples/worlds/thumbnails/openrobotics.empty.png
  include/ignition/gazebo/Model.hh
  include/ignition/gazebo/SystemLoader.hh
  include/ignition/gazebo/Util.hh
  include/ignition/gazebo/config.hh.in
  include/ignition/gazebo/gui/Gui.hh
  src/Model.cc
  src/ServerConfig.cc
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/Util.cc
  src/Util_TEST.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/GuiFileHandler.hh
  src/gui/Gui_TEST.cc
  src/gui/Gui_clean_exit_TEST.cc
  src/gui/QuickStartHandler.cc
  src/gui/QuickStartHandler.hh
  src/gui/gui.config
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Vector3d.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.qrc
  src/gui/resources/FuelThumbnail.qml
  src/gui/resources/QuickStart.qml
  src/gui/resources/gazebo.qrc
  src/gui/resources/images/gazebo_horz_pos_topbar.svg
  src/gui/resources/images/search.svg
  src/ign.cc
  src/ign.hh
  src/systems/CMakeLists.txt
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.hh
  src/systems/apply_link_wrench/CMakeLists.txt
  src/systems/user_commands/UserCommands.cc
  test/integration/CMakeLists.txt
  test/integration/ackermann_steering_system.cc
  test/integration/apply_link_wrench_system.cc
  test/integration/entity_system.cc
  test/integration/model.cc
  test/worlds/apply_link_wrench.sdf
  test/worlds/diff_drive_no_plugin.sdf
Labels: 🏯 fortress

#1629 ign -> gz Migrate config and log directories : gz-sim
  Migration.md
Labels: 🌱 garden, ign to gz

#1630 Merge ign-gazebo6 ➡️ main (part 1)
  CMakeLists.txt
  Changelog.md
  examples/worlds/boundingbox_camera.sdf
  examples/worlds/multicopter_velocity_control.sdf
  include/gz/sim/components/BoundingBoxCamera.hh
  include/ignition/gazebo/components/BoundingBoxCamera.hh
  src/SdfEntityCreator.cc
  src/cmd/CMakeLists.txt
  src/cmd/cmdsim.rb.in
  src/cmd/model.bash_completion.sh
  src/cmd/sim.bash_completion.sh
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/gz_TEST.cc
  src/rendering/RenderUtil.cc
  src/systems/diff_drive/DiffDrive.hh
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  src/systems/sensors/CMakeLists.txt
  src/systems/sensors/Sensors.cc
  test/integration/ModelPhotoShootTest.hh
  test/integration/odometry_publisher.cc
  test/integration/sensors_system_battery.cc
Labels: 🌱 garden

#1634 Update gz-sensors branch in example
  examples/plugin/custom_sensor_system/CMakeLists.txt
Labels: bug, tests, 🌱 garden

#1631 Merge ign-gazebo6 ➡️ main (part 2)
  .github/ci/packages.apt
  Changelog.md
  include/gz/sim/Conversions.hh
  include/gz/sim/Events.hh
  include/gz/sim/Server.hh
  include/gz/sim/ServerConfig.hh
  include/gz/sim/SystemLoader.hh
  include/gz/sim/components/Serialization.hh
  include/gz/sim/gui/GuiEvents.hh
  include/gz/sim/rendering/SceneManager.hh
  python/CMakeLists.txt
  src/CMakeLists.txt
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/Server.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/Util.cc
  src/gui/GuiEvents.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/rendering/SceneManager.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/physics/CMakeLists.txt
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/triggered_publisher/TriggeredPublisher.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/CMakeLists.txt
  test/integration/battery_plugin.cc
  test/integration/entity_system.cc
  test/integration/follow_actor_system.cc
  test/integration/network_handshake.cc
  test/integration/reset.cc
  test/integration/reset_sensors.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sensors_system.cc
  test/integration/sensors_system_battery.cc
  test/integration/wind_effects.cc
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  test/worlds/diff_drive_no_plugin.sdf
  test/worlds/particle_emitter.sdf
  test/worlds/reset_detachable_joint.sdf
Labels: 🌱 garden

#1640 ⬆️ Bump main to 8.0.0~pre1
  CMakeLists.txt
  Changelog.md
  examples/plugin/command_actor/CMakeLists.txt
  examples/plugin/custom_component/CMakeLists.txt
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/plugin/gui_system_plugin/CMakeLists.txt
  examples/plugin/hello_world/CMakeLists.txt
  examples/plugin/rendering_plugins/CMakeLists.txt
  examples/plugin/reset_plugin/CMakeLists.txt
  examples/plugin/system_plugin/CMakeLists.txt
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/each_performance/CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🌱 garden

#1641 Replace pose in ViewAngle with GzPose
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: GUI, 🏰 citadel, OOBE 📦✨

#1644 Update CODEOWNERS and maintainer to Michael
  .github/CODEOWNERS
  README.md
Labels: 🏰 citadel

#1605 🕐 Tock: Remove Fortress deprecations
  examples/plugin/rendering_plugins/RenderingGuiPlugin.hh
  examples/scripts/log_video_recorder/log_video_recorder.sdf
  examples/worlds/conveyor.sdf
  examples/worlds/deprecated_ignition.sdf
  examples/worlds/minimal_scene.sdf
  examples/worlds/spherical_coordinates.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  examples/worlds/tunnel.sdf
  examples/worlds/video_record_dbl_pendulum.sdf
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/Types.hh
  include/gz/sim/components/Factory.hh
  include/gz/sim/detail/ComponentStorageBase.hh
  include/gz/sim/detail/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/gui/Gui.cc
  src/gui/gui.config
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/align_tool/AlignTool.cc
  src/gui/plugins/plot_3d/Plot3D_TEST.cc
  src/gui/plugins/scene3d/CMakeLists.txt
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/GzScene3D.qrc
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
  src/gui/plugins/scene_manager/GzSceneManager.hh
  src/gui/plugins/select_entities/SelectEntities.hh
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  test/worlds/conveyor.sdf
  test/worlds/log_record_resources.sdf
  test/worlds/revolute_joint_equilibrium.sdf
  tutorials/gui_config.md
  tutorials/rendering_plugins.md
  tutorials/server_config.md
  tutorials/video_recorder.md
Labels: bug, 🌱 garden, Breaking change

#1607 Component Inspector with common widget pose plotting
  src/gui/plugins/component_inspector/Pose3d.qml
Labels: GUI, 🏯 fortress, OOBE 📦✨

#1638 Replace plotIcon in ComponentInspector with GzPlotIcon
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Physics.qml
  src/gui/plugins/component_inspector/SphericalCoordinates.qml
Labels: GUI, 🏯 fortress, OOBE 📦✨

#1637 Add option to disable building python bindings
  CMakeLists.txt
Labels: bug, 🌱 garden

#1530 Common widget GzColor replacement
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Material.qml
Labels: GUI, 🏯 fortress, OOBE 📦✨

#1636 Add support for specifying log record period
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/ServerConfig.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/cmd/cmdgazebo.rb.in
  src/cmd/gazebo.bash_completion.sh
  src/ign.cc
  src/ign.hh
  src/systems/log/LogRecord.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/log_system.cc
Labels: enhancement, 🏯 fortress

#1650 🎈 3.14.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#1651 ign-gazebo3 -> ign-gazebo6
  .github/CODEOWNERS
  README.md
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: 🏯 fortress

#1643 Fix Windows and Doxygen
  src/LevelManager.cc
  src/gui/QuickStartHandler.hh
  src/systems/elevator/Elevator.hh
  src/systems/elevator/ElevatorCommonPrivate.hh
  src/systems/elevator/ElevatorStateMachine.hh
  src/systems/elevator/state_machine/ActionsImpl.hh
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/elevator/state_machine/EventsImpl.hh
  src/systems/elevator/state_machine/GuardsImpl.hh
  src/systems/elevator/state_machine/StatesImpl.hh
  src/systems/elevator/utils/DoorTimer.hh
  src/systems/elevator/utils/JointMonitor.hh
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/optical_tactile_plugin/Visualization.hh
  src/systems/particle_emitter2/ParticleEmitter2.cc
  test/integration/apply_link_wrench_system.cc
Labels: bug, documentation, Windows, 🏯 fortress

#1617 Adding tests for hydrodynamics
  src/systems/hydrodynamics/Hydrodynamics.cc
  test/integration/CMakeLists.txt
  test/integration/hydrodynamics.cc
  test/worlds/hydrodynamics.sdf
Labels: bug, tests, 🌱 garden, MBARI buoy

#1618 Set seed value using CLI
  src/cmd/cmdsim.rb.in
  src/gz.cc
  src/gz.hh
  src/gz_TEST.cc
Labels: enhancement

#1608 Acoustic comms plugin
  examples/worlds/acoustic_comms.sdf
  examples/worlds/acoustic_comms_moving_targets.sdf
  src/systems/CMakeLists.txt
  src/systems/acoustic_comms/AcousticComms.cc
  src/systems/acoustic_comms/AcousticComms.hh
  src/systems/acoustic_comms/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/acoustic_comms.cc
Labels: enhancement, MBARI-LRAUV

#1670 Readd namespaces for Q_ARGS
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/joint_position_controller/JointPositionController.cc
Labels: bug, 🏰 citadel

#1671 Add information about <topic> system paramter in JointStatePublisher
  src/systems/joint_state_publisher/JointStatePublisher.hh
Labels: 🏯 fortress

#1225 Add Metal support to Gazebo for macOS
  src/cmd/cmdsim.rb.in
  src/gui/plugins/component_inspector/Boolean.qml
  src/gui/plugins/modules/TypeIcon.qml
  src/gui/plugins/visualize_lidar/VisualizeLidar.qml
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
Labels: bug, GUI, rendering, sensors, macOS, 🌱 garden

#1674 Fix two tests
  test/integration/log_system.cc
  test/integration/save_world.cc
  test/worlds/joint_sensor.sdf
Labels: bug, 🌱 garden

#1675 Fix gz_TEST paths
  src/gz_TEST.cc
Labels: bug, 🌱 garden

#1677 6 ➡️ 7: Fix Windows and Doxygen (#1643)
  src/systems/elevator/Elevator.cc
  src/systems/elevator/Elevator.hh
  src/systems/elevator/ElevatorCommonPrivate.hh
  src/systems/elevator/ElevatorStateMachine.hh
  src/systems/elevator/state_machine/ActionsImpl.hh
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/elevator/state_machine/EventsImpl.hh
  src/systems/elevator/state_machine/GuardsImpl.hh
  src/systems/elevator/state_machine/StatesImpl.hh
  src/systems/elevator/utils/DoorTimer.cc
  src/systems/elevator/utils/DoorTimer.hh
  src/systems/elevator/utils/JointMonitor.cc
  src/systems/elevator/utils/JointMonitor.hh
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/optical_tactile_plugin/Visualization.hh
  src/systems/particle_emitter2/ParticleEmitter2.cc
Labels: bug, Windows, 🌱 garden

#1678 Remove unused function
  src/gui/GuiRunner.cc
  src/gui/GuiRunner.hh
Labels: bug, 🌱 garden, Breaking change

#1681 Add topic parameter to thrust plugin
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_battery.sdf
Labels: 🏯 fortress

#1682 🎈 6.12.0: bumped minor and updated changelog
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🏯 fortress

#1566 Update headers for missing transitive includes
  examples/standalone/comms/publisher.cc
  examples/standalone/entity_creation/entity_creation.cc
  examples/standalone/joy_to_twist/joy_to_twist.cc
  examples/standalone/joystick/joystick.cc
  examples/standalone/light_control/light_control.cc
  examples/standalone/multi_lrauv_race/multi_lrauv_race.cc
  include/gz/sim/comms/MsgManager.hh
  include/gz/sim/rendering/SceneManager.hh
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/gui/Gui.cc
  src/gui/GuiFileHandler.cc
  src/gui/GuiRunner.cc
  src/gui/Gui_TEST.cc
  src/gui/PathManager.cc
  src/gui/plugins/component_inspector/Pose3d.cc
  src/gui/plugins/copy_paste/CopyPaste.cc
  src/gui/plugins/copy_paste/CopyPaste.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/network/NetworkManagerPrimary.hh
  src/rendering/MarkerManager.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/elevator/state_machine/ElevatorStateMachineImpl.hh
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/velocity_control/VelocityControl.cc
  test/integration/camera_sensor_background.cc
  test/integration/camera_sensor_background_from_scene.cc
  test/integration/camera_video_record_system.cc
  test/integration/joint_state_publisher_system.cc
  test/integration/logical_audio_sensor_plugin.cc
  test/integration/multicopter.cc
  test/integration/network_handshake.cc
  test/integration/perfect_comms.cc
  test/integration/play_pause.cc
  test/integration/rf_comms.cc
  test/integration/save_world.cc
  test/integration/touch_plugin.cc
  test/performance/sdf_runner.cc
  test/plugins/TestModelSystem.hh
  test/plugins/TestSensorSystem.hh
  test/plugins/TestVisualSystem.hh
Labels: bug, 🌱 garden
