Repository gazebosim/gz-sim, pull requests merged in 2022-01, with the labels that each got.

#1274 Add project() call to examples
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/each_performance/CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
Labels: 🏰 citadel

#1271 Re-enable triggered publisher tests
  test/integration/CMakeLists.txt
Labels: 🌱 garden

#1229 Min and max parameters for velocity, acceleration, and jerk apply to linear and angular separately.
  examples/worlds/diff_drive.sdf
  examples/worlds/diff_drive_skid.sdf
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  test/worlds/diff_drive.sdf
  test/worlds/diff_drive_custom_topics.sdf
Labels: 🏢 edifice

#1276 3 ➡️ 5
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/each_performance/CMakeLists.txt
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  include/ignition/gazebo/Server.hh
  include/ignition/gazebo/gui/TmpIface.hh
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/gui/TmpIface.cc
Labels: 🏢 edifice

#1285 Documentation Error
  README.md
Labels: 🏢 edifice

#1248 Add NavSat sensor (GPS)
  CMakeLists.txt
  examples/worlds/spherical_coordinates.sdf
  include/ignition/gazebo/components/NavSat.hh
  src/Conversions.cc
  src/SdfEntityCreator.cc
  src/systems/CMakeLists.txt
  src/systems/navsat/CMakeLists.txt
  src/systems/navsat/NavSat.cc
  src/systems/navsat/NavSat.hh
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/navsat_system.cc
  test/worlds/navsat.sdf
Labels: enhancement, sensors, 🏯 fortress

#1279 Add world force
  include/ignition/gazebo/Link.hh
  src/Link.cc
  test/integration/link.cc
Labels: physics, 🏯 fortress

#1286 Disable more tests on Windows
  src/EntityComponentManager_TEST.cc
  src/SdfGenerator_TEST.cc
  test/integration/buoyancy_engine.cc
  test/integration/force_torque_system.cc
  test/integration/navsat_system.cc
  test/integration/physics_system.cc
  test/integration/recreate_entities.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/spherical_coordinates.cc
  test/integration/world_control_state.cc
Labels: tests, needs upstream release, 🏯 fortress

#1289 Prepare for 6.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1282 Cleanup update call for non-rendering sensors
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/imu/Imu.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
Labels: 🏢 edifice

#1263 Optional orientation when spawning entity using spherical coordinates
  src/systems/user_commands/UserCommands.cc
  test/integration/spherical_coordinates.cc
Labels: 🏯 fortress

#1291 typo fix.
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/System.hh
  include/ignition/gazebo/components/JointTransmittedWrench.hh
  include/ignition/gazebo/detail/ComponentStorageBase.hh
  include/ignition/gazebo/detail/View.hh
  include/ignition/gazebo/rendering/SceneManager.hh
Labels: 🏯 fortress

#1292 5 ➡️ 6
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/each_performance/CMakeLists.txt
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  examples/worlds/diff_drive.sdf
  examples/worlds/diff_drive_skid.sdf
  include/ignition/gazebo/Server.hh
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/diff_drive/DiffDrive.hh
  src/systems/imu/Imu.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  test/worlds/diff_drive.sdf
  test/worlds/diff_drive_custom_topics.sdf
  tutorials/install.md
Labels: 🏯 fortress

#1294 Prevent GzScene3D 💥 if another scene is already loaded
  src/gui/plugins/scene3d/GzScene3D.qml
  src/gui/plugins/scene3d/Scene3D.cc
  src/gui/plugins/scene3d/Scene3D.hh
Labels: bug, 🏰 citadel, OOBE 📦✨

#1269 Thruster plugin: accept angular velocity and provide feedback on topic
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_ang_vel_cmd.sdf
Labels: 🌱 garden

#1298 Add surface to buoyancy engine. (retarget fortress)
  examples/worlds/buoyancy_engine.sdf
  src/systems/buoyancy_engine/BuoyancyEngine.cc
  src/systems/buoyancy_engine/BuoyancyEngine.hh
  test/integration/buoyancy_engine.cc
  test/worlds/buoyancy_engine.sdf
Labels: 🏯 fortress

#1297 Fix graded buoyancy problems
  examples/worlds/graded_buoyancy.sdf
  src/systems/buoyancy/Buoyancy.cc
  src/systems/buoyancy/Buoyancy.hh
  test/integration/buoyancy.cc
  test/integration/buoyancy_engine.cc
  test/worlds/buoyancy_graded_restoring_moments.sdf
  test/worlds/buoyancy_uniform_restoring_moments.sdf
Labels: bug, 🏯 fortress

#1302 Buoyancy: fix center of volume's reference frame
  include/ignition/gazebo/components/CenterOfVolume.hh
  src/systems/buoyancy/Buoyancy.cc
  test/integration/buoyancy.cc
  test/worlds/center_of_volume.sdf
Labels: bug, 🏰 citadel

#1304 Fix typo in EntityComponentManager
  src/EntityComponentManager.cc
Labels: 🏯 fortress

#1300 Mark Component::Clone as const
  Migration.md
  include/ignition/gazebo/components/Component.hh
  src/Component_TEST.cc
Labels: 🌱 garden

#1309 Document the `<topic>` option for JointPositionController.
  src/systems/joint_position_controller/JointPositionController.hh
Labels: 🏯 fortress

#1308 [python] Add worldEntity util
  examples/scripts/python_api/README.md
  examples/scripts/python_api/gravity.sdf
  examples/scripts/python_api/testFixture.py
  include/ignition/gazebo/EventManager.hh
  python/CMakeLists.txt
  python/src/ignition/gazebo/Util.cc
  python/src/ignition/gazebo/Util.hh
  python/src/ignition/gazebo/_ignition_gazebo_pybind11.cc
  python/test/testFixture_TEST.py
  tutorials/python_interfaces.md
Labels: scripting

#1311 Update source install instructions
  tutorials/install.md
Labels: bug, documentation, 🏯 fortress

#1314 Log an error if JointPositionController cannot find the joint. (citadel retarget)
  src/systems/joint_position_controller/JointPositionController.cc
Labels: 🏰 citadel
