Repository gazebosim/gz-sim, pull requests merged in 2022-12, with the labels that each got.

#1827 Fixed Fortress tests related to lights
  src/SdfEntityCreator_TEST.cc
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/gui/Gui_TEST.cc
  test/integration/log_system.cc
  test/integration/recreate_entities.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/user_commands.cc
Labels: 🏯 fortress

#1819 hydrodynamics flags test strengthening
  test/integration/hydrodynamics_flags.cc
  test/worlds/hydrodynamics_flags.sdf
Labels: 🏯 fortress

#1825 Sync View Angle GUI with view controller
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: needs upstream release, 🏯 fortress

#1829 Fix QML warnings regarding binding loops
  src/gui/resources/GazeboDrawer.qml
Labels: 🏰 citadel

#1830 Remove duplicate Fuel server used by ResourceSpawner
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
Labels: 🏰 citadel

#1832 port: 6 to 7 2022-12-06
  src/SdfEntityCreator_TEST.cc
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/gui/Gui_TEST.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
  test/integration/hydrodynamics_flags.cc
  test/integration/log_system.cc
  test/integration/recreate_entities.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/user_commands.cc
  test/worlds/hydrodynamics_flags.sdf
Labels: 🌱 garden

#1833 Fix component removal in component inspector
  src/gui/plugins/component_inspector/ComponentInspector.cc
Labels: 🌱 garden

#1822 Example controller for LRAUV
  examples/standalone/lrauv_control/CMakeLists.txt
  examples/standalone/lrauv_control/README.md
  examples/standalone/lrauv_control/lrauv_control.cc
  examples/worlds/lrauv_control_demo.sdf
Labels: 🌱 garden

#1814 Add multichannel lookup for environment sensors.
  src/systems/environmental_sensor_system/CMakeLists.txt
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.cc
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh
  src/systems/environmental_sensor_system/TransformTypes.hh
  src/systems/environmental_sensor_system/TransformTypes_TEST.cc
  test/integration/environmental_sensor_system.cc
  test/worlds/environmental_sensor.csv
  test/worlds/environmental_sensor.sdf.in
Labels: 🌱 garden, MBARI-LRAUV

#1840 Disable tests that require dartsim on windows
  test/integration/hydrodynamics.cc
  test/integration/hydrodynamics_flags.cc
Labels: 🏯 fortress

#1839 Allow using a CSV file to define currents for hydrodynamic system
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  test/integration/hydrodynamics.cc
  test/worlds/CMakeLists.txt
  test/worlds/hydrodynamic_currents.csv
  test/worlds/hydrodynamics.sdf.in
Labels: 🌱 garden, MBARI-LRAUV

#1811 Adding battery consumers and extra fixes
  include/ignition/gazebo/components/BatteryPowerLoad.hh
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/thruster/Thruster.cc
  test/integration/battery_plugin.cc
  test/worlds/battery.sdf
  test/worlds/battery_thruster_consumer.sdf
  tutorials/battery.md
Labels: 🏯 fortress, MBARI-LRAUV

#1431 Add interface to allow systems to declare parameters
  CMakeLists.txt
  include/ignition/gazebo/System.hh
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
Labels: enhancement, needs upstream release, 🏯 fortress

#1846 Header guard fix for battery power load component
  include/ignition/gazebo/components/BatteryPowerLoad.hh
Labels: 🏯 fortress

#1849 Fix Ackermann plugin zero linVel turningRadius bug
  src/systems/ackermann_steering/AckermannSteering.cc
Labels: 🏯 fortress

#1850 🎈 6.14.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
