Repository gazebosim/gz-sim, pull requests merged in 2022-11, with the labels that each got.

#1744 Refactor: Trajectory loading seperated into external function
  src/rendering/SceneManager.cc
Labels: 🌱 garden

#1771 Towards Green CI
  .gitignore
  python/CMakeLists.txt
  python/test/testFixture_TEST.py
  src/Conversions_TEST.cc
  src/SdfGenerator_TEST.cc
  src/Server.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/gz_TEST.cc
  src/systems/acoustic_comms/AcousticComms.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/rf_comms/RFComms.cc
  src/systems/shader_param/ShaderParam.cc
  src/systems/track_controller/TrackController.cc
  src/systems/trajectory_follower/TrajectoryFollower.cc
  test/integration/breadcrumbs.cc
  test/integration/fuel_cached_server.cc
  test/integration/hydrodynamics.cc
  test/integration/odometry_publisher.cc
  test/integration/optical_tactile_plugin.cc
  test/integration/save_world.cc
  test/integration/scene_broadcaster_system.cc
  test/media/RescueRandy_Thermal.png
  test/worlds/breadcrumbs.sdf
  test/worlds/breadcrumbs_levels.sdf
  test/worlds/follow_actor.sdf
  test/worlds/fuel.gazebosim.org/openroboticstest/worlds/test%20world/2/test.sdf
  test/worlds/fuel.gazebosim.org/openroboticstest/worlds/test%20world/2/thumbnails/1.png
  test/worlds/model_nested_include.sdf
  test/worlds/model_photo_shoot_random_joints.sdf
  test/worlds/save_world.sdf
  test/worlds/thermal.sdf
Labels: 🌱 garden

#1778 Fix abi-checker: patch typo in Export.hh
  include/ignition/gazebo/thermal-sensor-system-system/Export.hh
Labels: 🌱 garden

#1779 Fix two tests on Windows
  src/Server_TEST.cc
  src/SystemLoader_TEST.cc
Labels: 🏯 fortress

#1781 🎈 6.13.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1755 Acoustic comms : Packet collision timeout
  examples/worlds/acoustic_comms_packet_collision.sdf
  src/systems/acoustic_comms/AcousticComms.cc
  src/systems/acoustic_comms/AcousticComms.hh
  test/integration/acoustic_comms.cc
Labels: 🌱 garden

#1774 Change nameFilter of saveDialog from "World files" to "SDF files"
  src/gui/resources/GazeboDrawer.qml
Labels: 🌱 garden

#1743 Fix minor bugs in RFComms plugin
  src/systems/rf_comms/RFComms.cc
Labels: 🏯 fortress

#1787 Addresses flakiness in `Hydrodynamics.VelocityTestInOil`.
  test/integration/hydrodynamics.cc
  test/worlds/hydrodynamics.sdf
Labels: 🏯 fortress

#1775 Allow loading a model SDF file in the Server class
  src/CMakeLists.txt
  src/Server.cc
  src/Server_Rendering_TEST.cc
  test/worlds/models/relative_resource_uri/meshes/box.dae
  test/worlds/models/relative_resource_uri/model2.sdf
Labels: 🌱 garden

#1790 🎈 7.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1616 Add EnvironmentalData component
  CMakeLists.txt
  include/gz/sim/components/Environment.hh
  src/CMakeLists.txt
  src/components/Environment.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/environment_loader/CMakeLists.txt
  src/gui/plugins/environment_loader/EnvironmentLoader.cc
  src/gui/plugins/environment_loader/EnvironmentLoader.hh
  src/gui/plugins/environment_loader/EnvironmentLoader.qml
  src/gui/plugins/environment_loader/EnvironmentLoader.qrc
  src/systems/CMakeLists.txt
  src/systems/environment_preload/CMakeLists.txt
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environment_preload/EnvironmentPreload.hh
  test/integration/CMakeLists.txt
  test/integration/environment_preload_system.cc
  test/worlds/CMakeLists.txt
  test/worlds/environmental_data.csv
  test/worlds/environmental_data.sdf.in
Labels: enhancement, needs upstream release, MBARI-LRAUV

#1784 Adds support for hydrodynamic cross terms
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
Labels: 🏯 fortress, MBARI-LRAUV

#1748 Adds a tool for environment data visualization
  examples/worlds/environmental_data.csv
  examples/worlds/environmental_sensor.sdf
  include/gz/sim/Util.hh
  include/gz/sim/components/Environment.hh
  src/Util.cc
  src/components/Environment.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/environment_loader/EnvironmentLoader.cc
  src/gui/plugins/environment_loader/EnvironmentLoader.hh
  src/gui/plugins/environment_loader/EnvironmentLoader.qml
  src/gui/plugins/environment_visualization/CMakeLists.txt
  src/gui/plugins/environment_visualization/EnvironmentVisualization.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.hh
  src/gui/plugins/environment_visualization/EnvironmentVisualization.qml
  src/gui/plugins/environment_visualization/EnvironmentVisualization.qrc
  src/systems/CMakeLists.txt
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environmental_sensor_system/CMakeLists.txt
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.cc
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh
  test/integration/CMakeLists.txt
  test/integration/environment_preload_system.cc
  test/integration/environmental_sensor_system.cc
  test/worlds/CMakeLists.txt
  test/worlds/environmental_data.sdf.in
  test/worlds/environmental_sensor.csv
  test/worlds/environmental_sensor.sdf.in
Labels: needs upstream release, MBARI-LRAUV

#1788 Add checkbox in view angle plugin for toggling view control reference visual
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: 🏯 fortress

#1793 Acoustic comms : Propagation model
  examples/worlds/acoustic_comms_propagation.sdf
  src/systems/acoustic_comms/AcousticComms.cc
  src/systems/acoustic_comms/AcousticComms.hh
  test/integration/acoustic_comms.cc
Labels: 🌱 garden, MBARI-LRAUV

#1798 Backport #1748: Adds a tool for environment data visualization and custom environmental sensors
  examples/worlds/environmental_data.csv
  examples/worlds/environmental_sensor.sdf
  include/gz/sim/Util.hh
  include/gz/sim/components/Environment.hh
  src/Util.cc
  src/components/Environment.cc
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/environment_loader/EnvironmentLoader.cc
  src/gui/plugins/environment_loader/EnvironmentLoader.hh
  src/gui/plugins/environment_loader/EnvironmentLoader.qml
  src/gui/plugins/environment_visualization/CMakeLists.txt
  src/gui/plugins/environment_visualization/EnvironmentVisualization.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.hh
  src/gui/plugins/environment_visualization/EnvironmentVisualization.qml
  src/gui/plugins/environment_visualization/EnvironmentVisualization.qrc
  src/systems/CMakeLists.txt
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environmental_sensor_system/CMakeLists.txt
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.cc
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.hh
  test/integration/CMakeLists.txt
  test/integration/environment_preload_system.cc
  test/integration/environmental_sensor_system.cc
  test/worlds/CMakeLists.txt
  test/worlds/environmental_data.sdf.in
  test/worlds/environmental_sensor.csv
  test/worlds/environmental_sensor.sdf.in
Labels: 🌱 garden, MBARI-LRAUV

#1805 Remove fixed width from world control
  src/gui/gui.config
Labels: 🌱 garden

#1750 Check AddBvhAnimation return value
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#1809 Removed unused attributes in view_angle plugin
  src/gui/plugins/view_angle/ViewAngle.cc
Labels: 🌱 garden

#1813 Restore GUI support for macOS
  src/cmd/cmdsim.rb.in
Labels: 🌱 garden

#1817 Update documentation on `UpdateInfo::realTime`
  include/ignition/gazebo/Types.hh
Labels: 🏰 citadel

#1818 Fixed light entity number
  src/SdfEntityCreator.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
Labels: 🏯 fortress

#1821 port: 6 to 7 2022-11-29
  src/SdfEntityCreator.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
Labels: 🌱 garden

#1810 Allow to move to model from Angle view plugin
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
Labels: 🏯 fortress
