Repository gazebosim/gz-sim, pull requests merged in 2022-03, with the labels that each got.

#1335 Extend ShaderParam system to support loading different shader languages
  src/systems/shader_param/ShaderParam.cc
  src/systems/shader_param/ShaderParam.hh
Labels: 🏯 fortress

#1368 Disables Failing Buoyancy Tests on Win32
  test/integration/buoyancy.cc
Labels: 🏯 fortress

#1287 Emitter migration
  Migration.md
  examples/worlds/multi_lrauv_race.sdf
  examples/worlds/particle_emitter.sdf
  examples/worlds/particle_emitter2.sdf
  src/systems/particle_emitter/ParticleEmitter.cc
  src/systems/particle_emitter/ParticleEmitter.hh
  src/systems/particle_emitter2/ParticleEmitter2.hh
  test/integration/CMakeLists.txt
  test/integration/particle_emitter.cc
  test/integration/particle_emitter2.cc
  test/worlds/particle_emitter.sdf
  test/worlds/particle_emitter2.sdf
  tutorials/particle_tutorial.md
Labels: rendering, 🌱 garden

#1346 Eliminates std::filesystem usage in utils.cc
  src/Util.cc
Labels: needs upstream release, 🌱 garden

#1369 Use pose multiplication instead of addition
  src/Util.cc
  src/rendering/RenderUtil.cc
  src/systems/optical_tactile_plugin/Visualization.cc
Labels: 🏯 fortress

#1372 Fix typo in python tutorial
  tutorials/python_interfaces.md
Labels: 🏯 fortress

#1371 GzSceneManager: Prevent crash 💥 when inserted from menu
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/gui/plugins/scene_manager/GzSceneManager.hh
  src/gui/plugins/scene_manager/GzSceneManager.qml
Labels: 🏯 fortress, OOBE 📦✨

#1373 Preapare version 6.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#1375 Populate GUI plugins that are empty
  examples/worlds/empty_gui.sdf
  src/gui/plugins/entity_context_menu/EntityContextMenuPlugin.cc
  src/gui/plugins/entity_context_menu/EntityContextMenuPlugin.qml
  src/gui/plugins/scene_manager/GzSceneManager.qml
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/select_entities/SelectEntities.qml
  src/gui/plugins/spawn/Spawn.cc
  src/gui/plugins/spawn/Spawn.qml
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.qml
Labels: GUI, 🏯 fortress, OOBE 📦✨

#1377 Fix visualization python tutorial
  tutorials/python_interfaces.md
Labels: documentation, 🏯 fortress, scripting

#1382 Fix trajectory follower: enable WorldPose component
  src/systems/trajectory_follower/TrajectoryFollower.cc
Labels: bug, 🌱 garden

#1386 Added headless rendering tutorial
  tutorials.md.in
  tutorials/headless_rendering.md
Labels: documentation, rendering, 🏯 fortress

#1343 Allow to turn on/off lights
  CMakeLists.txt
  src/Conversions.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Light.qml
  src/rendering/RenderUtil.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
Labels: needs upstream release, 🏢 edifice, OOBE 📦✨

#1381 Add gazebo Entity id to rendering sensor's user data
  src/rendering/SceneManager.cc
  test/integration/CMakeLists.txt
  test/integration/sensors_system.cc
Labels: 🏯 fortress

#1388 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  docker/README.md
  tutorials/install.md
Labels: documentation, tests, 🌱 garden

#1391 Don't mark entities with a ComponentState::NoChange component as modified
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
Labels: 🏯 fortress

#1262 Added DEM support
  examples/worlds/dem_monterey_bay.sdf
  examples/worlds/dem_volcano.sdf
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
Labels: needs upstream release, 🌱 garden

#1397 Disable ModelCommandAPI_TEST.RgbdCameraSensor on macOS
  src/ModelCommandAPI_TEST.cc
Labels: 🏯 fortress

#1398 Disable PeerTracker.PeerTrackerStale on macOS
  src/network/PeerTracker_TEST.cc
Labels: 🏯 fortress

#1387 Toggle Light visuals
  examples/worlds/lights.sdf
  src/Conversions.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Light.qml
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/user_commands/UserCommands.cc
Labels: needs upstream release, 🏢 edifice, OOBE 📦✨

#1383 Prevent hanging when world has only non-world plugins
  src/SimulationRunner.cc
  src/SimulationRunner_TEST.cc
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
  test/worlds/model_plugin_only.sdf
Labels: 🏯 fortress, OOBE 📦✨

#1249 Support world reset
  include/ignition/gazebo/EntityComponentManager.hh
  include/ignition/gazebo/System.hh
  include/ignition/gazebo/detail/BaseView.hh
  include/ignition/gazebo/detail/View.hh
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManagerDiff.cc
  src/EntityComponentManagerDiff.hh
  src/EntityComponentManager_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager.hh
  test/integration/log_system.cc
Labels: 🌱 garden

#1400 Component inspector: refactor Pose3d C++ code into a separate class
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/Pose3d.cc
  src/gui/plugins/component_inspector/Pose3d.hh
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Types.hh
Labels: GUI, 🏰 citadel, OOBE 📦✨

#1406 Add <initial_position> param to JointPositionController system
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_position_controller/JointPositionController.hh
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller_velocity.sdf
Labels: 🏯 fortress, mbzirc

#1402 Preserve sign of thrust_coefficient
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_ccw_ang_vel_cmd.sdf
  test/worlds/thruster_ccw_force_cmd.sdf
Labels: 🌱 garden

#1405 Fix JointStatePublisher topic name for nested models
  src/systems/joint_state_publisher/JointStatePublisher.cc
  test/integration/joint_state_publisher_system.cc
  test/worlds/diff_drive_nested.sdf
Labels: 🏯 fortress, mbzirc

#1408 3 ➡️ 5
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/Pose3d.cc
  src/gui/plugins/component_inspector/Pose3d.hh
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Types.hh
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
  test/integration/buoyancy.cc
  test/integration/user_commands.cc
Labels: 🏢 edifice

#1395 Fortress: Install Ogre 2.2, simplify docker
  .github/ci/packages.apt
  docker/Dockerfile.base
  docker/scripts/install_ign_deps.sh
Labels: 🏯 fortress

#1407 Fix visibility and add documentation
  src/EntityComponentManagerDiff.hh
Labels: Windows, 🌱 garden

#1392 SceneBroadcaster: only send changed state information for change events
  src/EntityComponentManager.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/shapes_scene_broadcaster_only.sdf
Labels: 🏯 fortress

#1241 Add wheel slip user command
  include/ignition/gazebo/components/WheelSlipCmd.hh
  src/systems/user_commands/UserCommands.cc
  src/systems/wheel_slip/WheelSlip.cc
  test/integration/user_commands.cc
Labels: enhancement, 🏢 edifice

#1413 5 ➡️ 6
  CMakeLists.txt
  examples/worlds/lights.sdf
  src/Conversions.cc
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Pose3d.cc
  src/gui/plugins/component_inspector/Pose3d.hh
  src/gui/plugins/component_inspector/Pose3d.qml
  src/gui/plugins/component_inspector/Types.hh
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
  test/integration/user_commands.cc
Labels: needs upstream release, 🏯 fortress

#1374 Distortion camera integration test
  test/integration/CMakeLists.txt
  test/integration/distortion_camera.cc
  test/worlds/camera_distortion.sdf
Labels: needs upstream release, 🏯 fortress

#1331 Modelpropshop gazebo plugin port
  examples/worlds/model_photo_shoot.sdf
  src/systems/CMakeLists.txt
  src/systems/model_photo_shoot/CMakeLists.txt
  src/systems/model_photo_shoot/ModelPhotoShoot.cc
  src/systems/model_photo_shoot/ModelPhotoShoot.hh
  test/integration/CMakeLists.txt
  test/integration/ModelPhotoShootTest.hh
  test/integration/model_photo_shoot_default_joints.cc
  test/integration/model_photo_shoot_random_joints.cc
  test/worlds/model_photo_shoot_random_joints.sdf
  tutorials.md.in
  tutorials/model_photo_shoot.md
Labels: 🏢 edifice

#1419 Referring to Fuel assets within a heightmap
  examples/worlds/fuel.sdf
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
Labels: 🏯 fortress, MBARI-LRAUV

#1385 Disable sensors in sensors system when battery is drained
  src/systems/sensors/Sensors.cc
  src/systems/sensors/Sensors.hh
  test/integration/CMakeLists.txt
  test/integration/sensors_system_battery.cc
  test/worlds/sensors_system_battery.sdf
Labels: needs upstream release, 🏯 fortress

#1420 🏁🎈 5.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice
