Repository gazebosim/gz-sim, pull requests merged in 2022-10, with the labels that each got.

#1685 Restore Add System GUI plugin
  include/ignition/gazebo/SystemLoader.hh
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.hh
  src/gui/plugins/component_inspector/ComponentInspector.qml
  test/integration/entity_system.cc
  test/worlds/diff_drive_no_plugin.sdf
Labels: bug, GUI, 🏯 fortress

#1697 Remove actors from screen when they are supposed to
  src/rendering/RenderUtil.cc
Labels: 🌱 garden

#1719 Update tutorial for `blender_distort_meshes`
  examples/scripts/blender/distort_mesh.py
  tutorials/blender_distort_meshes.md
Labels: 🌱 garden

#1652 Adding thrust coefficient calculation
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thrust_coefficient.sdf
Labels: enhancement, 🏯 fortress, MBARI-LRAUV

#1676 Merge ign-gazebo6 ➡️ gz-sim7
  .github/CODEOWNERS
  Changelog.md
  README.md
  include/gz/sim/ServerConfig.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.cc
  src/cmd/cmdsim.rb.in
  src/cmd/sim.bash_completion.sh
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/Light.qml
  src/gui/plugins/component_inspector/Material.qml
  src/gui/plugins/component_inspector/Physics.qml
  src/gui/plugins/component_inspector/SphericalCoordinates.qml
  src/gui/plugins/view_angle/ViewAngle.qml
  src/gz.cc
  src/gz.hh
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/log/LogRecord.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/CMakeLists.txt
  test/integration/ackermann_steering_system.cc
  test/integration/hydrodynamics.cc
  test/integration/log_system.cc
  test/worlds/hydrodynamics.sdf
  test/worlds/log_record_resources.sdf
Labels: 🌱 garden

#1704 Cherry pick acoustic comms to gz-sim7
  examples/standalone/acoustic_comms_demo/CMakeLists.txt
  examples/standalone/acoustic_comms_demo/README.md
  examples/standalone/acoustic_comms_demo/acoustic_comms_demo.cc
  examples/worlds/acoustic_comms.sdf
  examples/worlds/acoustic_comms_demo.sdf
  examples/worlds/acoustic_comms_moving_targets.sdf
  src/systems/CMakeLists.txt
  src/systems/acoustic_comms/AcousticComms.cc
  src/systems/acoustic_comms/AcousticComms.hh
  src/systems/acoustic_comms/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/acoustic_comms.cc
Labels: 🌱 garden

#1749 Update examples to use gazebosim.org
  examples/standalone/joy_to_twist/README.md
  examples/standalone/joystick/README.md
  examples/worlds/actor.sdf
  examples/worlds/actors_population.sdf.erb
  examples/worlds/breadcrumbs.sdf
  examples/worlds/camera_sensor.sdf
  examples/worlds/depth_camera_sensor.sdf
  examples/worlds/elevator.sdf
  examples/worlds/fuel.sdf
  examples/worlds/fuel_textured_mesh.sdf
  examples/worlds/gpu_lidar_sensor.sdf
  examples/worlds/import_mesh.sdf
  examples/worlds/log_record_resources.sdf
  examples/worlds/multicopter_velocity_control.sdf
  examples/worlds/plot_3d.sdf
  examples/worlds/quadcopter.sdf
  examples/worlds/sensors_demo.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  examples/worlds/tunnel.sdf
Labels: 🏰 citadel

#1718 Fix tutorial for `blender_sdf_exporter`
  examples/scripts/blender/sdf_exporter.py
  tutorials/blender_sdf_exporter.md
Labels: 🌱 garden

#1753 Citadel: Removed warnings
  src/Util_TEST.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  test/integration/wheel_slip.cc
Labels: 🏰 citadel

#1692 Enable/Disable individual hydrodynamic components.
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  test/integration/CMakeLists.txt
  test/integration/hydrodynamics_flags.cc
  test/worlds/hydrodynamics_flags.sdf
Labels: 🏯 fortress

#1754 Fortress: Removed warnings
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  src/systems/optical_tactile_plugin/Visualization.cc
  src/systems/optical_tactile_plugin/Visualization.hh
  test/integration/thruster.cc
Labels: 🏯 fortress

#1756 Added collection name to About Dialog
  src/gui/AboutDialogHandler.cc
Labels: 🏰 citadel

#1757 Convert ignitionrobotics to gazebosim in tests directory
  test/integration/battery_plugin.cc
  test/integration/examples_build.cc
  test/integration/log_system.cc
  test/integration/network_handshake.cc
  test/integration/save_world.cc
  test/integration/sdf_include.cc
  test/integration/touch_plugin.cc
  test/integration/tracked_vehicle_system.cc
  test/worlds/breadcrumbs.sdf
  test/worlds/include.sdf
  test/worlds/log_record_resources.sdf
  test/worlds/save_world.sdf
Labels: 🏰 citadel

#1758 Convert ignitionrobotics to gazebosim in sources and includes
  include/ignition/gazebo/Entity.hh
  include/ignition/gazebo/ServerConfig.hh
  src/SdfGenerator_TEST.cc
  src/ServerConfig.cc
  src/Server_TEST.cc
  src/World.cc
  src/cmd/cmdgazebo.rb.in
  src/gui/AboutDialogHandler.cc
  src/gui/Gui_TEST.cc
  src/gui/plugins/scene3d/Scene3D.cc
  src/ign.hh
  src/ign_TEST.cc
  src/network/NetworkManagerPrimary.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/battery_plugin/LinearBatteryPlugin.hh
Labels: 🏰 citadel

#1759 Convert ignitionrobotics to gazebosim in tutorials
  src/ign_TEST.cc
  tutorials/battery.md
  tutorials/collada_world_exporter.md
  tutorials/detachable_joints.md
  tutorials/distributed_simulation.md
  tutorials/erb_template.md
  tutorials/gui_config.md
  tutorials/levels.md
  tutorials/log.md
  tutorials/logical_audio_sensor.md
  tutorials/mesh_to_fuel.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/migration_link_api.md
  tutorials/migration_model_api.md
  tutorials/migration_sdf.md
  tutorials/migration_world_api.md
  tutorials/physics.md
  tutorials/point_cloud_to_mesh.md
  tutorials/rendering_plugins.md
  tutorials/resources.md
  tutorials/server_config.md
  tutorials/terminology.md
  tutorials/test_fixture.md
  tutorials/triggered_publisher.md
  tutorials/video_recorder.md
Labels: 🏰 citadel

#1760 Final update of ignitionrobotics to gazebosim for citadel
  CMakeLists.txt
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Changelog.md
  NEWS
  docker/README.md
  docker/scripts/build_ign.sh
  docker/scripts/upload_json_benchmark.sh
Labels: 🏰 citadel

#1761 Removed unused speedlimit file
  src/systems/ackermann_steering/SpeedLimiter.hh
Labels: 🏯 fortress

#1727 Clarify errors when plugins fail to load
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
Labels: 🌱 garden

#1763 Add pybind11 module as MODULE
  python/CMakeLists.txt
Labels: 🌱 garden

#1764 Enable use of ign gazebo -s on Windows (take two)
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/ModelCommandAPI.hh
  src/cmd/cmdgazebo.rb.in
  src/cmd/cmdmodel.rb.in
  src/ign.hh
  src/ign_TEST.cc
  src/systems/CMakeLists.txt
Labels: 🏯 fortress

#1412 Script and tutorial for generating procedural datasets with Blender
  examples/scripts/blender/procedural_dataset_generator.py
  tutorials.md.in
  tutorials/blender_procedural_datasets.md
  tutorials/files/blender_procedural_datasets/blender_instructions.png
  tutorials/files/blender_procedural_datasets/demo_blender_rock.gif
  tutorials/files/blender_procedural_datasets/demo_blender_woodland.gif
  tutorials/files/blender_procedural_datasets/demo_gazebo_rock.png
  tutorials/files/blender_procedural_datasets/demo_gazebo_woodland.png
  tutorials/files/blender_procedural_datasets/rock.blend
  tutorials/files/blender_procedural_datasets/woodland.blend
Labels: documentation, enhancement, 🏯 fortress

#1766 Fix scene_broadcaster_system test
  test/worlds/shapes_scene_broadcaster_only.sdf
Labels: 🏯 fortress

#1767 Fix thruster integration test
  test/integration/thruster.cc
Labels: 🏯 fortress

#1772 Some minor changes to hydrodynamic flags test
  test/worlds/hydrodynamics_flags.sdf
Labels: 🏯 fortress
