Repository gazebosim/gz-sim, pull requests merged in 2023-10, with the labels that each got.

#2187 Remove direct dependency on libdart in CI
  .github/ci-focal/before_cmake.sh
  .github/ci/packages.apt
Labels: 🎵 harmonic

#1842 Fix enviroment system loading mechanism
  examples/worlds/CMakeLists.txt
  examples/worlds/environmental_sensor.sdf
  src/gui/plugins/environment_loader/EnvironmentLoader.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.hh
  src/systems/environment_preload/CMakeLists.txt
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environment_preload/VisualizationTool.cc
  src/systems/environment_preload/VisualizationTool.hh
Labels: needs upstream release, 🌱 garden

#2190 Bump Fuel model version in test
  src/SdfGenerator_TEST.cc
Labels: 🏰 citadel

#2191 Merge ign-gazebo3 ➡️ ign-gazebo6
  src/SdfGenerator_TEST.cc
  test/integration/save_world.cc
Labels: 🏯 fortress

#2172 Support specifying the name of light associated with lens flares
  src/systems/lens_flare/LensFlare.cc
  src/systems/lens_flare/LensFlare.hh
Labels: 🎵 harmonic

#2189 Lift Drag Bug Fix
  src/systems/lift_drag/LiftDrag.cc
  src/systems/lift_drag/LiftDrag.hh
Labels: 🌱 garden

#2197 Backport test fix to garden
  test/integration/save_world.cc
Labels: 🌱 garden

#2196 Relax pose check in flaky ActorTrajectoryNoMesh test
  test/integration/actor_trajectory.cc
Labels: 🌱 garden

#2210 Backport sensors system fixes
  src/systems/sensors/Sensors.cc
Labels: 🏯 fortress

#2183 Standardize Doxygen parameter formatting for systems A-N
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/acoustic_comms/AcousticComms.hh
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/breadcrumbs/Breadcrumbs.hh
  src/systems/buoyancy/Buoyancy.hh
  src/systems/buoyancy_engine/BuoyancyEngine.hh
  src/systems/camera_video_recorder/CameraVideoRecorder.hh
  src/systems/comms_endpoint/CommsEndpoint.hh
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/diff_drive/DiffDrive.hh
  src/systems/elevator/Elevator.hh
  src/systems/environment_preload/EnvironmentPreload.hh
  src/systems/follow_actor/FollowActor.hh
  src/systems/hydrodynamics/Hydrodynamics.hh
  src/systems/joint_controller/JointController.hh
  src/systems/joint_position_controller/JointPositionController.hh
  src/systems/joint_state_publisher/JointStatePublisher.hh
  src/systems/joint_traj_control/JointTrajectoryController.hh
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.hh
  src/systems/lens_flare/LensFlare.hh
  src/systems/lift_drag/LiftDrag.hh
  src/systems/log/LogPlayback.hh
  src/systems/log_video_recorder/LogVideoRecorder.hh
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.hh
  src/systems/mecanum_drive/MecanumDrive.hh
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/pose_publisher/PosePublisher.hh
  src/systems/user_commands/UserCommands.hh
Labels: documentation, 🎵 harmonic

#2176 Fix for sensor pointer null when navsat plugin in included in sdf
  src/Conversions.cc
Labels: 🏯 fortress
