Repository gazebosim/gz-sim, pull requests merged in 2023-02, with the labels that each got.

#1876 Add orientation to Odom with covariance.
  src/systems/odometry_publisher/OdometryPublisher.cc
  test/integration/odometry_publisher.cc
Labels: 🌱 garden

#1873 Add P gain value for Ackermann steering.
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  test/worlds/ackermann_steering_only.sdf
Labels: 🌱 garden

#1592 Fluid added mass
  examples/worlds/fluid_added_mass.sdf
  src/AddedMass_TEST.cc
  src/CMakeLists.txt
  src/Conversions.cc
  src/Util.cc
  src/gui/plugins/component_inspector/CMakeLists.txt
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector/ComponentInspector.qrc
  src/gui/plugins/component_inspector/Inertial.cc
  src/gui/plugins/component_inspector/Inertial.hh
  src/gui/plugins/component_inspector/Inertial.qml
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  test/integration/CMakeLists.txt
  test/integration/added_mass.cc
  test/integration/apply_link_wrench_system.cc
  test/worlds/added_mass_ellipsoids.sdf
  test/worlds/added_mass_full_matrix.sdf
  test/worlds/fluid_added_mass.sdf
  test/worlds/fluid_added_mass.sdf.erb
Labels: enhancement, physics, 🌱 garden, MBARI buoy

#1881 🎈 7.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1882 Fix cmake unrecognized argument warning
  CMakeLists.txt
Labels: 🌱 garden

#1874 Fix some windows warnings (C4244 and C4305)
  src/Conversions_TEST.cc
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
  test/integration/optical_tactile_plugin.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🏯 fortress

#1877 Fix view angle plugin
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.qml
Labels: 🌱 garden

#1884 cmdsim.rb: fix ruby syntax
  src/cmd/cmdsim.rb.in
Labels: 🌱 garden

#1851 Support nested joints in JointPositionController
  examples/worlds/nested_model_joint_positions.sdf
  src/systems/joint_position_controller/JointPositionController.cc
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller_nested_models.sdf
Labels: 🌱 garden

#1847 Added airspeed sensor
  CMakeLists.txt
  examples/worlds/sensors.sdf
  include/gz/sim/Util.hh
  include/gz/sim/components/AirSpeedSensor.hh
  src/Conversions.cc
  src/SdfEntityCreator.cc
  src/SdfGenerator.cc
  src/Util.cc
  src/systems/CMakeLists.txt
  src/systems/air_speed/AirSpeed.cc
  src/systems/air_speed/AirSpeed.hh
  src/systems/air_speed/CMakeLists.txt
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/CMakeLists.txt
  test/integration/air_speed_system.cc
  test/worlds/air_speed.sdf
Labels: 🌱 garden

#1895 Fix flaky triggered camera integration test
  test/integration/triggered_camera.cc
Labels: 🏯 fortress

#1896 🎈 7.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1897 Increase timeout for UNIT_Gui_clean_exit_TEST
  src/gui/CMakeLists.txt
Labels: 🌱 garden

#1899 Fix gz plugin paths in windows
  include/ignition/gazebo/config.hh
  src/systems/CMakeLists.txt
Labels: 🌱 garden

#1901 Partial backport of #1728
  test/integration/scene_broadcaster_system.cc
Labels: 🏯 fortress

#1902 Increase thread sleep delay
  src/gui/Gui_clean_exit_TEST.cc
Labels: 🌱 garden

#1888 Document behaviour changes introduced #1784
  examples/worlds/auv_controls.sdf
  examples/worlds/multi_lrauv_race.sdf
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  test/worlds/hydrodynamics.sdf
  test/worlds/hydrodynamics_flags.sdf
  tutorials/underwater_vehicles.md
Labels: 🏯 fortress

#1836 Use a queue to track component registration from mulitiple sources
  include/ignition/gazebo/components/Component.hh
  include/ignition/gazebo/components/Factory.hh
  src/CMakeLists.txt
  src/ComponentFactory.cc
  src/ComponentFactory_TEST.cc
Labels: 🏯 fortress

#1908 Add SensorTopic component to rendering sensors
  src/rendering/RenderUtil.cc
  test/integration/sensors_system.cc
Labels: 🏯 fortress
