Repository gazebosim/gz-sim, pull requests merged in 2023-11, with the labels that each got.

#2222 Update github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#2220 Fix macOS test failures by registering components in the core library
  src/SdfEntityCreator.cc
Labels: 🏰 citadel

#2225 Backport ActorTrajectoryNoMesh test fix
  test/integration/actor_trajectory.cc
Labels: 🏯 fortress

#2218 Implements a method to get the link inertia
  include/gz/sim/Link.hh
  python/src/gz/sim/Link.cc
  python/test/link_TEST.py
  src/Link.cc
  test/integration/link.cc
Labels: 🎵 harmonic

#2224 Port: 7 to 8
  examples/worlds/CMakeLists.txt
  examples/worlds/advanced_lift_drag_system.sdf
  examples/worlds/environmental_sensor.sdf
  src/gui/plugins/environment_loader/EnvironmentLoader.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.cc
  src/gui/plugins/environment_visualization/EnvironmentVisualization.hh
  src/systems/CMakeLists.txt
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.hh
  src/systems/advanced_lift_drag/CMakeLists.txt
  src/systems/environment_preload/CMakeLists.txt
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environment_preload/VisualizationTool.cc
  src/systems/environment_preload/VisualizationTool.hh
  src/systems/lift_drag/LiftDrag.cc
  src/systems/lift_drag/LiftDrag.hh
  src/systems/sensors/Sensors.cc
  test/integration/actor_trajectory.cc
  test/integration/reset_sensors.cc
Labels: 🎵 harmonic

#2227 Add note about elevator example
  examples/worlds/elevator.sdf
Labels: 🌱 garden

#2230 Use `GZ_PI` instead of `M_PI` to fix windows builds
  examples/standalone/marker/marker.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  test/integration/added_mass.cc
Labels: 🌱 garden

#2212 Standardize Doxygen parameter formatting for systems O-Z
  src/systems/buoyancy_engine/BuoyancyEngine.hh
  src/systems/odometry_publisher/OdometryPublisher.hh
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.hh
  src/systems/particle_emitter/ParticleEmitter.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.hh
  src/systems/python_system_loader/PythonSystemLoader.hh
  src/systems/rf_comms/RFComms.hh
  src/systems/sensors/Sensors.hh
  src/systems/shader_param/ShaderParam.hh
  src/systems/thruster/Thruster.hh
  src/systems/touch_plugin/TouchPlugin.hh
  src/systems/track_controller/TrackController.hh
  src/systems/tracked_vehicle/TrackedVehicle.hh
  src/systems/trajectory_follower/TrajectoryFollower.hh
  src/systems/triggered_publisher/TriggeredPublisher.hh
  src/systems/velocity_control/VelocityControl.hh
  src/systems/wheel_slip/WheelSlip.hh
  src/systems/wind_effects/WindEffects.hh
Labels: documentation, 🎵 harmonic

#2233 Add libpython3-dev CI dependency
  .github/ci/packages.apt
  src/SimulationRunner.cc
Labels: 🎵 harmonic

#2234 Merge gz-sim7 ➡️ gz-sim8
  examples/standalone/marker/marker.cc
  examples/worlds/elevator.sdf
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  test/integration/added_mass.cc
Labels: 🎵 harmonic

#2226 wind addition to advanced_lift_drag plugin
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.hh
Labels: 🌱 garden

#2236 Backport #2231 to garden: use sdf FindElement API to avoid const_cast
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/joint_traj_control/JointTrajectoryController.cc
  src/systems/log/LogRecord.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/shader_param/ShaderParam.cc
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/velocity_control/VelocityControl.cc
Labels: 🌱 garden

#2242 Merge gz-sim7 ➡️ gz-sim8
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.hh
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_state_publisher/JointStatePublisher.cc
  src/systems/joint_traj_control/JointTrajectoryController.cc
  src/systems/log/LogRecord.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/shader_param/ShaderParam.cc
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/velocity_control/VelocityControl.cc
Labels: 🎵 harmonic

#2182 Bugfix: Fixed Centre of Mass and Inertia Matrix Calculation Bug `MeshInertiaCalculator::CalculateMassProperties()` function
  src/MeshInertiaCalculator.cc
  src/MeshInertiaCalculator.hh
  test/integration/mesh_inertia_calculation.cc
  test/worlds/mesh_inertia_calculation.sdf
  test/worlds/models/cylinder_dae_bottom_origin/meshes/cylinder_bottom_origin.dae
  test/worlds/models/cylinder_dae_bottom_origin/model.config
  test/worlds/models/cylinder_dae_bottom_origin/model.sdf
  tutorials/auto_inertia_calculation.md
Labels: 🎵 harmonic

#2245 EnvironmentPreload: ignerr -> gzerr
  src/systems/environment_preload/EnvironmentPreload.cc
Labels: 🌱 garden

#2237 Update Github Action workflows
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#2246 environment_preload: fix windows compiler warnings
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environment_preload/VisualizationTool.cc
  src/systems/environment_preload/VisualizationTool.hh
Labels: 🌱 garden

#2247 Disable distortion camera test on Linux
  test/integration/distortion_camera.cc
Labels: 🎵 harmonic

#2250 mecanum_drive: use mesh wheels in example world
  examples/worlds/mecanum_drive.sdf
Labels: 🌱 garden

#2254 Fix DLL linkage/visibility issues
  src/CMakeLists.txt
  src/cmd/runGui_main.cc
  src/gz.cc
Labels: 🌱 garden

#2252 Allow removal of model that has joint_position_controller plugin.
  src/systems/joint_position_controller/JointPositionController.cc
Labels: 🎵 harmonic
