Repository gazebosim/gz-sim, pull requests merged in 2023-01, with the labels that each got.

#1853 Fix SdfGenerator unit test
  src/SdfGenerator_TEST.cc
Labels: 🌱 garden

#1854 Minor optimization to transform control tool
  src/gui/plugins/transform_control/TransformControl.cc
Labels: 🏯 fortress

#1858 Add ignition alias back
  src/systems/thruster/Thruster.cc
Labels: 🌱 garden

#1857 port: 6 to 7 (10-JAN-2023)
  CMakeLists.txt
  Changelog.md
  include/gz/sim/System.hh
  include/gz/sim/components/BatteryPowerLoad.hh
  include/ignition/gazebo/components/BatteryPowerLoad.hh
  src/CMakeLists.txt
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/view_angle/ViewAngle.hh
  src/gui/plugins/view_angle/ViewAngle.qml
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/battery_plugin/LinearBatteryPlugin.hh
  src/systems/thruster/Thruster.cc
  test/integration/battery_plugin.cc
  test/integration/hydrodynamics.cc
  test/integration/hydrodynamics_flags.cc
  test/worlds/battery.sdf
  test/worlds/battery_thruster_consumer.sdf
  tutorials.md.in
  tutorials/battery.md
  tutorials/files/move_camera_to_model/box_20.png
  tutorials/files/move_camera_to_model/box_5.png
  tutorials/files/move_camera_to_model/move_to_model.gif
  tutorials/move_camera_to_model.md
Labels: 🌱 garden

#1735 Add CLI to switch to Vulkan & Metal backends
  include/gz/sim/ServerConfig.hh
  include/gz/sim/components/RenderEngineServerApiBackend.hh
  include/gz/sim/gui/Gui.hh
  include/gz/sim/rendering/RenderUtil.hh
  src/LevelManager.cc
  src/ServerConfig.cc
  src/cmd/cmdsim.rb.in
  src/gui/Gui.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector_editor/ComponentInspectorEditor.cc
  src/gz.cc
  src/gz.hh
  src/rendering/RenderUtil.cc
  src/systems/sensors/Sensors.cc
Labels: needs upstream release

#1597 GUI for Global Illumination (VCT / CI VCT)
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/global_illumination_civct/CMakeLists.txt
  src/gui/plugins/global_illumination_civct/CiVctCascadePrivate.cc
  src/gui/plugins/global_illumination_civct/CiVctCascadePrivate.hh
  src/gui/plugins/global_illumination_civct/CiVctCascadePrivate.qml
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.cc
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.hh
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.qml
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.qrc
  src/gui/plugins/global_illumination_civct/Tsa.hh
  src/gui/plugins/global_illumination_vct/CMakeLists.txt
  src/gui/plugins/global_illumination_vct/GlobalIlluminationVct.cc
  src/gui/plugins/global_illumination_vct/GlobalIlluminationVct.hh
  src/gui/plugins/global_illumination_vct/GlobalIlluminationVct.qml
  src/gui/plugins/global_illumination_vct/GlobalIlluminationVct.qrc
Labels: enhancement, GUI, needs upstream release

#1860 Ackermann steering with steering angle and sub_topic.
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  test/integration/ackermann_steering_system.cc
  test/worlds/ackermann_steering_only.sdf
  test/worlds/ackermann_steering_only_custom_sub_topics.sdf
Labels: 🌱 garden

#1861 Enable the JointController and JointPositionController to use sub_topics and control multiple joints.
  src/systems/joint_controller/JointController.cc
  src/systems/joint_controller/JointController.hh
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_position_controller/JointPositionController.hh
  test/integration/joint_controller_system.cc
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_controller.sdf
  test/worlds/joint_position_controller_multiple_joints_subtopic.sdf
Labels: 🌱 garden

#1869 Prepare for 7.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden
