Repository gazebosim/gz-sim, pull requests merged in 2023-06, with the labels that each got.

#1687 Allow re-attaching detached joint
  examples/worlds/detachable_joint.sdf
  examples/worlds/triggered_publisher.sdf
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  test/integration/detachable_joint.cc
  test/worlds/detachable_joint.sdf
  tutorials/detachable_joints.md
  tutorials/triggered_publisher.md
Labels: enhancement, 🏯 fortress

#2004 Port record topic fix
  src/ServerPrivate.cc
Labels: 🏯 fortress

#2012 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: 🌱 garden

#1998 Print an error message when trying to load SDF files that don't contain a `<world>`
  src/Server.cc
  src/Server_TEST.cc
Labels: 🏰 citadel

#2005 Disable pybind11 on Windows by default
  CMakeLists.txt
Labels: 🏯 fortress

#1949 Support world joints (joints inside <world> tags)
  src/LevelManager.cc
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/worlds/joints_in_world.sdf
Labels: 🌱 garden

#2006 Protobuf: Do not require version 3 do support Protobuf 4.23.2 (23.2)
  CMakeLists.txt
  src/systems/triggered_publisher/TriggeredPublisher.cc
Labels: 🏯 fortress

#2013 Merge ign-gazebo3 ➡️ ign-gazebo6
  .github/workflows/ci.yml
  Changelog.md
  src/CMakeLists.txt
  src/Server.cc
  src/Server_TEST.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gz.cc
  src/rendering/MarkerManager.cc
  test/integration/CMakeLists.txt
  test/integration/markers.cc
Labels: 🏯 fortress

#2020 Cherry-pick #2006 to garden: fix finding new protobuf
  CMakeLists.txt
  src/systems/triggered_publisher/TriggeredPublisher.cc
Labels: 🌱 garden

#2017 Backport #2006 to citadel: Fix finding new versions of protobuf
  CMakeLists.txt
  src/systems/triggered_publisher/TriggeredPublisher.cc
Labels: 🏰 citadel
