Repository gazebosim/gz-sim, pull requests merged in 2023-03, with the labels that each got.

#1824 Added reset simulation tutorial
  examples/plugin/system_plugin/SampleSystem.hh
  examples/plugin/system_plugin/SampleSystem2.cc
  tutorials.md.in
  tutorials/create_system_plugins.md
  tutorials/files/reset_simulation/reset_button.gif
  tutorials/reset_simulation.md
Labels: 🌱 garden

#1910 Add Joint class
  include/ignition/gazebo/Joint.hh
  src/CMakeLists.txt
  src/Joint.cc
  src/Joint_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/joint.cc
Labels: 🏯 fortress

#1801 Allow specifying initial simulation time with a CLI argument
  include/gz/sim/ServerConfig.hh
  src/ServerConfig.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/cmd/cmdsim.rb.in
  src/gz.cc
  src/gz.hh
  src/gz_TEST.cc
Labels: enhancement, 🌱 garden

#1907 Added magnetometer value based on location
  src/systems/magnetometer/Magnetometer.cc
Labels: 🌱 garden

#1911 Address a few Windows CI Issues
  include/gz/sim/detail/EntityComponentManager.hh
  src/cmd/ModelCommandAPI.hh
  src/gz.hh
  test/integration/hydrodynamics.cc
Labels: 🌱 garden

#1915 Minor terminology fix in tutorial
  tutorials/migrating_ardupilot_plugin.md
Labels: 🌱 garden

#1912 Add Sensor class
  include/ignition/gazebo/Joint.hh
  include/ignition/gazebo/Sensor.hh
  src/CMakeLists.txt
  src/Joint.cc
  src/Sensor.cc
  src/Sensor_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/joint.cc
  test/integration/sensor.cc
Labels: 🏯 fortress

#1868 Update all velocity and acceleration components of non-link entities
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/worlds/non_link_components.sdf
Labels: 🌱 garden

#1913 Add Actor class
  include/ignition/gazebo/Actor.hh
  src/Actor.cc
  src/Actor_TEST.cc
  src/CMakeLists.txt
  src/rendering/RenderUtil.cc
  test/integration/CMakeLists.txt
  test/integration/actor.cc
Labels: 🏯 fortress

#1654 Fix overflow if dropStr is large
  src/gui/plugins/spawn/Spawn.cc
Labels: bug, 🌱 garden

#1921 Fix off-by-one error in physics test
  test/integration/physics_system.cc
Labels: 🌱 garden

#1920 Fix flaky RF comms test by relaxing the check for msg counter
  test/integration/rf_comms.cc
Labels: 🏯 fortress

#1914 Resolve inconsistent visibility on ign-gazebo6
  src/cmd/ModelCommandAPI.hh
  src/ign.hh
Labels: 🏯 fortress

#1892 Bump msgs, transport, and fuel-tools version in Harmonic
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  docker/Dockerfile.nightly
  examples/standalone/acoustic_comms_demo/CMakeLists.txt
  examples/standalone/comms/CMakeLists.txt
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  tutorials/migrating_ardupilot_plugin.md
Labels: 🎵 harmonic

#1804 Add DopplerVelocityLogSystem plugin
  CMakeLists.txt
  include/gz/sim/components/Environment.hh
  src/CMakeLists.txt
  src/components/Environment.cc
  src/systems/CMakeLists.txt
  src/systems/dvl/CMakeLists.txt
  src/systems/dvl/DopplerVelocityLogSystem.cc
  src/systems/dvl/DopplerVelocityLogSystem.hh
  test/helpers/ModelManipulator.hh
  test/helpers/ModelObserver.hh
  test/helpers/Subscription.hh
  test/helpers/TestFixture.hh
  test/integration/CMakeLists.txt
  test/integration/dvl_system.cc
  test/integration/dvl_system_bottom_tracking.cc
  test/integration/dvl_system_water_mass_tracking.cc
  test/worlds/bottomless_pit.sdf
  test/worlds/flat_seabed.sdf
  test/worlds/underwater_currents.csv
  test/worlds/underwater_currents.sdf
Labels: MBARI-LRAUV, 🎵 harmonic

#1918 Add Light class
  include/ignition/gazebo/Light.hh
  src/CMakeLists.txt
  src/Light.cc
  src/Light_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/light.cc
  test/integration/sensor.cc
Labels: 🏯 fortress

#1917 Get Windows to green on gz-sim7
  src/CMakeLists.txt
  src/SdfGenerator_TEST.cc
  test/benchmark/each.cc
  test/benchmark/ecm_serialize.cc
Labels: 🌱 garden

#1922 Fix TopicInfo deprecation warnings in Harmonic
  src/SimulationRunner.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  test/integration/sensors_system.cc
Labels: 🎵 harmonic

#1935 Add comment about buoyancy force location to underwater tutorial
  tutorials/underwater_vehicles.md
Labels: 🌱 garden

#1937 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#1943 Initialize services in ViewAngle constructor
  src/gui/plugins/view_angle/ViewAngle.cc
Labels: 🌱 garden

#1944 Merge ign-gazebo3 ➡️ ign-gazebo6
  .github/workflows/ci.yml
  COPYING
  LICENSE
Labels: 🏯 fortress

#1939 Cherry-Pick #1836: Use a queue to track component registration from multiple sources
  include/gz/sim/components/Component.hh
  include/gz/sim/components/Factory.hh
  src/CMakeLists.txt
  src/ComponentFactory.cc
  src/ComponentFactory_TEST.cc
Labels: 🌱 garden

#1916 gz_TEST: improve initial sim time test reliability
  src/gz_TEST.cc
Labels: 🌱 garden

#1945 Merge 6 ➡️ 7 part 1
  .github/CODEOWNERS
  examples/worlds/auv_controls.sdf
  examples/worlds/multi_lrauv_race.sdf
  include/gz/sim/Types.hh
  src/EntityComponentManager_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/resources/GazeboDrawer.qml
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
  src/systems/shader_param/ShaderParam.cc
  test/integration/battery_plugin.cc
  test/integration/joint_position_controller_system.cc
  test/integration/optical_tactile_plugin.cc
  test/integration/triggered_camera.cc
  test/worlds/hydrodynamics.sdf.in
  test/worlds/hydrodynamics_flags.sdf
  tutorials/migration_sdf.md
  tutorials/underwater_vehicles.md
Labels: 🌱 garden
