Repository gazebosim/gz-sim, pull requests merged in 2023-09, with the labels that each got.

#2108 Fix broken links in terminology tutorial (Garden)
  tutorials/terminology.md
Labels: 🌱 garden

#2113 Remove GZ_PHYSICS_ENGINE_INSTALL_DIR deprecation warnings
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  test/integration/tracked_vehicle_system.cc
Labels: beta, 🌱 garden

#2114 Fix typos in underwater vehicles tutorial
  tutorials/underwater_vehicles.md
Labels: 🎵 harmonic

#2115 Fix default topic name of JointStatePublisher
  src/systems/joint_state_publisher/JointStatePublisher.hh
Labels: 🌱 garden

#2116 Add link to existing issue
  tutorials/terminology.md
Labels: 🌱 garden

#2120 Fix thrust cmd topic in underwater tutorial
  tutorials/underwater_vehicles.md
Labels: 🌱 garden

#2122 Removed warning in sensors_demos.sdf
  examples/worlds/sensors_demo.sdf
Labels: 🎵 harmonic

#2121 Fixed invalid service names
  src/SimulationRunner.cc
  src/systems/user_commands/UserCommands.cc
Labels: 🎵 harmonic

#2126 Fix camera move to model
  src/gui/plugins/view_angle/ViewAngle.cc
  tutorials/move_camera_to_model.md
Labels: 🌱 garden

#2124 Update README.md
  README.md
Labels: 🎵 harmonic

#2127 Update link in particles tutorial
  tutorials/particle_tutorial.md
Labels: 🎵 harmonic

#2130 Update triggered_publisher.md
  tutorials/triggered_publisher.md
Labels: 🎵 harmonic

#2129 Remove sdformat diff drive warning
  examples/worlds/diff_drive.sdf
Labels: 🎵 harmonic

#2133 Fixes the link for the Hardware Acceleration Tutorial
  tutorials/video_recorder.md
Labels: 🎵 harmonic

#2134 Use default physics engine in example worlds
  examples/worlds/nested_model.sdf
  examples/worlds/particle_emitter.sdf
Labels: 🌱 garden

#2128 Update underwater_vehicles.md
  tutorials/underwater_vehicles.md
Labels: 🎵 harmonic

#2101 Fix duplicate entries in joint position controller GUI plugin
  src/gui/plugins/joint_position_controller/JointPositionController.cc
Labels: beta, 🌱 garden

#2123 Removed python trace
  examples/scripts/python_api/systems/test_system.py
  tutorials/python_interfaces.md
Labels: 🎵 harmonic

#2139 Load transform control and select entities plugins in thermal camera world
  examples/worlds/thermal_camera.sdf
Labels: 🎵 harmonic

#2135 Update video recorder tutorial screenshot
  tutorials/files/video_recorder/video_recorder.png
  tutorials/video_recorder.md
Labels: 🌱 garden

#2138 Voldivh/model command output update
  tutorials/model_command.md
Labels: 🌱 garden

#2111 Fix multi_lrauv_race example
  examples/standalone/multi_lrauv_race/multi_lrauv_race.cc
  examples/worlds/multi_lrauv_race.sdf
Labels: beta, 🎵 harmonic

#2143 Add note about Featherstone
  tutorials/physics.md
Labels: beta, 🎵 harmonic

#2145 Fix CMake warning in example
  examples/plugin/hello_world/CMakeLists.txt
Labels: 🎵 harmonic

#2144 Improve joint controller world visualization
  examples/worlds/joint_controller.sdf
Labels: 🎵 harmonic

#2148 Update Logging tutorial
  tutorials/log.md
Labels: 🎵 harmonic

#2147 Update Reset simulation tutorial
  tutorials/reset_simulation.md
Labels: 🎵 harmonic

#2150 Update triggered publisher tutorial
  tutorials/triggered_publisher.md
Labels: 🎵 harmonic

#2149 Fix light_control example and update tutorial
  examples/standalone/light_control/light_control.cc
  tutorials/light_config.md
Labels: 🎵 harmonic

#2151 Fix reset button in examples
  examples/worlds/boundingbox_camera.sdf
  examples/worlds/camera_sensor.sdf
  examples/worlds/dem_monterey_bay.sdf
  examples/worlds/dem_moon.sdf
  examples/worlds/dem_volcano.sdf
  examples/worlds/depth_camera_sensor.sdf
  examples/worlds/fuel_textured_mesh.sdf
  examples/worlds/grid.sdf
  examples/worlds/lrauv_control_demo.sdf
  examples/worlds/minimal_scene.sdf
  examples/worlds/optical_tactile_sensor_plugin.sdf
  examples/worlds/plot_3d.sdf
  examples/worlds/projector.sdf
  examples/worlds/resource_spawner.sdf
  examples/worlds/segmentation_camera.sdf
  examples/worlds/sensors_demo.sdf
  examples/worlds/shader_param.sdf
  examples/worlds/sky.sdf
  examples/worlds/spherical_coordinates.sdf
  examples/worlds/triggered_camera_sensor.sdf
  examples/worlds/tunnel.sdf
  examples/worlds/video_record_dbl_pendulum.sdf
  examples/worlds/visibility.sdf
  examples/worlds/visualize_contacts.sdf
  examples/worlds/visualize_lidar.sdf
  examples/worlds/wide_angle_camera.sdf
Labels: 🎵 harmonic

#2141 Fix another deadlock in sensors system
  src/systems/sensors/Sensors.cc
Labels: beta, 🎵 harmonic

#2119 Added tutorial for Automatic Inertia Calculator
  examples/worlds/auto_inertia_pendulum.sdf
  examples/worlds/auto_inertia_rolling_shapes.sdf
  tutorials.md.in
  tutorials/auto_inertia_calculation.md
  tutorials/files/auto_inertia/auto_inertia_pendulum.gif
  tutorials/files/auto_inertia/cylinder_inertia_demo.gif
  tutorials/files/auto_inertia/rolling_inertia_demo.gif
Labels: documentation, beta, 🎵 harmonic

#2157 Fix example output in python tutorial
  tutorials/python_interfaces.md
Labels: beta, 🎵 harmonic

#2156 Fix SDFormat xml output of sdf_exporter
  examples/scripts/blender/sdf_exporter.py
Labels: beta, 🌱 garden

#2159 Backport reset button fix
  examples/plugin/rendering_plugins/rendering_plugins.sdf
  examples/scripts/log_video_recorder/log_video_recorder.sdf
  examples/worlds/boundingbox_camera.sdf
  examples/worlds/camera_sensor.sdf
  examples/worlds/dem_monterey_bay.sdf
  examples/worlds/dem_moon.sdf
  examples/worlds/dem_volcano.sdf
  examples/worlds/depth_camera_sensor.sdf
  examples/worlds/fuel_textured_mesh.sdf
  examples/worlds/grid.sdf
  examples/worlds/lrauv_control_demo.sdf
  examples/worlds/minimal_scene.sdf
  examples/worlds/optical_tactile_sensor_plugin.sdf
  examples/worlds/plot_3d.sdf
  examples/worlds/projector.sdf
  examples/worlds/resource_spawner.sdf
  examples/worlds/segmentation_camera.sdf
  examples/worlds/sensors_demo.sdf
  examples/worlds/shader_param.sdf
  examples/worlds/sky.sdf
  examples/worlds/spherical_coordinates.sdf
  examples/worlds/thermal_camera.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  examples/worlds/triggered_camera_sensor.sdf
  examples/worlds/tunnel.sdf
  examples/worlds/video_record_dbl_pendulum.sdf
  examples/worlds/visibility.sdf
  examples/worlds/visualize_contacts.sdf
  examples/worlds/visualize_lidar.sdf
  examples/worlds/wide_angle_camera.sdf
  src/gui/playback_gui.config
Labels: 🌱 garden

#2158 Merge gz-sim7 ➡️ gz-sim8
  examples/scripts/blender/sdf_exporter.py
  examples/worlds/nested_model.sdf
  examples/worlds/particle_emitter.sdf
  src/gui/plugins/joint_position_controller/JointPositionController.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/systems/joint_state_publisher/JointStatePublisher.hh
  tutorials/files/video_recorder/video_recorder.png
  tutorials/move_camera_to_model.md
  tutorials/terminology.md
  tutorials/video_recorder.md
Labels: 🎵 harmonic

#2169 Fix image sizes in apply_force_torque tutorial
  tutorials/apply_force_torque.md
Labels: beta, 🌱 garden

#2173 Prepare for 7.6.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#2175 Merge: 7 -> 8
  Changelog.md
  examples/plugin/rendering_plugins/rendering_plugins.sdf
  examples/scripts/log_video_recorder/log_video_recorder.sdf
  examples/worlds/tracked_vehicle_simple.sdf
  src/gui/playback_gui.config
  test/integration/save_world.cc
  tutorials/apply_force_torque.md
Labels: beta, 🎵 harmonic

#2132 TouchPlugin: Reset the plugin with the initial values
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/touch_plugin/TouchPlugin.hh
Labels: beta, 🎵 harmonic

#2171 Bugfix: Updated Mesh Inertia Calculator to incorporate mesh scale in the calculations
  src/MeshInertiaCalculator.cc
  src/MeshInertiaCalculator.hh
Labels: beta, 🎵 harmonic

#2166 Server: explicitly skip auto-inertial calculation
  src/Server.cc
Labels: beta, 🎵 harmonic

#2178 Prepare for 8.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🎵 harmonic

#2181 Prepare for 8.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
