Repository gazebosim/gz-sim, pull requests merged in 2023-07, with the labels that each got.

#2027 Several minor fixes
  src/ServerConfig.cc
  src/SystemLoader_TEST.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/buoyancy/Buoyancy.cc
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/multicopter_control/MulticopterVelocityControl.hh
  src/systems/performer_detector/PerformerDetector.hh
  src/systems/physics/Physics.cc
  src/systems/sensors/Sensors.cc
  src/systems/thruster/Thruster.cc
  src/systems/triggered_publisher/TriggeredPublisher.cc
  test/integration/log_system.cc
  test/test_config.hh.in
  tutorials/battery.md
Labels: 🌱 garden

#1968 Add optional binary relocatability
  include/gz/sim/InstallationDirectories.hh
  include/gz/sim/config.hh.in
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  src/ServerConfig.cc
  src/SystemLoader.cc
  src/Util.cc
  src/gui/CMakeLists.txt
  src/gui/Gui.cc
  src/gui/QuickStartHandler.cc
  src/gui/QuickStartHandler.hh
  src/gui/plugins/CMakeLists.txt
  src/gz.cc
  src/systems/environmental_sensor_system/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/CMakeLists.txt
  src/systems/physics/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden

#2025 Prevent deadlock in sensors system
  src/systems/sensors/Sensors.cc
Labels: 🌱 garden

#2028 Categorize tutorials list
  tutorials.md.in
  tutorials/gui_config.md
  tutorials/install.md
  tutorials/light_config.md
  tutorials/model_command.md
  tutorials/model_photo_shoot.md
  tutorials/python_interfaces.md
  tutorials/reset_simulation.md
  tutorials/underwater_vehicles.md
Labels: documentation, 🌱 garden

#2030 Fix TransformControl's BlockOrbit behavior
  src/gui/plugins/transform_control/TransformControl.cc
Labels: 🌱 garden

#2032 ComponentInspector: display PhysicsEnginePlugin
  src/gui/plugins/component_inspector/ComponentInspector.cc
Labels: 🌱 garden

#2007 Support loading mesh by mesh name in <mesh><uri>
  include/gz/sim/Util.hh
  src/Util.cc
  src/Util_TEST.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/mesh_uri.cc
  test/worlds/camera_sensor_scene_background.sdf
  tutorials/resources.md
Labels: 🌱 garden

#2046 Disable Focal on Harmonic
  .github/workflows/ci.yml
Labels: 🎵 harmonic

#2047 Adds a warning if the `Server` method of a `TestFixture` is called before `Finalize`
  src/TestFixture.cc
Labels: 🏰 citadel

#2014 Apply Force and Torque GUI plugin
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.hh
  src/gui/plugins/apply_force_torque/ApplyForceTorque.qml
  src/gui/plugins/apply_force_torque/ApplyForceTorque.qrc
  src/gui/plugins/apply_force_torque/CMakeLists.txt
Labels: 🌱 garden

#2049 Change type of `Component::typeName` and address outstanding todos
  Migration.md
  include/gz/sim/components/Component.hh
  include/gz/sim/components/Factory.hh
  src/ComponentFactory.cc
  src/ComponentFactory_TEST.cc
  src/Component_TEST.cc
  src/SimulationRunner_TEST.cc
Labels: 🎵 harmonic

#2059 Fix const-correctness of the `Model::JointByName` and `Model::LinkByName` APIs
  include/gz/sim/Model.hh
  src/Model.cc
Labels: 🎵 harmonic

#2058 Backport sensors system threading optimization changes
  include/gz/sim/EventManager.hh
  src/EventManager_TEST.cc
  src/systems/sensors/Sensors.cc
  test/integration/CMakeLists.txt
  test/integration/sensors_system_update_rate.cc
  test/worlds/sensor.sdf
Labels: 🏯 fortress

#2052 Use sdf::Element::FindElement instead of GetElement in ApplyLinkWrench
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
Labels: 🏰 citadel

#2064 Use new API for creating a Projector
  src/rendering/SceneManager.cc
Labels: beta, 🎵 harmonic

#2063 Use ogre2 in wide angle camera and lens flares worlds
  examples/worlds/wide_angle_camera.sdf
  test/worlds/camera_lens_flare.sdf
  test/worlds/wide_angle_camera_sensor.sdf
Labels: beta, 🎵 harmonic
