Repository gazebosim/gz-sim, pull requests merged in 2023-08, with the labels that each got.

#2067 Fix a minor issue in the documentation of the server API
  include/gz/sim/Server.hh
Labels: 🏰 citadel

#2066 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#2001 Fix Joint Position Controller Behaviour Described in #1997
  include/gz/sim/EntityComponentManager.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller_velocity.sdf
Labels: beta, 🏯 fortress

#2070 Remove unnecessary headers to fix ABI checker
  include/ignition/gazebo/ign/gazebo/Export.hh
  include/ignition/gazebo/ignition/gazebo/Export.hh
Labels: beta, 🌱 garden

#2069 Avoid nullptr dereference if TouchPlugin is not attached to a model entity.
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/touch_plugin/TouchPlugin.hh
Labels: beta, 🌱 garden

#2053 Remove deprecations and address some todos for Harmonic
  CMakeLists.txt
  include/gz/sim/Events.hh
  include/gz/sim/ServerConfig.hh
  include/gz/sim/SystemLoader.hh
  include/gz/sim/TestFixture.hh
  include/gz/sim/gui/GuiEvents.hh
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/ServerConfig.cc
  src/Server_TEST.cc
  src/SystemLoader.cc
  src/TestFixture.cc
  src/gui/GuiEvents.cc
  src/gui/GuiRunner.cc
  src/gui/plugins/scene_manager/GzSceneManager.cc
  src/systems/CMakeLists.txt
  src/systems/air_speed/AirSpeed.cc
  src/systems/lens_flare/LensFlare.cc
  src/systems/particle_emitter2/CMakeLists.txt
  src/systems/particle_emitter2/ParticleEmitter2.cc
  src/systems/particle_emitter2/ParticleEmitter2.hh
  test/integration/deprecated_TEST.cc
Labels: beta, 🎵 harmonic

#2060 Use new sky cubemap, instead of header
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: beta, 🎵 harmonic

#1927 Proposal to add deadband to thruster
  src/systems/thruster/Thruster.cc
  src/systems/thruster/Thruster.hh
  test/integration/thruster.cc
  test/worlds/thruster_deadband.sdf
Labels: beta, 🌱 garden

#2062 Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-sim8
  .github/ci/packages.apt
  CMakeLists.txt
  docker/Dockerfile.nightly
  examples/scripts/python_api/testFixture.py
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  src/SdfEntityCreator.cc
  tutorials/blender_distort_meshes.md
  tutorials/blender_sdf_exporter.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/python_interfaces.md
  tutorials/reset_simulation.md
Labels: beta, 🎵 harmonic

#2035 Adds bindings for the world convenience class
  .github/ci/packages.apt
  python/CMakeLists.txt
  python/src/gz/sim/World.cc
  python/test/gz_test_deps/__init__.py
  python/test/gz_test_deps/math.py
  python/test/gz_test_deps/sdformat.py
  python/test/gz_test_deps/sim.py
  python/test/world_TEST.py
  python/test/world_test.sdf
Labels: beta

#2026 Add force offset support to ApplyLinkWrench system and to Link API
  include/gz/sim/Link.hh
  src/Link.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.hh
  test/integration/link.cc
Labels: beta, 🌱 garden

#2036 Adds bindings for the model convenience class
  python/CMakeLists.txt
  python/src/gz/sim/Model.cc
  python/src/gz/sim/Model.hh
  python/src/gz/sim/World.cc
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/model_TEST.py
  python/test/model_test.sdf
  python/test/world_TEST.py
Labels: beta

#2077 Prevent printing misleading error msg in visualize lidar gui plugin
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: 🌱 garden

#2078 Merge ign-gazebo3 ➡️ ign-gazebo6
  include/gz/sim/Server.hh
  src/TestFixture.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
Labels: 🏯 fortress

#2054 Harmonic: Address some todos
  src/Conversions.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/systems/air_speed/AirSpeed.cc
  test/integration/air_speed_system.cc
Labels: beta, 🎵 harmonic

#2039 Adds bindings for the Link convenience class
  python/CMakeLists.txt
  python/src/gz/sim/Link.cc
  python/src/gz/sim/Link.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/link_TEST.py
  python/test/link_test.sdf
  python/test/model_TEST.py
  python/test/world_TEST.py
Labels: beta

#2080 Prepare for 6.15.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#2040 Adds bindings for the Joint convenience class
  include/gz/sim/Joint.hh
  python/CMakeLists.txt
  python/src/gz/sim/Joint.cc
  python/src/gz/sim/Joint.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/joint_TEST.py
  python/test/joint_test.sdf
Labels: beta

#2038 Add new MouseDrag plugin
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/mouse_drag/CMakeLists.txt
  src/gui/plugins/mouse_drag/MouseDrag.cc
  src/gui/plugins/mouse_drag/MouseDrag.hh
  src/gui/plugins/mouse_drag/MouseDrag.qml
  src/gui/plugins/mouse_drag/MouseDrag.qrc
Labels: beta, 🌱 garden

#2075 Add non concurrency to Ubuntu CI workflow
  .github/workflows/ci.yml
Labels: 🌱 garden

#2042 Adds bindings for the Sensor convenience class
  python/CMakeLists.txt
  python/src/gz/sim/Sensor.cc
  python/src/gz/sim/Sensor.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/joint_test.sdf
  python/test/sensor_TEST.py
Labels: beta

#2057 Configurable stiffnesses in MouseDrag
  src/gui/plugins/mouse_drag/MouseDrag.cc
  src/gui/plugins/mouse_drag/MouseDrag.hh
  src/gui/plugins/mouse_drag/MouseDrag.qml
Labels: beta, 🌱 garden

#1698 Improve documentation on how to replace Scene3D plugin
  Migration.md
  src/gui/Gui.cc
Labels: beta, 🌱 garden

#2041 Adds bindings for the Actor convenience class
  include/gz/sim/Actor.hh
  python/CMakeLists.txt
  python/src/gz/sim/Actor.cc
  python/src/gz/sim/Actor.hh
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/actor_TEST.py
  python/test/actor_test.sdf
Labels: beta

#2051 Visualization tools for ApplyForceTorque
  include/gz/sim/rendering/WrenchVisualizer.hh
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.hh
  src/gui/plugins/apply_force_torque/ApplyForceTorque.qml
  src/gui/plugins/apply_force_torque/CMakeLists.txt
  src/rendering/CMakeLists.txt
  src/rendering/WrenchVisualizer.cc
Labels: beta, 🌱 garden

#2093 Add version number to gz.common python binding
  examples/scripts/python_api/testFixture.py
  python/CMakeLists.txt
  python/src/gz/common/_gz_common_pybind11.cc
  python/src/gz/sim/TestFixture.cc
  python/test/actor_TEST.py
  python/test/gz_test_deps/common.py
  python/test/joint_TEST.py
  python/test/link_TEST.py
  python/test/model_TEST.py
  python/test/sensor_TEST.py
  python/test/testFixture_TEST.py
  python/test/world_TEST.py
Labels: beta, 🎵 harmonic

#2094 Fix plugin conversion error message
  src/SimulationRunner.cc
  src/TestFixture_TEST.cc
Labels: beta, 🌱 garden

#2056 Force offset and vector magnitude support in ApplyForceTorque
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.hh
  src/gui/plugins/apply_force_torque/ApplyForceTorque.qml
  src/rendering/WrenchVisualizer.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
Labels: beta, 🌱 garden

#2043 Adds Python bindings for the Light convenience class
  include/gz/sim/Light.hh
  python/CMakeLists.txt
  python/src/gz/sim/Light.cc
  python/src/gz/sim/Light.hh
  python/src/gz/sim/Link.cc
  python/src/gz/sim/_gz_sim_pybind11.cc
  python/test/light_TEST.py
  python/test/light_test.sdf
Labels: beta

#2097 Prevent crash when viewing heightmap collision
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
Labels: beta, 🌱 garden

#2098 Merge ign-gazebo6 ➡️ gz-sim7
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  examples/worlds/detachable_joint.sdf
  examples/worlds/triggered_publisher.sdf
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/Server.hh
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/Server.cc
  src/TestFixture.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gz.cc
  src/rendering/MarkerManager.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  test/integration/CMakeLists.txt
  test/integration/detachable_joint.cc
  test/integration/joint_position_controller_system.cc
  test/integration/markers.cc
  test/integration/sensors_system_update_rate.cc
  test/integration/triggered_camera.cc
  test/worlds/detachable_joint.sdf
  test/worlds/joint_position_controller_velocity.sdf
  tutorials/detachable_joints.md
  tutorials/triggered_publisher.md
Labels: beta, 🌱 garden

#2083 Add tutorials for ApplyForceTorque and MouseDrag plugins
  tutorials.md.in
  tutorials/apply_force_torque.md
  tutorials/files/apply_force_torque/Force.png
  tutorials/files/apply_force_torque/ForceOffset.png
  tutorials/files/apply_force_torque/Interface.png
  tutorials/files/apply_force_torque/RotationTool.png
  tutorials/files/apply_force_torque/Torque.png
  tutorials/files/mouse_drag/Interface.png
  tutorials/files/mouse_drag/Rotation.png
  tutorials/files/mouse_drag/Translation.png
  tutorials/mouse_drag.md
Labels: documentation, beta, 🌱 garden

#2021 Odometry topic for the track controller system
  examples/worlds/conveyor.sdf
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  test/integration/tracked_vehicle_system.cc
Labels: beta, 🌱 garden

#2087 Update for new message generation and iwyu
  src/CMakeLists.txt
  src/msgs/CMakeLists.txt
  src/network/NetworkManagerPrimary.cc
  src/network/NetworkManagerPrimary.hh
  src/network/NetworkManagerSecondary.cc
  src/network/NetworkManagerSecondary.hh
  src/network/PeerInfo.hh
  src/proto/gz/sim/private_msgs/peer_control.proto
  src/proto/gz/sim/private_msgs/peer_info.proto
  src/proto/gz/sim/private_msgs/performer_affinity.proto
  src/proto/gz/sim/private_msgs/simulation_step.proto
Labels: beta, 🎵 harmonic

#2100 Make systems and tests include headers they use
  src/AddedMass_TEST.cc
  src/CMakeLists.txt
  src/Server_TEST.cc
  src/SimulationRunner_TEST.cc
  src/cmd/ModelCommandAPI.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/visualize_contacts/VisualizeContacts.cc
  src/msgs/CMakeLists.txt
  src/network/NetworkManagerPrimary.cc
  src/network/NetworkManagerPrimary.hh
  src/network/NetworkManagerSecondary.cc
  src/network/NetworkManagerSecondary.hh
  src/network/PeerInfo.hh
  src/proto/gz/sim/private_msgs/peer_control.proto
  src/proto/gz/sim/private_msgs/peer_info.proto
  src/proto/gz/sim/private_msgs/performer_affinity.proto
  src/proto/gz/sim/private_msgs/simulation_step.proto
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/ackermann_steering_system.cc
  test/integration/diff_drive_system.cc
  test/integration/entity_system.cc
  test/integration/force_torque_system.cc
  test/integration/halt_motion.cc
  test/integration/log_system.cc
  test/integration/odometry_publisher.cc
  test/integration/performer_detector.cc
  test/integration/pose_publisher_system.cc
  test/integration/reset.cc
  test/integration/reset_detachable_joint.cc
  test/integration/reset_sensors.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sensors_system_update_rate.cc
  test/integration/spherical_coordinates.cc
  test/integration/tracked_vehicle_system.cc
  test/integration/triggered_publisher.cc
  test/integration/user_commands.cc
  test/integration/velocity_control_system.cc
  test/integration/wind_effects.cc
  test/integration/world_control_state.cc
Labels: 🎵 harmonic

#2086 Fix rendering tests
  src/rendering/SceneManager.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/lens_flare/LensFlare.cc
  src/systems/sensors/Sensors.cc
  src/systems/shader_param/ShaderParam.cc
Labels: beta, 🎵 harmonic

#1838 Apply mimic constraint to joints
  examples/worlds/mimic_fast_slow_pendulums_world.sdf
  src/systems/physics/Physics.cc
Labels: beta, 🎵 harmonic

#2081 Add support for writing systems in Python
  .github/ci/packages.apt
  CMakeLists.txt
  examples/scripts/python_api/systems/test_system.py
  examples/worlds/python_system_loader.sdf
  include/gz/sim/EventManager.hh
  python/CMakeLists.txt
  python/test/gz_test_deps/msgs.py
  python/test/gz_test_deps/transport.py
  python/test/link_TEST.py
  python/test/plugins/test_model_system.py
  src/CMakeLists.txt
  src/Link.cc
  src/Server.cc
  src/SimulationRunner.cc
  src/systems/CMakeLists.txt
  src/systems/python_system_loader/CMakeLists.txt
  src/systems/python_system_loader/PythonSystemLoader.cc
  src/systems/python_system_loader/PythonSystemLoader.hh
  test/integration/CMakeLists.txt
  test/integration/link.cc
  test/integration/python_system_loader.cc
  test/worlds/python_system_loader.sdf
  tutorials/python_interfaces.md
Labels: beta, 🎵 harmonic

#2044 Adds python demo examples
  examples/standalone/lrauv_control/lrauv_control.py
  examples/standalone/multi_lrauv_race/multi_lrauv_race.py
Labels: beta, 🎵 harmonic

#2055 Removing ignition
  docker/build.bash
  examples/worlds/deprecated_ignition.sdf
  include/gz/sim/System.hh
  include/gz/sim/Util.hh
  include/gz/sim/components/Model.hh
  src/ServerConfig.cc
  src/ServerPrivate.cc
  src/SystemLoader.cc
  src/Util_TEST.cc
  src/gui/plugins/banana_for_scale/BananaForScale.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/rendering/RenderUtil.cc
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/log/LogPlayback.cc
  src/systems/physics/Physics.cc
  src/systems/triggered_publisher/TriggeredPublisher.hh
  test/integration/battery_plugin.cc
  test/worlds/battery_thruster_consumer.sdf
  test/worlds/hydrodynamics.sdf.in
  tutorials/erb_template.md
  tutorials/migration_actor_api.md
  tutorials/migration_joint_api.md
  tutorials/migration_light_api.md
  tutorials/model_photo_shoot.md
  tutorials/move_camera_to_model.md
  tutorials/particle_tutorial.md
  tutorials/resources.md
  tutorials/triggered_publisher.md
Labels: beta, 🎵 harmonic

#2104 Remove forward-ported restriction on model loading
  src/Server.cc
Labels: beta, 🌱 garden

#2105 Depend on gz-common graphics component
  CMakeLists.txt
Labels: 🎵 harmonic

#2103 Port: 7 to main
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  examples/worlds/conveyor.sdf
  examples/worlds/detachable_joint.sdf
  examples/worlds/triggered_publisher.sdf
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/Server.hh
  src/CMakeLists.txt
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/SimulationRunner.cc
  src/TestFixture.cc
  src/TestFixture_TEST.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.hh
  src/gui/plugins/apply_force_torque/ApplyForceTorque.qml
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/gz.cc
  src/rendering/MarkerManager.cc
  src/rendering/WrenchVisualizer.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  src/systems/track_controller/TrackController.cc
  src/systems/track_controller/TrackController.hh
  test/integration/CMakeLists.txt
  test/integration/detachable_joint.cc
  test/integration/joint_position_controller_system.cc
  test/integration/markers.cc
  test/integration/sensors_system_update_rate.cc
  test/integration/tracked_vehicle_system.cc
  test/integration/triggered_camera.cc
  test/worlds/detachable_joint.sdf
  test/worlds/joint_position_controller_velocity.sdf
  tutorials.md.in
  tutorials/apply_force_torque.md
  tutorials/detachable_joints.md
  tutorials/files/apply_force_torque/Force.png
  tutorials/files/apply_force_torque/ForceOffset.png
  tutorials/files/apply_force_torque/Interface.png
  tutorials/files/apply_force_torque/RotationTool.png
  tutorials/files/apply_force_torque/Torque.png
  tutorials/files/mouse_drag/Interface.png
  tutorials/files/mouse_drag/Rotation.png
  tutorials/files/mouse_drag/Translation.png
  tutorials/mouse_drag.md
  tutorials/triggered_publisher.md
Labels: beta, 🎵 harmonic

#2061 Added Mesh Moment of Inertia Calculator
  src/CMakeLists.txt
  src/MeshInertiaCalculator.cc
  src/MeshInertiaCalculator.hh
  src/Server.cc
  test/integration/CMakeLists.txt
  test/integration/mesh_inertia_calculation.cc
  test/worlds/mesh_inertia_calculation.sdf
  test/worlds/models/cylinder_dae/meshes/cylinder.dae
  test/worlds/models/cylinder_dae/model.config
  test/worlds/models/cylinder_dae/model.sdf
Labels: beta, 🎵 harmonic

#2106 Remove GZ_PHYSICS_ENGINE_INSTALL_DIR deprecation warnings
  src/systems/physics/EntityFeatureMap_TEST.cc
  src/systems/physics/Physics.cc
  test/integration/tracked_vehicle_system.cc
Labels: beta, 🎵 harmonic
