Repository gazebosim/gz-sim, pull requests merged in 2023-05, with the labels that each got.

#1960 Unload render engine when the sensors system exits
  include/gz/sim/rendering/MarkerManager.hh
  include/gz/sim/rendering/RenderUtil.hh
  include/gz/sim/rendering/SceneManager.hh
  src/rendering/MarkerManager.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/sensors/Sensors.cc
  test/integration/ModelPhotoShootTest.hh
  test/performance/CMakeLists.txt
  test/performance/sensors_system.cc
  test/worlds/lights_render.sdf
  test/worlds/sensors_system_mem_leak.sdf
Labels: 🌱 garden

#1976 Update sdf plugins to use actuator_number.
  examples/worlds/multicopter_velocity_control.sdf
  examples/worlds/quadcopter.sdf
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  test/worlds/ackermann_steering_only_actuators.sdf
  test/worlds/odometry_publisher_3d.sdf
  test/worlds/quadcopter.sdf
  test/worlds/quadcopter_velocity_control.sdf
Labels: 🌱 garden

#1954 Actuators message for JointPositionController.
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/joint_position_controller/JointPositionController.hh
  test/integration/joint_position_controller_system.cc
  test/worlds/joint_position_controller_actuators.sdf
Labels: 🌱 garden

#1930 Add tutorial on migrating the Sensor class from gazebo classic
  tutorials.md.in
  tutorials/migration_sensor_api.md
Labels: 🏯 fortress

#1978 Add missing cmake exports from core library
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/include_sim_hh.cc
Labels: 🌱 garden

#1982 fixed a code block in the python interfaces tutorial
  tutorials/python_interfaces.md
Labels: 🌱 garden

#1967 Use ignition::gazebo:: in class instantiation
  src/EntityComponentManager.cc
  src/Link.cc
  src/Model.cc
  src/SdfEntityCreator.cc
  src/ServerConfig.cc
  src/SystemLoader.cc
  src/TestFixture.cc
  src/World.cc
  src/rendering/MarkerManager.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/apply_link_wrench/ApplyLinkWrench.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/buoyancy/Buoyancy.cc
  src/systems/camera_video_recorder/CameraVideoRecorder.cc
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  src/systems/contact/Contact.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/imu/Imu.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/kinetic_energy_monitor/KineticEnergyMonitor.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/log/LogPlayback.cc
  src/systems/log/LogRecord.cc
  src/systems/log_video_recorder/LogVideoRecorder.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/physics/Physics.cc
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  src/systems/sensors/Sensors.cc
  src/systems/thermal/Thermal.cc
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/track_controller/TrackController.cc
  src/systems/tracked_vehicle/TrackedVehicle.cc
  src/systems/user_commands/UserCommands.cc
  src/systems/velocity_control/VelocityControl.cc
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wind_effects/WindEffects.cc
Labels: 🏰 citadel

#1977 Forward port 6 to 7
  src/SdfEntityCreator.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
  test/integration/CMakeLists.txt
  test/integration/actor_trajectory.cc
  test/worlds/actor_trajectory.sdf
  tutorials.md.in
  tutorials/migration_actor_api.md
  tutorials/migration_joint_api.md
  tutorials/migration_light_api.md
  tutorials/migration_link_api.md
  tutorials/migration_model_api.md
Labels: 🌱 garden

#1962 Speed up Resource Spawner load time by fetching model list asynchronously
  src/CMakeLists.txt
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.hh
  src/gui/plugins/resource_spawner/ResourceSpawner.qml
  src/gz.cc
Labels: 🏰 citadel

#1984 Prepare for 3.15.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#1988 Update workflow triggers to avoid duplicates
  .github/workflows/ci.yml
Labels: 🏰 citadel

#1953 Actuators message input for JointController.
  src/systems/joint_controller/JointController.cc
  src/systems/joint_controller/JointController.hh
  test/integration/joint_controller_system.cc
  test/worlds/joint_controller.sdf
Labels: 🌱 garden

#1991 🎈 7.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#1979 Support loading Projectors
  examples/worlds/projector.sdf
  include/gz/sim/Conversions.hh
  include/gz/sim/SdfEntityCreator.hh
  include/gz/sim/components/Projector.hh
  include/gz/sim/rendering/SceneManager.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/SdfEntityCreator.cc
  src/Util.cc
  src/Util_TEST.cc
  src/rendering/RenderUtil.cc
  src/rendering/SceneManager.cc
  src/systems/scene_broadcaster/SceneBroadcaster.cc
  test/integration/CMakeLists.txt
  test/integration/components.cc
  test/integration/projector.cc
  test/integration/scene_broadcaster_system.cc
  test/worlds/projector.sdf
Labels: 🌱 garden
