Repository gazebosim/gz-sim, pull requests merged in 2024-01, with the labels that each got.

#2274 Install the Python libs to system site-packages instead of root
  python/CMakeLists.txt
Labels: 🎵 harmonic

#2277 Merge ign-gazebo3 ➡️ ign-gazebo6
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏯 fortress

#2279 🎈 3.15.1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#2280 Fix URL in hydrodynamics tutorial
  tutorials/theory_hydrodynamics.md
Labels: 🎵 harmonic

#2263 Added tutorial for Gazebo joint controller plugin
  examples/worlds/joint_controller.sdf
  examples/worlds/joint_position_controller.sdf
  tutorials/files/joint_controllers/JoinControllerForceMode.gif
  tutorials/files/joint_controllers/JointController.png
  tutorials/files/joint_controllers/JointControllerVelMode1.gif
  tutorials/files/joint_controllers/JointControllerVelMode2.gif
  tutorials/files/joint_controllers/JointPositionController.gif
  tutorials/files/joint_controllers/JointTrajectoryController.gif
  tutorials/files/joint_controllers/JointTrajectoryController.png
  tutorials/joint_controller.md
Labels: 🌱 garden

#2269 Support for Gazebo materials
  include/gz/sim/InstallationDirectories.hh
  src/CMakeLists.txt
  src/InstallationDirectories.cc
  src/SdfEntityCreator.cc
  src/rendering/MaterialParser/ConfigLoader.cc
  src/rendering/MaterialParser/ConfigLoader.hh
  src/rendering/MaterialParser/MaterialParser.cc
  src/rendering/MaterialParser/MaterialParser.hh
  src/rendering/MaterialParser/gazebo.material
  test/integration/CMakeLists.txt
  test/integration/material.cc
  tutorials/migration_sdf.md
Labels: 🎵 harmonic

#2283 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#2275 Allow using plugin file names and environment variables compatible with Garden and later
  include/gz/sim/Util.hh
  src/Conversions.cc
  src/ServerConfig.cc
  src/ServerConfig_TEST.cc
  src/ServerPrivate.hh
  src/Server_TEST.cc
  src/SystemLoader.cc
  src/SystemLoader_TEST.cc
  src/Util.cc
  src/cmd/cmdgazebo.rb.in
  src/gz_TEST.cc
  src/rendering/RenderUtil.cc
  src/systems/particle_emitter/ParticleEmitter.cc
  test/helpers/Util.hh
  tutorials/migration_sdf.md
  tutorials/resources.md
  tutorials/server_config.md
Labels: 🏯 fortress

#2284 Prepare for 6.16.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#2288 Merge ign-gazebo6 ➡️ gz-sim7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  Changelog.md
  examples/worlds/diff_drive_skid.sdf
  src/Conversions.cc
  src/Server_TEST.cc
  src/SystemLoader_TEST.cc
  src/Util.cc
  src/gz_TEST.cc
  test/helpers/Util.hh
Labels: 🌱 garden

#2109 Regroup tutorials into four categories
  tutorials.md.in
  tutorials/entity_creation.md
  tutorials/model_photo_shoot.md
  tutorials/physics.md
  tutorials/python_interfaces.md
Labels: documentation

#2292 Prepare for 7.7.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#2293 Merge gz-sim7 ➡️ gz-sim8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  Changelog.md
  examples/worlds/diff_drive_skid.sdf
  examples/worlds/joint_controller.sdf
  examples/worlds/joint_position_controller.sdf
  examples/worlds/mecanum_drive.sdf
  examples/worlds/tunnel.sdf
  src/CMakeLists.txt
  src/Conversions.cc
  src/Server_TEST.cc
  src/SystemLoader_TEST.cc
  src/Util.cc
  src/cmd/runGui_main.cc
  src/gz.cc
  src/gz_TEST.cc
  src/systems/environment_preload/EnvironmentPreload.cc
  src/systems/environment_preload/VisualizationTool.cc
  src/systems/environment_preload/VisualizationTool.hh
  src/systems/lift_drag/LiftDrag.cc
  test/helpers/Util.hh
  tutorials/files/joint_controllers/JoinControllerForceMode.gif
  tutorials/files/joint_controllers/JointController.png
  tutorials/files/joint_controllers/JointControllerVelMode1.gif
  tutorials/files/joint_controllers/JointControllerVelMode2.gif
  tutorials/files/joint_controllers/JointPositionController.gif
  tutorials/files/joint_controllers/JointTrajectoryController.gif
  tutorials/files/joint_controllers/JointTrajectoryController.png
  tutorials/joint_controller.md
Labels: 🎵 harmonic

#2286 Change an entities visual material color by topic.
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
  test/worlds/material_color.sdf
Labels: 🎵 harmonic

#2300 Fix `INTEGRATION_save_world` on windows
  test/worlds/non_rendering_sensors.sdf
Labels: 🎵 harmonic

#2298 Explicitly check SKIP_PYBIND11 for python bindings
  CMakeLists.txt
Labels: 🎵 harmonic

#2295 Light entity match SDF boolean for UserCommands.
  src/systems/user_commands/UserCommands.cc
  test/integration/user_commands.cc
  test/worlds/lights_render_all.sdf
Labels: 🎵 harmonic
