Repository gazebosim/gz-sim, pull requests merged in 2024-06, with the labels that each got.

#2420 Enable 24.04 CI, require cmake 3.22.1
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/plugin/command_actor/CMakeLists.txt
  examples/plugin/custom_component/CMakeLists.txt
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/plugin/gui_system_plugin/CMakeLists.txt
  examples/plugin/hello_world/CMakeLists.txt
  examples/plugin/rendering_plugins/CMakeLists.txt
  examples/plugin/reset_plugin/CMakeLists.txt
  examples/plugin/system_plugin/CMakeLists.txt
  examples/standalone/acoustic_comms_demo/CMakeLists.txt
  examples/standalone/comms/CMakeLists.txt
  examples/standalone/custom_server/CMakeLists.txt
  examples/standalone/each_performance/CMakeLists.txt
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/external_ecm/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/lrauv_control/CMakeLists.txt
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/scene_requester/CMakeLists.txt
  python/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/examples_build.cc
  test/test_config.hh.in
Labels: 🏛️ ionic

#2427 Use topicFromScopedName in a few systems
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/pose_publisher/PosePublisher.cc
Labels: 🌱 garden

#2425 Optimize rendering sensor pose updates
  src/rendering/RenderUtil.cc
Labels: 🎵 harmonic

#2430 Handle sdf::Geometry::EMPTY in conversions
  src/Conversions.cc
  src/Conversions_TEST.cc
Labels: 🌱 garden

#2432 Merge 8 -> main
  CMakeLists.txt
  include/gz/sim/Util.hh
  src/Util.cc
  src/Util_TEST.cc
  src/rendering/RenderUtil.cc
Labels: 🏛️ ionic

#2435 Fix warning message to show precise jump back in time duration
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/air_speed/AirSpeed.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/contact/Contact.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/imu/Imu.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/log/LogRecord.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/multicopter_control/MulticopterVelocityControl.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/navsat/NavSat.cc
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/velocity_control/VelocityControl.cc
  src/systems/wind_effects/WindEffects.cc
Labels: 🎵 harmonic

#2383 Add pause run tutorial
  tutorials.md.in
  tutorials/files/pause_run_simlation/gui_pause_run.png
  tutorials/pause_run_simulation.md
  tutorials/reset_simulation.md
Labels: 🎵 harmonic

#2442 Prepare for 8.4.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2398 Add support for no gravity link
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
Labels: needs upstream release, 🏯 fortress

#2443 Do not update sensors if it a triggered sensor
  CMakeLists.txt
  src/systems/sensors/Sensors.cc
Labels: needs upstream release, 🎵 harmonic

#2219 Add tutorial for using the Pose component
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  tutorials/component_pose.md
  tutorials/using_components.md
Labels: documentation, 🎵 harmonic

#2444 Fix ModelCommandAPI unit test
  src/ModelCommandAPI_TEST.cc
Labels: 🎵 harmonic

#2410 Adding cone primitives.
  include/gz/sim/Primitives.hh
  src/Conversions.cc
  src/Primitives.cc
  src/gui/plugins/component_inspector_editor/ComponentInspectorEditor.qml
  src/gui/plugins/component_inspector_editor/ModelEditor.cc
  src/gui/plugins/entity_tree/EntityTree.qml
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/cone.png
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/MarkerManager.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🏛️ ionic

#2448 shapes.sdf example: bump to 1.12, add cone shape
  examples/worlds/shapes.sdf
Labels: 🏛️ ionic

#2449 Remove Cone shape from particle emitter msg conversion
  src/Conversions.cc
Labels: 🏛️ ionic

#2445 Parse voxel resolution SDF param when decomposing meshes
  src/Util.cc
Labels: 🎵 harmonic

#2450 Remove python3-distutils from package.xml
  package.xml
Labels: 🏛️ ionic

#2352 Support visualizing mesh collisions with convex decomposition
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/Util.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
Labels: 🏛️ ionic

#2451 Add GravityEnabled boolean component
  include/gz/sim/components/Gravity.hh
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
Labels: 🏯 fortress

#2382 Permit to run gz sim -g on Windows
  src/cmd/cmdsim.rb.in
Labels: needs upstream release, 🎵 harmonic

#2404 Add Cone as a primitive parametric shape.
  examples/worlds/shapes.sdf
  include/gz/sim/Primitives.hh
  src/Conversions.cc
  src/Primitives.cc
  src/gui/plugins/component_inspector_editor/ComponentInspectorEditor.qml
  src/gui/plugins/component_inspector_editor/ModelEditor.cc
  src/gui/plugins/entity_tree/EntityTree.qml
  src/gui/plugins/shapes/Shapes.qml
  src/gui/plugins/shapes/Shapes.qrc
  src/gui/plugins/shapes/cone.png
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/MarkerManager.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🎵 harmonic

#2455 Prepare for 8.5.0
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2447 Merge 6 -> 7
  include/gz/sim/components/Gravity.hh
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
Labels: 🌱 garden

#2270 Set max contacts for collision pairs
  src/systems/physics/Physics.cc
Labels: needs upstream release, 🌱 garden

#2456 Merge 7 -> 8
  include/gz/sim/components/Gravity.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/ModelCommandAPI_TEST.cc
  src/SdfEntityCreator.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/physics/Physics.cc
  src/systems/pose_publisher/PosePublisher.cc
Labels: 🎵 harmonic
