Repository gazebosim/gz-sim, pull requests merged in 2024-07, with the labels that each got.

#2457 Correct name of sensor in warning message
  src/systems/magnetometer/Magnetometer.cc
Labels: 🎵 harmonic

#2461 Address a couple of todos in Conversions.cc
  src/Conversions.cc
  src/Conversions_TEST.cc
  test/integration/scene_broadcaster_system.cc
Labels: 🎵 harmonic

#2452 Consolidate entity creation.
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/SdfEntityCreator.hh
  include/gz/sim/components/Performer.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/LevelManager.cc
  src/LevelManager.hh
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/pose_publisher/PosePublisher.cc
Labels: needs upstream release, 🌱 garden

#2460 Magnetometer: correct field calculation
  src/systems/magnetometer/Magnetometer.cc
  src/systems/magnetometer/Magnetometer.hh
Labels: 🎵 harmonic

#2467 Update description of reset_sensors test
  test/integration/reset_sensors.cc
Labels: 🎵 harmonic

#2469 Fix warnings generated by NetworkConfigTest
  src/network/NetworkConfig_TEST.cc
Labels: 🏛️ ionic

#2468 Enable tests on macOS
  test/integration/actor_trajectory.cc
  test/integration/camera_sensor_background_from_scene.cc
  test/integration/sensors_system.cc
  test/integration/sensors_system_battery.cc
  test/integration/sensors_system_update_rate.cc
  test/integration/thermal_sensor_system.cc
  test/integration/thermal_system.cc
  test/integration/wide_angle_camera.cc
Labels: 🎵 harmonic

#2470 Merge ign-gazebo3 ➡️ ign-gazebo6
  .github/ci/after_make.sh
  .github/ci/before_cmake.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
  include/gz/sim/playback_server.config
Labels: 🏯 fortress

#2472 Merge gz-sim8 ➡️ main
  Changelog.md
  examples/worlds/shapes.sdf
  include/gz/sim/components/Gravity.hh
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/ModelCommandAPI_TEST.cc
  src/SdfEntityCreator.cc
  src/Util.cc
  src/cmd/cmdsim.rb.in
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/advanced_lift_drag/AdvancedLiftDrag.cc
  src/systems/air_pressure/AirPressure.cc
  src/systems/air_speed/AirSpeed.cc
  src/systems/altimeter/Altimeter.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/contact/Contact.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/imu/Imu.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/lift_drag/LiftDrag.cc
  src/systems/log/LogRecord.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/logical_camera/LogicalCamera.cc
  src/systems/magnetometer/Magnetometer.cc
  src/systems/magnetometer/Magnetometer.hh
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/multicopter_control/MulticopterVelocityControl.cc
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/navsat/NavSat.cc
  src/systems/odometry_publisher/OdometryPublisher.cc
  src/systems/odometry_publisher/OdometryPublisher.hh
  src/systems/physics/Physics.cc
  src/systems/pose_publisher/PosePublisher.cc
  src/systems/sensors/Sensors.cc
  src/systems/touch_plugin/TouchPlugin.cc
  src/systems/velocity_control/VelocityControl.cc
  src/systems/wind_effects/WindEffects.cc
  test/integration/actor_trajectory.cc
  test/integration/camera_sensor_background_from_scene.cc
  test/integration/reset_sensors.cc
  test/integration/scene_broadcaster_system.cc
  test/integration/sensors_system.cc
  test/integration/sensors_system_battery.cc
  test/integration/sensors_system_update_rate.cc
  test/integration/thermal_sensor_system.cc
  test/integration/thermal_system.cc
  test/integration/wide_angle_camera.cc
  tutorials.md.in
  tutorials/component_pose.md
  tutorials/files/pause_run_simlation/gui_pause_run.png
  tutorials/pause_run_simulation.md
  tutorials/reset_simulation.md
  tutorials/using_components.md
Labels: 🏛️ ionic

#2474 Check if any entity actually has a ContactSensorData component before…
  src/systems/physics/Physics.cc
Labels: 🎵 harmonic

#2479 Add UserCommands plugin to GPU lidar sensor example
  examples/worlds/gpu_lidar_sensor.sdf
Labels: 🎵 harmonic

#2454 Backport convex decomposition visualization
  src/Conversions.cc
  src/Conversions_TEST.cc
  src/Util.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
Labels: 🎵 harmonic

#2477 Merge 6 -> 7
  .github/ci/after_make.sh
  .github/ci/before_cmake.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
  test/integration/camera_video_record_system.cc
  test/integration/distortion_camera.cc
  test/integration/reset_sensors.cc
  test/integration/shader_param_system.cc
  test/integration/wide_angle_camera.cc
Labels: 🌱 garden

#2232 Remove systems if their parent entity is removed
  include/gz/sim/EntityComponentManager.hh
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
Labels: 🏛️ ionic

#2481 Fix lidar visualization when gz_frame_id is specified
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: 🎵 harmonic

#2483 Backport lidar visualization frame_id fix
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
Labels: 🏯 fortress

#2431 feat: added support for spacecraft thrusters
  examples/worlds/ground_spacecraft_testbed.sdf
  examples/worlds/spacecraft.sdf
  src/systems/CMakeLists.txt
  src/systems/spacecraft_thruster_model/CMakeLists.txt
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.cc
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.hh
  test/integration/CMakeLists.txt
  test/integration/spacecraft.cc
  tutorials/files/spacecraft/dart.png
  tutorials/files/spacecraft/kth_spacecraft_simulator.png
  tutorials/spacecraft_thrusters.md
Labels: 🌱 garden

#2491 Prepare for 7.8.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#2492 Fix error resolving gazebo classic material when loading world
  src/SdfEntityCreator.cc
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  test/integration/material.cc
  test/worlds/classic_material.sdf
Labels: 🎵 harmonic

#2496 Prepare for 8.6.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2499 Disable failing testFixture_TEST for MacOS
  python/CMakeLists.txt
Labels: 🏯 fortress

#2503 Initialize threadsNeedCleanUp in SimulationRunner
  src/SimulationRunner.hh
Labels: 🎵 harmonic

#2501 Improve signal handling
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
Labels: beta, 🏛️ ionic
