Repository gazebosim/gz-sim, pull requests merged in 2024-05, with the labels that each got.

#2378 Merge 8 -> main
  .github/ci/packages.apt
  CMakeLists.txt
  Changelog.md
  examples/worlds/dvl_world.sdf
  include/gz/sim/ServerConfig.hh
  src/CMakeLists.txt
  src/Server.cc
  src/ServerConfig.cc
  src/Server_Rendering_TEST.cc
  src/Server_TEST.cc
  src/Util.cc
  src/cmd/CMakeLists.txt
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/modules/CMakeLists.txt
  src/systems/CMakeLists.txt
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
  test/integration/triggered_publisher.cc
  test/worlds/README.md
Labels: 🏛️ ionic

#2395 ForwardPort #2388 Fix unused gcc warnings
  src/network/NetworkConfig_TEST.cc
Labels: 🎵 harmonic

#2396 Remove Empty Test File
  src/CMakeLists.txt
  src/System_TEST.cc
Labels: 🎵 harmonic

#2403 ForceTorque system: improve readability
  src/systems/force_torque/ForceTorque.cc
Labels: 🏛️ ionic

#2241 Lighter Than Air Dynamics Systems
  examples/worlds/lighter_than_air_blimp.sdf
  include/gz/sim/Link.hh
  src/Link.cc
  src/systems/CMakeLists.txt
  src/systems/lighter_than_air_dynamics/CMakeLists.txt
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.cc
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.hh
  test/integration/CMakeLists.txt
  test/integration/lighter_than_air_dynamics.cc
  test/worlds/lighter_than_air_dynamics.sdf
Labels: 🌱 garden

#2405 Backport ForceTorque system: improve readability (#2403)
  src/systems/force_torque/ForceTorque.cc
Labels: 🌱 garden

#2402 Add Track and Follow options in gui EntityContextMenu
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.hh
  src/gui/plugins/modules/EntityContextMenu.qml
Labels: needs upstream release, 🎵 harmonic

#2411 Merge gz-sim7 ➡️ gz-sim8
  examples/worlds/lighter_than_air_blimp.sdf
  include/gz/sim/Link.hh
  src/Link.cc
  src/systems/CMakeLists.txt
  src/systems/force_torque/ForceTorque.cc
  src/systems/lighter_than_air_dynamics/CMakeLists.txt
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.cc
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.hh
  test/integration/CMakeLists.txt
  test/integration/lighter_than_air_dynamics.cc
  test/worlds/lighter_than_air_dynamics.sdf
Labels: 🎵 harmonic

#2414 Add missing algorithm include
  include/gz/sim/components/Factory.hh
Labels: 🎵 harmonic

#2408 Update sensors with pending trigger immediately in Sensors system
  src/systems/sensors/Sensors.cc
Labels: 🎵 harmonic

#2397 Fix CMake warnings in Noble
  examples/standalone/gtest_setup/CMakeLists.txt
Labels: 🎵 harmonic

#2419 Rephrase cmake comment about CMP0077
  CMakeLists.txt
Labels: 🏯 fortress

#2417 Support mesh optimization when using AttachMeshShapeFeature
  include/gz/sim/Util.hh
  src/Util.cc
  src/Util_TEST.cc
Labels: 🎵 harmonic

#2418 Use VERSION_GREATER_EQUAL in cmake logic
  src/CMakeLists.txt
Labels: 🏯 fortress

#2422 Merge gz-sim8 ➡️ main
  .github/workflows/package_xml.yml
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  examples/worlds/lighter_than_air_blimp.sdf
  include/gz/sim/Link.hh
  include/gz/sim/components/Factory.hh
  package.xml
  src/CMakeLists.txt
  src/Link.cc
  src/System_TEST.cc
  src/gui/plugins/modules/EntityContextMenu.cc
  src/gui/plugins/modules/EntityContextMenu.hh
  src/gui/plugins/modules/EntityContextMenu.qml
  src/systems/CMakeLists.txt
  src/systems/elevator/vender/afsm/include/afsm/detail/transitions.hpp
  src/systems/lighter_than_air_dynamics/CMakeLists.txt
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.cc
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.hh
  src/systems/sensors/Sensors.cc
  test/integration/CMakeLists.txt
  test/integration/lighter_than_air_dynamics.cc
  test/worlds/lighter_than_air_dynamics.sdf
Labels: 🏛️ ionic

#2423 Merge ign-gazebo6 ➡️ gz-sim7
  CMakeLists.txt
  src/CMakeLists.txt
Labels: 🌱 garden

#2351 Parse and set bullet solver iterations
  include/gz/sim/components/Physics.hh
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
  test/worlds/physics_options.sdf
Labels: 🏛️ ionic

#2426 Remove a few extra zeros from some sdf files
  test/worlds/quadcopter.sdf
  test/worlds/quadcopter_velocity_control.sdf
Labels: 🌱 garden

#2428 Merge gz-sim7 ➡️ gz-sim8
  CMakeLists.txt
  src/CMakeLists.txt
  test/worlds/quadcopter.sdf
  test/worlds/quadcopter_velocity_control.sdf
Labels: 🎵 harmonic
