Repository gazebosim/gz-sim, pull requests merged in 2024-11, with the labels that each got.

#2666 Backport fix for multicopter motor plugin crash
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
Labels: 🎵 harmonic

#2671 Prepare for 8.7.0 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2673 Prepend to PYTHONPATH in tests
  python/CMakeLists.txt
  test/integration/CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#2674 Fix crash in OpticalTactilePlugin by checking for valid visualize pointer
  src/systems/optical_tactile_plugin/OpticalTactilePlugin.cc
Labels: 🏛️ ionic, 🪵 jetty

#2596 Improve load times by skipping serialization of entities when unecessary.
  include/gz/sim/components/Model.hh
Labels: 🪵 jetty

#2686 Remove detachable joints when a model is removed
  src/EntityComponentManager.cc
  src/systems/physics/Physics.cc
  test/integration/entity_erase.cc
Labels: 🏛️ ionic, 🪵 jetty

#2687 Fix uncontrolled cast of size_t to uint
  src/SimulationRunner.cc
Labels: 🏯 fortress
