Repository gazebosim/gz-sim, pull requests merged in 2024-04, with the labels that each got.

#2350 Fixed undefined behavior in thruster.cc
  test/integration/thruster.cc
Labels: 🎵 harmonic

#2357 thruster test: remove unnecessary sleep
  test/integration/thruster.cc
Labels: 🎵 harmonic

#2360 Use SetComponentData to simplify code and improve coverage
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/thruster/Thruster.cc
  src/systems/velocity_control/VelocityControl.cc
  test/integration/wheel_slip.cc
Labels: 🎵 harmonic

#2363 Merge gz-sim8 ➡️ main
  Changelog.md
  src/MeshInertiaCalculator.cc
  src/SimulationRunner.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/SceneManager.cc
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/diff_drive/DiffDrive.cc
  src/systems/dvl/DopplerVelocityLogSystem.cc
  src/systems/joint_controller/JointController.cc
  src/systems/joint_position_controller/JointPositionController.cc
  src/systems/mecanum_drive/MecanumDrive.cc
  src/systems/thruster/Thruster.cc
  src/systems/velocity_control/VelocityControl.cc
  test/integration/thruster.cc
  test/integration/wheel_slip.cc
Labels: 🏛️ ionic

#2354 Fix TriggeredPublisher test
  test/integration/triggered_publisher.cc
Labels: 🎵 harmonic

#2228 Physics: remove *VelocityCmd at each time step
  Migration.md
  src/systems/multicopter_motor_model/MulticopterMotorModel.cc
  src/systems/physics/Physics.cc
  src/systems/trajectory_follower/TrajectoryFollower.cc
  test/worlds/quadcopter.sdf
  test/worlds/quadcopter_velocity_control.sdf
Labels: 🏛️ ionic

#2355 Use steer_p_gain for UpdateVelocity steer joint speed
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/ackermann_steering/AckermannSteering.hh
Labels: 🎵 harmonic

#2368 Prepare for 8.3.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#2373 Added example world for `DopplerVelocityLogSystem`
  examples/worlds/dvl_world.sdf
  test/worlds/README.md
Labels: 🎵 harmonic

#2374 Drop python3-distutils from Noble package list (onwards)
  .github/ci/packages.apt
Labels: 🎵 harmonic

#2349 Enable StoreResolvedURIs when loading SDF
  include/gz/sim/ServerConfig.hh
  src/Server.cc
  src/ServerConfig.cc
  src/Server_Rendering_TEST.cc
  src/Server_TEST.cc
  src/Util.cc
Labels: 🎵 harmonic

#2339 [Backport]: Fix ModelPhotoShootTest test failures (#2294)
  examples/worlds/model_photo_shoot.sdf
  test/integration/ModelPhotoShootTest.hh
  test/worlds/model_photo_shoot_random_joints.sdf
Labels: 🏯 fortress

#2381 Merge ign-gazebo6 ➡️ gz-sim7
  examples/worlds/model_photo_shoot.sdf
  test/integration/ModelPhotoShootTest.hh
  test/worlds/model_photo_shoot_random_joints.sdf
Labels: 🌱 garden

#2385 Fix namespace and class links in documentation references that use namespace `gz`
  api.md.in
Labels: 🏯 fortress

#2337 Add package.xml
  .github/workflows/package_xml.yml
  package.xml
Labels: 🎵 harmonic

#2386 Fix name of gz-fuel_tools in package.xml
  package.xml
Labels: 🎵 harmonic

#2388 Blast545/fix unused gcc warnings
  src/network/NetworkConfig_TEST.cc
Labels: 🎵 harmonic

#2375 Fix GCC/CMake warnings for Noble
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/standalone/gtest_setup/CMakeLists.txt
  src/systems/elevator/vender/afsm/include/afsm/detail/transitions.hpp
Labels: 🎵 harmonic
