Repository gazebosim/gz-sim, pull requests merged in 2024-12, with the labels that each got.

#2693 Link.hh: add Sensor accessor APIs
  include/gz/sim/Link.hh
  python/src/gz/sim/Link.cc
  python/test/link_TEST.py
  src/Link.cc
  src/Link_TEST.cc
  test/integration/link.cc
Labels: 🏛️ ionic, 🪵 jetty

#2651 Use same FP limits for TrackedVehicle to avoid self-moving
  src/systems/tracked_vehicle/TrackedVehicle.cc
Labels: 🏛️ ionic

#2699 Extend shapes gui plugin width to include the ellipsoid button
  src/gui/gui.config
Labels: 🏛️ ionic, 🪵 jetty

#2700 Prepare for 3.15.2 Release
  Changelog.md
Labels: 🏰 citadel

#2702 Prepare for 3.15.2 Release (Redo)
  CMakeLists.txt
Labels: 🏰 citadel

#2696 Add parameter for adjust current sign in battery plugin
  src/systems/battery_plugin/LinearBatteryPlugin.cc
Labels: 🏛️ ionic, 🪵 jetty

#2697 Fix publishing only top level model pose in pose publisher
  src/systems/pose_publisher/PosePublisher.cc
  test/integration/pose_publisher_system.cc
  test/worlds/pose_publisher.sdf
Labels: 🏛️ ionic, 🪵 jetty

#2647 Adds support for `ISystemReset` in test fixture
  include/gz/sim/TestFixture.hh
  python/src/gz/sim/TestFixture.cc
  src/TestFixture.cc
Labels: 🪵 jetty
