Repository gazebosim/gz-sim, pull requests merged in 2024-08, with the labels that each got.

#2487 Specify System::PreUpdate, Update execution order
  examples/plugin/priority_printer_plugin/CMakeLists.txt
  examples/plugin/priority_printer_plugin/PriorityPrinter.cc
  examples/plugin/priority_printer_plugin/PriorityPrinter.hh
  examples/plugin/priority_printer_plugin/README.md
  examples/plugin/priority_printer_plugin/priority_printer_plugin.sdf
  include/gz/sim/System.hh
  src/SimulationRunner.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
Labels: beta, 🏛️ ionic

#2509 Fix #2458 - Checking linkEnity is empty
  src/systems/user_commands/UserCommands.cc
Labels: 🎵 harmonic

#2505 Remove ignition related deprecations
  include/gz/sim/components/Factory.hh
  src/ServerConfig.cc
  src/SystemLoader.cc
  src/cmd/cmdsim.rb.in
  src/gui/plugins/video_recorder/VideoRecorder.cc
  src/systems/lighter_than_air_dynamics/LighterThanAirDynamics.cc
  src/systems/log/LogPlayback.cc
  src/systems/physics/Physics.cc
  test/benchmark/ecm_serialize.cc
  test/integration/each_new_removed.cc
  test/media/levels_log/state.tlog
  tutorials/install.md
  tutorials/joint_controller.md
  tutorials/migration_sensor_api.md
Labels: 🏛️ ionic

#2516 Fix adding system to non-existent entity
  src/SystemManager.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
Labels: beta, 🎵 harmonic

#2253 gui_system_plugin: clarify description in README
  examples/plugin/gui_system_plugin/README.md
Labels: beta, 🎵 harmonic

#2490 Fix ResourceSpawner
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
Labels: needs upstream release, beta, 🎵 harmonic

#2521 Make sure steering joints exist before updating velocity / odometry in AckermannSteering plugin
  src/systems/ackermann_steering/AckermannSteering.cc
Labels: 🎵 harmonic

#2493 Deprecate use of added mass via hydrodynamics
  src/systems/hydrodynamics/Hydrodynamics.cc
  src/systems/hydrodynamics/Hydrodynamics.hh
Labels: beta, 🏛️ ionic

#1097 Detachable joint: support for nested models of the same name
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  test/integration/detachable_joint.cc
  test/worlds/detachable_joint_child.sdf
Labels: beta, 🏯 fortress, MBARI-LRAUV

#2523 Disable detachable_joint integration test case on Windows
  test/integration/detachable_joint.cc
Labels: 🏯 fortress

#2524 Remove unused var in thruster system
  src/systems/thruster/Thruster.cc
Labels: 🎵 harmonic

#2494 ForceTorque system: write WrenchMeasured to ECM
  Migration.md
  examples/worlds/sensors.sdf
  include/gz/sim/Model.hh
  include/gz/sim/components/WrenchMeasured.hh
  python/test/joint_test.sdf
  python/test/sensor_TEST.py
  src/Model.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/force_torque/ForceTorque.hh
  src/systems/physics/Physics.cc
  test/integration/force_torque_system.cc
  test/integration/model.cc
  test/worlds/force_torque.sdf
Labels: beta

#2525 Merge gz-sim8 ➡️ main
  Changelog.md
  examples/plugin/gui_system_plugin/README.md
  examples/worlds/gpu_lidar_sensor.sdf
  src/SdfEntityCreator.cc
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  src/SimulationRunner.hh
  src/SystemManager.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/systems/ackermann_steering/AckermannSteering.cc
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  src/systems/physics/Physics.cc
  src/systems/thruster/Thruster.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/material.cc
  test/worlds/classic_material.sdf
Labels: 🏛️ ionic

#2489 Physics: set link velocity from *VelocityReset components
  include/gz/sim/components/AngularVelocityReset.hh
  include/gz/sim/components/LinearVelocityReset.hh
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
Labels: beta, 🏛️ ionic

#2440 Set link velocity from `set_model_state` plugin
  examples/worlds/set_model_state.sdf
  src/systems/set_model_state/SetModelState.cc
Labels: beta

#2526 Force Qt to use xcb plugin on Wayland
  src/gui/Gui.cc
Labels: 🎵 harmonic

#2500 Add System interface to set default priority
  Migration.md
  include/gz/sim/System.hh
  src/SystemInternal.hh
  src/SystemManager.cc
  src/SystemManager_TEST.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/force_torque/ForceTorque.hh
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
  src/systems/user_commands/UserCommands.cc
  src/systems/user_commands/UserCommands.hh
Labels: beta, 🏛️ ionic

#2530 Backport to harmonic: Specify System::PreUpdate, Update execution order (#2487)
  examples/plugin/priority_printer_plugin/CMakeLists.txt
  examples/plugin/priority_printer_plugin/PriorityPrinter.cc
  examples/plugin/priority_printer_plugin/PriorityPrinter.hh
  examples/plugin/priority_printer_plugin/README.md
  examples/plugin/priority_printer_plugin/priority_printer_plugin.sdf
  include/gz/sim/System.hh
  src/SimulationRunner.cc
  src/SystemManager.cc
  src/SystemManager.hh
  src/SystemManager_TEST.cc
Labels: beta, 🎵 harmonic

#2527 Revert behavior change introduced in #2452
  src/SdfEntityCreator.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/pose_publisher/PosePublisher.cc
Labels: 🌱 garden

#2504 Merge 7 -> 8
  .github/ci/after_make.sh
  .github/ci/before_cmake.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
  examples/worlds/ground_spacecraft_testbed.sdf
  examples/worlds/spacecraft.sdf
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/SdfEntityCreator.hh
  include/gz/sim/components/Performer.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/LevelManager.cc
  src/LevelManager.hh
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/systems/CMakeLists.txt
  src/systems/spacecraft_thruster_model/CMakeLists.txt
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.cc
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.hh
  test/integration/CMakeLists.txt
  test/integration/camera_video_record_system.cc
  test/integration/distortion_camera.cc
  test/integration/reset_sensors.cc
  test/integration/shader_param_system.cc
  test/integration/spacecraft.cc
  test/integration/wide_angle_camera.cc
  tutorials/files/spacecraft/dart.png
  tutorials/files/spacecraft/kth_spacecraft_simulator.png
  tutorials/spacecraft_thrusters.md
Labels: beta, 🎵 harmonic

#2534 Prepare for 7.9.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#2535 Fix SphericalCoordinates deprecation warnings
  src/Util.cc
  src/systems/user_commands/UserCommands.cc
Labels: 🏛️ ionic

#2537 Fix UNIT_Server_TEST failure caused by change in behavior of `gz::common::SignalHandler`
  src/Server_TEST.cc
Labels: 🏛️ ionic

#2539 Add CMAKE_INSTALL_PREFIX to noble github workflow
  .github/workflows/ci.yml
Labels: 🏛️ ionic

#2533 Merge 8 -> main
  .github/ci/after_make.sh
  .github/ci/before_cmake.sh
  .github/ci/packages.apt
  .github/workflows/ci.yml
  Changelog.md
  examples/worlds/ground_spacecraft_testbed.sdf
  examples/worlds/spacecraft.sdf
  include/gz/sim/EntityComponentManager.hh
  include/gz/sim/SdfEntityCreator.hh
  include/gz/sim/components/Performer.hh
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/LevelManager.cc
  src/LevelManager.hh
  src/SdfEntityCreator.cc
  src/SdfEntityCreator_TEST.cc
  src/ServerPrivate.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/SimulationRunner.hh
  src/SimulationRunner_TEST.cc
  src/gui/Gui.cc
  src/systems/CMakeLists.txt
  src/systems/spacecraft_thruster_model/CMakeLists.txt
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.cc
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.hh
  test/integration/CMakeLists.txt
  test/integration/camera_video_record_system.cc
  test/integration/distortion_camera.cc
  test/integration/reset_sensors.cc
  test/integration/shader_param_system.cc
  test/integration/spacecraft.cc
  test/integration/wide_angle_camera.cc
  tutorials/files/spacecraft/dart.png
  tutorials/files/spacecraft/kth_spacecraft_simulator.png
  tutorials/spacecraft_thrusters.md
Labels: 🏛️ ionic

#2348 Fixed Odometry Publisher Angular Velocity Singularity in 3D
  src/systems/odometry_publisher/OdometryPublisher.cc
  test/integration/odometry_publisher.cc
  test/worlds/odometry_publisher_3d_singularity.sdf
Labels: needs upstream release, beta, 🎵 harmonic

#2540 Fix elevator system crash when empty laser scan msg is received.
  src/systems/elevator/Elevator.cc
Labels: 🎵 harmonic

#2548 clang-tidy fixes: use empty(), fix includes
  src/EntityComponentManager.cc
  src/EntityComponentManager_TEST.cc
  src/LevelManager.cc
  src/SdfEntityCreator.cc
  src/SimulationRunner.cc
  src/systems/spacecraft_thruster_model/SpacecraftThrusterModel.cc
Labels: 🎵 harmonic

#2546 Restore behavior change by reverting #2527
  src/SdfEntityCreator.cc
  src/systems/logical_audio_sensor_plugin/LogicalAudioSensorPlugin.cc
  src/systems/pose_publisher/PosePublisher.cc
Labels: beta, 🏛️ ionic

#2551 Remove <gz:system_priority/> from test worlds
  python/test/joint_test.sdf
  src/systems/physics/Physics.cc
  src/systems/user_commands/UserCommands.cc
  test/worlds/force_torque.sdf
Labels: 🏛️ ionic

#2552 Backport nonbreaking changes from ionic
  include/gz/sim/Model.hh
  include/gz/sim/components/WrenchMeasured.hh
  python/test/sensor_TEST.py
  src/Model.cc
  src/SystemManager.cc
  src/systems/force_torque/ForceTorque.cc
  src/systems/physics/Physics.cc
  src/systems/user_commands/UserCommands.cc
  test/integration/force_torque_system.cc
  test/integration/model.cc
Labels: 🎵 harmonic

#2545 Fix crash at exit due to a race condition with new signal handler
  src/ServerPrivate.cc
Labels: beta, 🏛️ ionic

#2497 Add a flexible mechanism to combine user and default plugins
  examples/worlds/camera_sensor.sdf
  examples/worlds/contact_sensor.sdf
  examples/worlds/mimic_fast_slow_pendulums_world.sdf
  examples/worlds/quadcopter.sdf
  include/gz/sim/Constants.hh
  src/ServerConfig.cc
  src/Server_TEST.cc
  src/SimulationRunner.cc
  src/gui/Gui.cc
  test/integration/reset_sensors.cc
  test/test_config.hh.in
  test/worlds/air_pressure.sdf
  test/worlds/air_speed.sdf
  test/worlds/reset_sensors.sdf
  tutorials/gui_config.md
  tutorials/server_config.md
Labels: beta, Breaking change, 🏛️ ionic

#2554 Update Changelog, README, and prep for 9.0.0pre1 release
  CMakeLists.txt
  Changelog.md
  README.md
Labels: 🏛️ ionic

#2553 Fix doxygen page links
  tutorials/adding_system_plugins.md
  tutorials/adding_visuals.md
  tutorials/create_vehicle.md
  tutorials/frame_reference.md
  tutorials/lander.md
  tutorials/surface_vehicles.md
  tutorials/theory_buoyancy.md
  tutorials/theory_hydrodynamics.md
  tutorials/underwater_vehicles.md
Labels: documentation, 🏛️ ionic
