Repository gazebosim/gz-sim, pull requests merged in 2025-06, with the labels that each got.

#2915 Use HeightmapUtil functions for loading HeightmapData
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/rendering/SceneManager.cc
  src/systems/physics/Physics.cc
Labels: 🏛️ ionic

#2792 Port Websocket server from gz-launch
  .github/ci/packages.apt
  CMakeLists.txt
  examples/scripts/websocket_server/README.md
  examples/scripts/websocket_server/eventemitter2.min.js
  examples/scripts/websocket_server/gz.js
  examples/scripts/websocket_server/gz3d.js
  examples/scripts/websocket_server/index.html
  examples/scripts/websocket_server/localhost.cert
  examples/scripts/websocket_server/localhost.key
  examples/scripts/websocket_server/websocket_server.sdf
  src/systems/CMakeLists.txt
  src/systems/websocket_server/CMakeLists.txt
  src/systems/websocket_server/WebsocketServer.cc
  src/systems/websocket_server/WebsocketServer.hh
  src/systems/websocket_server/combined.proto
  tutorials.md.in
  tutorials/files/websocket_server/fuel_visualization_gzweb.png
  tutorials/websocket_server.md
Labels: 🪵 jetty

#2935 ci.yml: run cppcheck, cpplint on noble
  .github/workflows/ci.yml
Labels: 🏛️ ionic

#2787 Add support to get link AABB from its collisions
  include/gz/sim/Link.hh
  include/gz/sim/Util.hh
  python/src/gz/sim/Link.cc
  python/test/link_TEST.py
  src/Link.cc
  src/Util.cc
  src/Util_TEST.cc
  test/integration/link.cc
Labels: needs upstream release, 🏛️ ionic

#2959 Set IGN_IP=127.0.0.1 in cmd tests
  src/CMakeLists.txt
Labels: 🏯 fortress
