Repository gazebosim/gz-sim, pull requests merged in 2025-08, with the labels that each got.

#2988 Fix crash when calling setPose service on static and nolink entity
  src/systems/physics/Physics.cc
Labels: 🏛️ ionic

#2984 Add param in physics system to enforce fixed constraint
  src/systems/physics/Physics.cc
  src/systems/physics/Physics.hh
Labels: 🏛️ ionic

#3022 Add missing algorithm include
  include/gz/sim/components/Factory.hh
Labels: 🏯 fortress

#3026 Merge ign-gazebo6 ➡️ gz-sim8
  Changelog.md
  examples/worlds/shader_param.sdf
  src/systems/detachable_joint/DetachableJoint.cc
  src/systems/detachable_joint/DetachableJoint.hh
  test/integration/detachable_joint.cc
  test/worlds/detachable_joint_child.sdf
Labels: 🎵 harmonic

#2990 Remove server+client flags from independent standalone execs
  src/cmd/gui_main.cc
  src/cmd/sim_main.cc
Labels: 🪵 jetty

#3025 Update Qt6 deps in package.xml
  package.xml
Labels: 🪵 jetty

#3003 Add LookupWheelSlip system
  BUILD.bazel
  examples/worlds/lookup_slip_heightmap.png
  examples/worlds/lookup_slip_heightmap_normal.png
  examples/worlds/lookup_slip_map.png
  examples/worlds/lookup_wheel_slip.sdf
  src/systems/CMakeLists.txt
  src/systems/lookup_wheel_slip/CMakeLists.txt
  src/systems/lookup_wheel_slip/LookupWheelSlip.cc
  src/systems/lookup_wheel_slip/LookupWheelSlip.hh
  src/systems/wheel_slip/WheelSlip.cc
  src/systems/wheel_slip/WheelSlip.hh
  test/integration/CMakeLists.txt
  test/integration/lookup_wheel_slip_system.cc
Labels: 🪵 jetty

#3038 Update changelog for 10.0.0
  Changelog.md
Labels: 🪵 jetty

#3040 Update references of main to gz-sim10
  Migration.md
  README.md
  examples/plugin/custom_sensor_system/README.md
  examples/plugin/priority_printer_plugin/README.md
  tutorials/adding_system_plugins.md
  tutorials/blender_distort_meshes.md
  tutorials/blender_procedural_datasets.md
  tutorials/blender_sdf_exporter.md
  tutorials/collada_world_exporter.md
  tutorials/component_pose.md
  tutorials/create_system_plugins.md
  tutorials/distributed_simulation.md
  tutorials/erb_template.md
  tutorials/hpc_clusters.md
  tutorials/lander.md
  tutorials/mesh_to_fuel.md
  tutorials/migrating_ardupilot_plugin.md
  tutorials/migration_sdf.md
  tutorials/mouse_drag.md
  tutorials/particle_tutorial.md
  tutorials/python_interfaces.md
  tutorials/rendering_plugins.md
  tutorials/resources.md
  tutorials/shadow_texture_size.md
  tutorials/test_fixture.md
  tutorials/triggered_publisher.md
  tutorials/video_recorder.md
  tutorials/websocket_server.md
Labels: 🪵 jetty

#3041 [Bazel] Update bazel module to use jetty release branches
  .github/workflows/bazel.yml
  BUILD.bazel
  MODULE.bazel
Labels: 🪵 jetty

#3044 Update GUI Runner initial state request timing
  src/gui/GuiRunner.cc
Labels: 🪵 jetty
