Repository gazebosim/gz-sim, pull requests merged in 2025-04, with the labels that each got.

#2843 Find gz-gui without major version
  CMakeLists.txt
  examples/plugin/rendering_plugins/CMakeLists.txt
  package.xml
  src/CMakeLists.txt
  src/gui/CMakeLists.txt
Labels: 🪵 jetty

#2808 Remove unneeded mesh_inertia_calculation test expectations
  test/integration/mesh_inertia_calculation.cc
Labels: 🏛️ ionic

#2835 Bring back feature for plotting pose attributes from Component Inspector
  src/gui/plugins/component_inspector/Pose3d.qml
Labels: 🪵 jetty

#2828 Detect running server on startup
  src/SimulationRunner.cc
  src/gui/Gui_TEST.cc
  src/gui/QuickStartHandler.cc
  src/gui/QuickStartHandler.hh
Labels: 🏛️ ionic

#2830 Fix QML warnings from Inertial.qml in Component Inspector
  src/gui/plugins/component_inspector/Inertial.qml
Labels: 🪵 jetty

#2857 Bump gz-transport and others in jetty
  .github/ci/packages.apt
  CMakeLists.txt
  docker/Dockerfile.nightly
  examples/plugin/custom_sensor_system/CMakeLists.txt
  examples/standalone/acoustic_comms_demo/CMakeLists.txt
  examples/standalone/comms/CMakeLists.txt
  examples/standalone/entity_creation/CMakeLists.txt
  examples/standalone/joy_to_twist/CMakeLists.txt
  examples/standalone/joystick/CMakeLists.txt
  examples/standalone/keyboard/CMakeLists.txt
  examples/standalone/light_control/CMakeLists.txt
  examples/standalone/lrauv_control/CMakeLists.txt
  examples/standalone/lrauv_control/lrauv_control.py
  examples/standalone/marker/CMakeLists.txt
  examples/standalone/multi_lrauv_race/CMakeLists.txt
  examples/standalone/multi_lrauv_race/multi_lrauv_race.py
  examples/standalone/scene_requester/CMakeLists.txt
  package.xml
  python/test/gz_test_deps/transport.py
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/gui/CMakeLists.txt
  src/systems/air_pressure/CMakeLists.txt
  src/systems/air_speed/CMakeLists.txt
  src/systems/altimeter/CMakeLists.txt
  src/systems/apply_joint_force/CMakeLists.txt
  src/systems/breadcrumbs/CMakeLists.txt
  src/systems/buoyancy_engine/CMakeLists.txt
  src/systems/dvl/CMakeLists.txt
  src/systems/elevator/CMakeLists.txt
  src/systems/environmental_sensor_system/CMakeLists.txt
  src/systems/force_torque/CMakeLists.txt
  src/systems/imu/CMakeLists.txt
  src/systems/joint_controller/CMakeLists.txt
  src/systems/joint_position_controller/CMakeLists.txt
  src/systems/joint_state_publisher/CMakeLists.txt
  src/systems/joint_traj_control/CMakeLists.txt
  src/systems/kinetic_energy_monitor/CMakeLists.txt
  src/systems/log/CMakeLists.txt
  src/systems/logical_audio_sensor_plugin/CMakeLists.txt
  src/systems/logical_camera/CMakeLists.txt
  src/systems/magnetometer/CMakeLists.txt
  src/systems/model_photo_shoot/CMakeLists.txt
  src/systems/multicopter_control/CMakeLists.txt
  src/systems/multicopter_motor_model/CMakeLists.txt
  src/systems/navsat/CMakeLists.txt
  src/systems/particle_emitter/CMakeLists.txt
  src/systems/sensors/CMakeLists.txt
  src/systems/track_controller/CMakeLists.txt
  src/systems/tracked_vehicle/CMakeLists.txt
  src/systems/triggered_publisher/CMakeLists.txt
  src/systems/wind_effects/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/plugins/CMakeLists.txt
  tutorials/component_jointforcecmd.md
  tutorials/migrating_ardupilot_plugin.md
Labels: 🪵 jetty

#2863 [Documentation] Address #2850: Mention `GZ_SIM_SYSTEM_PLUGIN_PATH`
  tutorials/create_system_plugins.md
Labels: 🏛️ ionic

#2870 Re-enable UNIT_Gui_TEST
  src/gui/Gui_TEST.cc
Labels: 🪵 jetty

#2833 tutorials: Added hpc_clusters.md
  tutorials.md.in
  tutorials/hpc_clusters.md
Labels: 🪵 jetty

#2887 Set GZ_IP=127.0.0.1 in gz cmd tests
  src/CMakeLists.txt
Labels: 🎵 harmonic

#2888 Do not create light visuals on server side
  src/rendering/RenderUtil.cc
Labels: 🪵 jetty
