Repository gazebosim/gz-sim, pull requests merged in 2025-02, with the labels that each got.

#2747 Also handle SIGTERM gracefully
  src/cmd/cmdsim.rb.in
Labels: 🏛️ ionic

#2739 Improvement for Visualize lidar plugin
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.hh
Labels: 🏛️ ionic

#2754 Register MeshInertialCalculator when loading sim from an SDF string
  src/ServerPrivate.cc
  test/integration/mesh_inertia_calculation.cc
Labels: 🎵 harmonic

#2514 Physics: Ray intersections
  include/gz/sim/components/RaycastData.hh
  src/systems/physics/Physics.cc
  test/integration/physics_system.cc
Labels: 🏛️ ionic

#2763 Prepare for 8.9.0 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2769 Prepare for 9.1.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic

#2767 ADD: publish the wind information to gz and ros topic
  src/systems/wind_effects/WindEffects.cc
  src/systems/wind_effects/WindEffects.hh
Labels: 🏛️ ionic

#2724 Standalone `gz model` executable
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/ModelCommandAPI.cc
  src/cmd/ModelCommandAPI.hh
  src/cmd/ModelCommandAPI_TEST.cc
  src/cmd/cmdmodel.rb.in
  src/cmd/gz_TEST.cc
  src/cmd/model_main.cc
Labels: 🏛️ ionic, 🪵 jetty

#2679 New system plugin called `DriveToPoseController`
  examples/worlds/drive_to_pose_controller.sdf
  src/systems/CMakeLists.txt
  src/systems/drive_to_pose_controller/CMakeLists.txt
  src/systems/drive_to_pose_controller/DriveToPoseController.cc
  src/systems/drive_to_pose_controller/DriveToPoseController.hh
  test/integration/CMakeLists.txt
  test/integration/drive_to_pose_controller_system.cc
  test/worlds/drive_to_pose_controller.sdf
Labels: 🏛️ ionic, 🪵 jetty

#2770 Support mesh optimization params in mesh inertial calculator
  src/MeshInertiaCalculator.cc
  src/MeshInertiaCalculator.hh
  test/integration/mesh_inertia_calculation.cc
  test/worlds/mesh_inertia_calculation.sdf
  test/worlds/models/cylinder_dae_convex_decomposition/meshes/cylinder.dae
  test/worlds/models/cylinder_dae_convex_decomposition/model.config
  test/worlds/models/cylinder_dae_convex_decomposition/model.sdf
Labels: 🏛️ ionic

#2783 Fix SimtimeArgument test on homebrew
  src/cmd/gz_TEST.cc
Labels: 🏛️ ionic

#2760 Port Server changes from gz-sim8 to gz-sim9 (#2638 and #2754)
  src/Server.cc
  src/ServerPrivate.cc
  src/ServerPrivate.hh
  test/integration/mesh_inertia_calculation.cc
Labels: 🏛️ ionic

#2618 Fixed GIL release issue with Python System and Python TestFixture.
  python/test/gravity.sdf
  src/systems/python_system_loader/PythonSystemLoader.cc
Labels: 🏛️ ionic

#2794 Cleanup for Visualize Frustum
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.cc
  src/gui/plugins/global_illumination_vct/GlobalIlluminationVct.cc
  src/gui/plugins/visualize_frustum/VisualizeFrustum.cc
  src/gui/plugins/visualize_lidar/VisualizeLidar.cc
  src/systems/log/LogPlayback.cc
Labels: 🏛️ ionic

#2793 Update Windows CI badge in README.md
  README.md
Labels: 🏛️ ionic

#2775 Attempt to correct mass matrix in mesh inertia calculator
  src/CMakeLists.txt
  src/MeshInertiaCalculator.cc
  src/MeshInertiaCalculator.hh
  src/MeshInertiaCalculator_TEST.cc
Labels: 🏛️ ionic

#2782 Update auto inertial calculation tutorial
  tutorials/auto_inertia_calculation.md
Labels: 🏛️ ionic
