Repository gazebosim/gz-sim, pull requests merged in 2025-01, with the labels that each got.

#2643 Fix docker nightly build
  .dockerignore
  .github/workflows/docker-nightly.yml
  docker/Dockerfile.base
  docker/Dockerfile.nightly
  docker/README.md
  docker/run.bash
  docker/scripts/enable_gcc8.sh
  docker/scripts/install_common_deps.sh
  test/benchmark/README.md
Labels: 🏛️ ionic

#2630 apply_joint_force: Simplified using ComponentDefault
  src/systems/apply_joint_force/ApplyJointForce.cc
  tutorials/component_jointforcecmd.md
Labels: 🏛️ ionic

#2712 Preparation for 6.17.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#2721 Prepare for 8.8.0 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#2714 Better use of std::variant
  examples/worlds/ackermann_steering.sdf
  src/SystemLoader.cc
  src/gui/plugins/apply_force_torque/ApplyForceTorque.cc
  src/gui/plugins/component_inspector/ComponentInspector.cc
  src/gui/plugins/component_inspector_editor/ComponentInspectorEditor.cc
  src/gui/plugins/joint_position_controller/JointPositionController.cc
  src/gui/plugins/mouse_drag/MouseDrag.cc
  src/gui/plugins/playback_scrubber/PlaybackScrubber.cc
  src/gui/plugins/plot_3d/Plot3D.cc
  src/gui/plugins/resource_spawner/ResourceSpawner.cc
  src/gui/plugins/select_entities/SelectEntities.cc
  src/gui/plugins/transform_control/TransformControl.cc
  src/gui/plugins/view_angle/ViewAngle.cc
  src/gui/plugins/visualization_capabilities/VisualizationCapabilities.cc
  src/systems/apply_joint_force/ApplyJointForce.cc
  src/systems/collada_world_exporter/ColladaWorldExporter.cc
  src/systems/environmental_sensor_system/EnvironmentalSensorSystem.cc
  test/integration/battery_plugin.cc
  test/integration/contact_system.cc
  test/integration/sensors_system_battery.cc
Labels: 🏛️ ionic, 🪵 jetty

#2725 LinearBatteryPlugin stability improvement
  src/systems/battery_plugin/LinearBatteryPlugin.cc
  test/integration/battery_plugin.cc
Labels: 🏛️ ionic, 🪵 jetty

#2732 Fix mesh import filters not displaying correctly on KDE #2731
  src/gui/plugins/entity_tree/EntityTree.qml
Labels: 🏛️ ionic

#2741 Fix illegal anchor warnings
  src/gui/plugins/entity_context_menu/EntityContextMenuPlugin.qml
  src/gui/plugins/entity_tree/EntityTree.qml
Labels: 🏛️ ionic

#2745 Update install link
  README.md
Labels: 🏛️ ionic

#2707 Visualze Frustum
  examples/worlds/visualize_frustum.sdf
  src/gui/plugins/CMakeLists.txt
  src/gui/plugins/visualize_frustum/CMakeLists.txt
  src/gui/plugins/visualize_frustum/VisualizeFrustum.cc
  src/gui/plugins/visualize_frustum/VisualizeFrustum.hh
  src/gui/plugins/visualize_frustum/VisualizeFrustum.qml
  src/gui/plugins/visualize_frustum/VisualizeFrustum.qrc
Labels: needs upstream release, 🏛️ ionic, 🪵 jetty

#2749 Add debug msg to log auto computed inertial values
  src/SdfEntityCreator.cc
Labels: 🏛️ ionic
