Repository gazebosim/gz-sim, pull requests merged in 2025-09, with the labels that each got.

#3042 Update theory_hydrodynamics.md with slight wording change
  tutorials/theory_hydrodynamics.md
Labels: 🪵 jetty

#3052 Fix saving world through GUI
  src/gui/resources/GazeboDrawer.qml
Labels: 🪵 jetty

#3051 Add Null Check for Scene Initialization in `onRefreshCamerasImpl` to Prevent Crash
  src/gui/plugins/global_illumination_civct/GlobalIlluminationCiVct.cc
Labels: 🪵 jetty

#3065 Disable `UtilTest.ResolveSdfWorldFile` on macOS
  src/Util_TEST.cc
Labels: 🪵 jetty

#3076 Prepare for 9.4.0 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🏛️ ionic

#3081 Fixed create system plugins tutorial
  tutorials/create_system_plugins.md
Labels: 🪵 jetty

#3074 Fix sporadic crash when launching GUI client on windows
  src/cmd/sim_main.cc
  src/gui/Gui.cc
Labels: 🪵 jetty

#3087 Use common::findFile when searching for slip map in LookupWheelSlip system
  src/systems/lookup_wheel_slip/LookupWheelSlip.cc
Labels: 🪵 jetty

#3085 Set non-unique material to submesh when updating cast shadows property
  src/rendering/SceneManager.cc
Labels: needs upstream release, 🪵 jetty

#3056 Add tutorial on wheel slip systems
  examples/worlds/trisphere_cycle_wheel_slip.sdf
  tutorials.md.in
  tutorials/files/wheel_slip_systems/lookup_wheel_slip.gif
  tutorials/files/wheel_slip_systems/wheel_slip.gif
  tutorials/wheel_slip_systems.md
Labels: 🪵 jetty

#3092 Prepare for 10.0.0-pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🪵 jetty

#3088 Don't install vendored backward files (take II)
  Changelog.md
  vendor/backward-cpp/CMakeLists.txt
  vendor/backward-cpp/GAZEBO_MODIFIED_CODE.patch
Labels: 🪵 jetty

#3095 Prepare for 10.0.0 release
  CMakeLists.txt
Labels: 🪵 jetty
