Repository gazebosim/gz-sim, pull requests merged in 2025-03, with the labels that each got.

#2776 Attempts to print a stacktrace on segfault in our integration tests
  .github/workflows/ci.yml
  CMakeLists.txt
  test/CMakeLists.txt
  test/backward_vendor/backward-cpp/BackwardConfig.cmake
  test/backward_vendor/backward-cpp/CMakeLists.txt
  test/backward_vendor/backward-cpp/LICENSE.txt
  test/backward_vendor/backward-cpp/backward.cpp
  test/backward_vendor/backward-cpp/backward.hpp
Labels: 🏛️ ionic

#2817 Update custom sensor system example to make the sensor respect update rate
  examples/plugin/custom_sensor_system/OdometerSystem.cc
Labels: 🏛️ ionic

#2819 Gui.cc: return "" instead of nullptr
  src/gui/Gui.cc
Labels: 🎵 harmonic

#2827 Restrict docker-nightly workflow to base branch
  .github/workflows/docker-nightly.yml
Labels: 🏛️ ionic

#2297 Adding MecanumDrive plugin with Odom and Tf, with Tests.
  src/systems/mecanum_drive/MecanumDrive.cc
  test/integration/CMakeLists.txt
  test/integration/mecanum_drive_system.cc
  test/worlds/mecanum_drive.sdf
  test/worlds/mecanum_drive_custom_frame_id.sdf
  test/worlds/mecanum_drive_custom_tf_topic.sdf
  test/worlds/mecanum_drive_custom_topics.sdf
Labels: 🎵 harmonic

#2834 Update GZ_DISTRIBUTION to Jetty
  CMakeLists.txt
Labels: 🪵 jetty

#2836 Add more documentation to environmental_sensor.sdf example world
  examples/worlds/environmental_sensor.sdf
Labels: 🪵 jetty

#2838 Don't install vendored backward files
  test/backward_vendor/backward-cpp/CMakeLists.txt
Labels: 🏛️ ionic

#2841 Merge gz-sim9 ➡️ main
  test/backward_vendor/backward-cpp/CMakeLists.txt
Labels: 🪵 jetty
